<body data-page="module-kaiten-migration" data-protected="1">
<div class="crm-app"><aside class="crm-sidebar"><div class="crm-brand"><span class="crm-brand-mark"></span> <?= htmlspecialchars($t('app.name','TropaTT'),ENT_QUOTES,'UTF-8') ?></div><nav class="nav flex-column crm-nav"></nav></aside><div class="crm-main-wrap"><header class="crm-topbar py-2"><div class="container-fluid"></div></header><main class="crm-content crm-admin-page"><div class="crm-page-head"><div><ol class="breadcrumb mb-1"><li class="breadcrumb-item"><a href="index.php?route=admin"><?= htmlspecialchars($t('nav.admin','Администрирование'),ENT_QUOTES,'UTF-8') ?></a></li><li class="breadcrumb-item active">Миграция из Kaiten</li></ol><h1 class="crm-page-title">Миграция из Kaiten</h1><p class="crm-subtitle">Перенос пространств, досок, колонок, карточек, комментариев и файлов в проекты и задачи TropaTT CRM.</p></div></div>
<div id="kaitenMigrationApp" class="kaiten-migration-grid">
<section class="crm-card kaiten-panel"><div class="crm-card-header d-flex justify-content-between align-items-center"><h5 class="mb-0">Подключение Kaiten</h5><button class="btn crm-btn-primary btn-sm" id="kaitenAddConnection"><i class="fa-solid fa-plus"></i> Добавить</button></div><div class="crm-card-body"><div id="kaitenConnections" class="kaiten-state">Загрузка подключений…</div></div></section>
<section class="crm-card kaiten-panel"><div class="crm-card-header d-flex justify-content-between align-items-center"><h5 class="mb-0">Источник</h5><button class="btn crm-btn-secondary btn-sm" id="kaitenDiscover" disabled><i class="fa-solid fa-rotate"></i> Обновить</button></div><div class="crm-card-body"><div id="kaitenSpaces" class="kaiten-state">Выберите подключение.</div><div id="kaitenBoards" class="mt-3"></div><div id="kaitenUserMappings" class="mt-4"></div></div></section>
<section class="crm-card kaiten-panel"><div class="crm-card-header"><h5 class="mb-0">Настройки миграции</h5></div><div class="crm-card-body"><label class="form-label" for="kaitenMode">Режим</label><select id="kaitenMode" class="form-select mb-3"><option value="import">Однократный импорт</option><option value="sync">Синхронизация</option><option value="dry_run">Предпросмотр без записи</option></select><div class="form-check mb-2"><input class="form-check-input" type="checkbox" id="kaitenArchived"><label class="form-check-label" for="kaitenArchived">Включать архивные карточки</label></div><div class="form-check mb-2"><input class="form-check-input" type="checkbox" id="kaitenComments" checked><label class="form-check-label" for="kaitenComments">Импортировать комментарии</label></div><div class="form-check mb-2"><input class="form-check-input" type="checkbox" id="kaitenAttachments"><label class="form-check-label" for="kaitenAttachments">Скачивать вложения</label></div><div class="form-check mb-3"><input class="form-check-input" type="checkbox" id="kaitenHistory"><label class="form-check-label" for="kaitenHistory">Сохранять историю в отчёте</label></div><button class="btn crm-btn-primary w-100" id="kaitenStart" disabled><i class="fa-solid fa-play"></i> Создать job</button><div id="kaitenActionMessage" class="small mt-3" role="status"></div></div></section>
<section class="crm-card kaiten-panel kaiten-job-panel"><div class="crm-card-header d-flex justify-content-between align-items-center"><h5 class="mb-0">Выполнение</h5><button class="btn crm-btn-secondary btn-sm" id="kaitenRefreshJobs"><i class="fa-solid fa-rotate"></i></button></div><div class="crm-card-body"><div id="kaitenJobs" class="kaiten-state">Загрузка jobs…</div></div></section>
</div></main></div></div>
<div class="modal fade" id="kaitenConnectionModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><form id="kaitenConnectionForm"><div class="modal-header"><h5 class="modal-title">Новое подключение Kaiten</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button></div><div class="modal-body"><p class="text-muted small">Укажите адрес вашего tenant Kaiten, например https://company.kaiten.ru. Используется Bearer API token; токен хранится в CRM зашифрованным и не выводится обратно.</p><label class="form-label">Название</label><input class="form-control mb-3" name="name" maxlength="255" required placeholder="Рабочий Kaiten"><label class="form-label">URL tenant</label><input class="form-control mb-3" name="base_url" type="url" required placeholder="https://company.kaiten.ru"><label class="form-label">API token</label><input class="form-control" name="access_token" type="password" required autocomplete="new-password"><div id="kaitenConnectionError" class="alert alert-danger d-none mt-3"></div></div><div class="modal-footer"><button type="button" class="btn crm-btn-secondary" data-bs-dismiss="modal">Отмена</button><button class="btn crm-btn-primary" type="submit">Сохранить и проверить</button></div></form></div></div></div>
