<?php
declare(strict_types=1);

/**
 * MCP toolset profiles.
 *
 * The embedded MCP server exposes a large tool catalog (600+ tools). Loading
 * the whole catalog into every agent session is wasteful: it costs tens of
 * thousands of context tokens and makes tool selection harder. These profiles
 * let a client request only the domain it works with:
 *
 *   - `?toolset=tasks`  — appended to the MCP endpoint URL (e.g.
 *     `/api/index.php?route=api/v1/mcp&toolset=tasks`);
 *   - `params.toolset`  — passed to the `tools/list` JSON-RPC method;
 *   - comma-separated  — union of several profiles, e.g. `?toolset=tasks,projects`.
 *
 * Semantics:
 *   - `core` is the DEFAULT profile returned by `tools/list` when no toolset is
 *     requested: a curated cross-domain starter set (profile, search, dashboard,
 *     notifications, plus basic read/create for the main entities).
 *   - `tasks`, `projects`, `kb`, `people`, `time`, `admin` cover their domains
 *     in full.
 *   - `all` (implicit, not listed here) returns every permission-visible tool.
 *     Any tool not assigned to a profile below is only reachable via `all` or
 *     a direct `tools/call` by name — opt-in by design.
 *
 * A tool may belong to several profiles (e.g. `crm_search` is in both `core`
 * and `kb`). Every listed name must exist in `mcp_permissions.php` — the local
 * unit test `mcp_toolsets_unit.php` enforces this fail-closed.
 */
return [
    'core' => [
        'title' => 'Core',
        'description' => 'Default profile: mega-tools (consolidated intent-based) for tasks, projects, people, CRM records, time, knowledge, AI, admin, plus profile, search, dashboard, notifications.',
        'tools' => [
            // Profile and navigation
            'crm_get_current_user',
            'crm_get_health_status',
            'crm_get_profile',
            'crm_update_profile',
            'crm_get_profile_preferences',
            'crm_update_profile_preferences',
            'crm_get_menu',
            'crm_get_menu_preferences',
            // Search and dashboard
            'crm_search',
            'crm_get_dashboard_summary',
            'crm_get_dashboard_widgets',
            // Notifications and activity
            'crm_get_activity_feed',
            'crm_list_notifications',
            'crm_get_notification_counters',
            'crm_mark_notification_read',
            'crm_mark_all_notifications_read',
            // Mega-tools: consolidated intent-based (replaces dozens of CRUD tools)
            'crm_task',
            'crm_project',
            'crm_people',
            'crm_crm',
            'crm_time',
            'crm_knowledge',
            'crm_ai',
            'crm_admin',
            // AgentOS tools: bundle and memory
            'crm_agent_bundle',
            'crm_agent_memory',
        ],
    ],
    'tasks' => [
        'title' => 'Tasks',
        'description' => 'Full task work management: tasks, subtasks, comments and drafts, tags, checklists, dependencies, relations, estimates, board and bulk operations, saved views, recurring rules, reminders, SLA, workflow rules and approvals.',
        'tools' => [
            // Tasks
            'crm_list_tasks',
            'crm_get_task',
            'crm_get_task_by_key',
            'crm_get_task_board',
            'crm_create_task',
            'crm_update_task',
            'crm_delete_task',
            'crm_move_task',
            'crm_bulk_update_tasks',
            // Subtasks
            'crm_list_subtasks',
            'crm_create_subtask',
            'crm_update_subtask',
            'crm_delete_subtask',
            // Comments and drafts
            'crm_list_task_comments',
            'crm_add_task_comment',
            'crm_update_comment',
            'crm_delete_comment',
            'crm_get_comment_draft',
            'crm_save_comment_draft',
            'crm_delete_comment_draft',
            // Tags
            'crm_list_task_tags',
            'crm_attach_task_tag',
            'crm_detach_task_tag',
            // Checklists
            'crm_list_task_checklists',
            'crm_list_checklist_items',
            'crm_create_task_checklist',
            'crm_create_checklist_item',
            'crm_update_checklist',
            'crm_update_checklist_item',
            'crm_delete_checklist',
            'crm_delete_checklist_item',
            // Dependencies
            'crm_list_dependencies',
            'crm_create_dependency',
            'crm_delete_dependency',
            // Relations
            'crm_list_task_relations',
            'crm_create_task_relation',
            'crm_delete_task_relation',
            // Estimates
            'crm_list_task_estimates',
            'crm_assign_task_estimate',
            'crm_remove_task_estimate',
            // Activity
            'crm_list_task_activity',
            // Saved views (task filters)
            'crm_list_saved_views',
            'crm_get_saved_view',
            'crm_get_saved_view_task_filters',
            'crm_create_saved_view',
            'crm_update_saved_view',
            'crm_archive_saved_view',
            'crm_delete_saved_view',
            'crm_duplicate_saved_view',
            'crm_pin_saved_view',
            'crm_touch_saved_view',
            // Recurring rules
            'crm_list_recurring_rules',
            'crm_get_recurring_rule',
            'crm_create_recurring_rule',
            'crm_update_recurring_rule',
            'crm_delete_recurring_rule',
            'crm_pause_recurring_rule',
            'crm_resume_recurring_rule',
            // Reminders
            'crm_list_reminders',
            'crm_get_reminder',
            'crm_create_reminder',
            'crm_update_reminder',
            'crm_delete_reminder',
            // SLA
            'crm_list_sla_policies',
            'crm_get_sla_policy',
            'crm_create_sla_policy',
            'crm_update_sla_policy',
            'crm_delete_sla_policy',
            'crm_assign_sla_to_task',
            'crm_get_sla_report',
            // Workflow rules (task automation)
            'crm_list_workflow_rules',
            'crm_get_workflow_rule',
            'crm_create_workflow_rule',
            'crm_update_workflow_rule',
            'crm_delete_workflow_rule',
            'crm_list_workflow_runs',
            'crm_run_workflow_rule_test',
            // Approvals
            'crm_list_approvals',
            'crm_get_approval',
            'crm_create_approval',
            'crm_approve_request',
            'crm_reject_request',
        ],
    ],
    'projects' => [
        'title' => 'Projects',
        'description' => 'Project management: projects, milestones, cycles (sprints), project modules, Gantt timeline, workload, summary/risks, estimate summaries, templates and the client cabinet portal.',
        'tools' => [
            // Projects
            'crm_list_projects',
            'crm_get_project',
            'crm_create_project',
            'crm_update_project',
            'crm_delete_project',
            'crm_get_project_summary',
            'crm_get_project_risks',
            'crm_get_project_timeline',
            'crm_get_project_workload',
            'crm_get_project_estimate_summary',
            'crm_get_project_milestones_summary',
            // Milestones
            'crm_list_milestones',
            'crm_get_milestone',
            'crm_create_milestone',
            'crm_update_milestone',
            'crm_delete_milestone',
            // Cycles / sprints
            'crm_list_cycles',
            'crm_get_cycle',
            'crm_create_cycle',
            'crm_update_cycle',
            'crm_delete_cycle',
            'crm_archive_cycle',
            'crm_complete_cycle',
            'crm_reopen_cycle',
            'crm_start_cycle',
            'crm_list_cycle_tasks',
            'crm_add_tasks_to_cycle',
            'crm_remove_cycle_task',
            'crm_transfer_unfinished_cycle_tasks',
            'crm_get_cycle_summary',
            'crm_get_cycle_estimate_summary',
            // Project modules
            'crm_list_project_modules',
            'crm_get_project_module',
            'crm_create_project_module',
            'crm_update_project_module',
            'crm_archive_project_module',
            'crm_delete_project_module',
            'crm_list_project_module_tasks',
            'crm_list_project_module_members',
            'crm_list_project_module_links',
            'crm_add_tasks_to_project_module',
            'crm_add_members_to_project_module',
            'crm_add_project_module_link',
            'crm_update_project_module_link',
            'crm_delete_project_module_link',
            'crm_remove_project_module_task',
            'crm_remove_project_module_member',
            'crm_get_module_estimate_summary',
            // Templates (task/project templates)
            'crm_list_templates',
            'crm_get_template',
            'crm_create_template',
            'crm_update_template',
            'crm_delete_template',
            'crm_apply_template',
            // Client cabinet portal
            'crm_list_client_cabinet_projects',
            'crm_get_client_cabinet_project',
            'crm_list_client_cabinet_project_tasks',
            'crm_create_project_from_idea_tasks',
        ],
    ],
    'kb' => [
        'title' => 'Knowledge Base',
        'description' => 'Knowledge base: spaces, pages, tree, drafts, comments, versions, locks, tags, links, files, favorites, subscriptions, review queue, export/import, reindex and the knowledge AI helpers.',
        'tools' => [
            'crm_search_knowledge',
            'crm_get_knowledge_overview',
            'crm_get_knowledge_analytics',
            'crm_get_knowledge_entity_pages',
            'crm_get_knowledge_suggest',
            // Spaces
            'crm_list_knowledge_spaces',
            'crm_list_knowledge_spaces_tree',
            'crm_get_knowledge_space',
            'crm_create_knowledge_space',
            'crm_update_knowledge_space',
            'crm_archive_knowledge_space',
            'crm_restore_knowledge_space',
            'crm_get_knowledge_space_permissions',
            'crm_add_knowledge_space_permission',
            'crm_remove_knowledge_space_permission',
            // Pages
            'crm_list_knowledge_pages',
            'crm_list_knowledge_recent',
            'crm_list_knowledge_popular',
            'crm_list_knowledge_outdated',
            'crm_get_knowledge_page',
            'crm_get_knowledge_tree',
            'crm_create_knowledge_page',
            'crm_update_knowledge_page',
            'crm_archive_knowledge_page',
            'crm_restore_knowledge_page',
            'crm_move_knowledge_page',
            'crm_duplicate_knowledge_page',
            'crm_lock_knowledge_page',
            'crm_unlock_knowledge_page',
            'crm_publish_knowledge_page',
            'crm_get_knowledge_page_draft',
            'crm_save_knowledge_page_draft',
            'crm_delete_knowledge_draft',
            'crm_cleanup_knowledge_drafts',
            'crm_favorite_knowledge_page',
            'crm_unfavorite_knowledge_page',
            'crm_list_knowledge_favorites',
            'crm_subscribe_knowledge_page',
            'crm_unsubscribe_knowledge_page',
            'crm_request_knowledge_review',
            'crm_approve_knowledge_review',
            'crm_reject_knowledge_review',
            'crm_resolve_knowledge_comment',
            'crm_reopen_knowledge_comment',
            'crm_list_knowledge_review_queue',
            // Comments
            'crm_list_knowledge_comments',
            'crm_add_knowledge_comment',
            'crm_delete_knowledge_comment',
            // Versions
            'crm_list_knowledge_page_versions',
            'crm_get_knowledge_page_version',
            'crm_diff_knowledge_page_version',
            'crm_restore_knowledge_page_version',
            'crm_lock_knowledge_page_version',
            'crm_unlock_knowledge_page_version',
            // Tags and links
            'crm_list_knowledge_page_tags',
            'crm_attach_knowledge_page_tag',
            'crm_detach_knowledge_page_tag',
            'crm_list_knowledge_page_links',
            'crm_link_knowledge_page_entity',
            'crm_delete_knowledge_page_link',
            // Files, export/import
            'crm_list_knowledge_files',
            'crm_delete_knowledge_file',
            'crm_upload_knowledge_file_base64',
            'crm_export_knowledge_page',
            'crm_export_knowledge_space',
            'crm_export_knowledge_all',
            'crm_import_knowledge_pages',
            // Templates
            'crm_list_knowledge_templates',
            'crm_create_knowledge_template',
            // Maintenance and AI
            'crm_rebuild_knowledge_permissions',
            'crm_reindex_knowledge',
            'crm_create_knowledge_ai_summary',
            'crm_create_knowledge_ai_explanation',
            'crm_create_knowledge_ai_checklist',
            'crm_create_knowledge_ai_faq_from_comments',
            'crm_create_knowledge_ai_suggest_for_task',
            'crm_suggest_knowledge_ai_structure',
            'crm_find_knowledge_ai_similar',
            'crm_find_knowledge_ai_duplicates',
            'crm_find_knowledge_ai_orphans',
        ],
    ],
    'people' => [
        'title' => 'People & CRM Records',
        'description' => 'People management: users, teams, departments, roles and permissions, invitations, impersonation, plus CRM records: clients, counterparties, companies, contacts and organizations.',
        'tools' => [
            // Users
            'crm_list_users',
            'crm_get_user',
            'crm_get_user_activity',
            'crm_create_user',
            'crm_update_user',
            'crm_delete_user',
            'crm_get_user_token_info',
            'crm_revoke_user_token',
            'crm_rotate_user_token',
            // Teams
            'crm_list_teams',
            'crm_get_team',
            'crm_create_team',
            'crm_update_team',
            'crm_delete_team',
            // Departments
            'crm_list_departments',
            'crm_get_department',
            'crm_create_department',
            'crm_update_department',
            'crm_delete_department',
            // Roles and permissions
            'crm_list_roles',
            'crm_list_permissions',
            'crm_get_role_permissions',
            'crm_set_role_permissions',
            'crm_create_role',
            'crm_update_role',
            'crm_delete_role',
            // Clients
            'crm_list_clients',
            'crm_get_client',
            'crm_create_client',
            'crm_update_client',
            'crm_delete_client',
            // Counterparties
            'crm_list_counterparties',
            'crm_get_counterparty',
            'crm_create_counterparty',
            'crm_update_counterparty',
            'crm_delete_counterparty',
            // Companies
            'crm_list_companies',
            'crm_get_company',
            'crm_create_company',
            'crm_update_company',
            'crm_delete_company',
            // Contacts
            'crm_list_contacts',
            'crm_get_contact',
            'crm_create_contact',
            'crm_update_contact',
            'crm_delete_contact',
            // Organizations
            'crm_list_organizations',
            'crm_get_organization',
            'crm_create_organization',
            'crm_update_organization',
            'crm_delete_organization',
            'crm_list_organization_members',
            'crm_add_organization_member',
            'crm_remove_organization_member',
            // Invitations
            'crm_list_invitations',
            'crm_create_invitation',
            'crm_accept_invitation',
            // Impersonation
            'crm_get_impersonation_status',
            'crm_start_impersonation',
            'crm_stop_impersonation',
        ],
    ],
    'time' => [
        'title' => 'Time & Calendar',
        'description' => 'Time tracking and planning: worklogs (list, matrix, summaries, earnings), calendar events and agenda, business calendars, holidays and working hours.',
        'tools' => [
            // Worklogs
            'crm_list_worklogs',
            'crm_get_worklog',
            'crm_get_worklog_detail',
            'crm_get_worklog_summary',
            'crm_get_worklog_task_summary',
            'crm_get_worklog_matrix',
            'crm_get_worklog_earnings',
            'crm_create_worklog',
            'crm_update_worklog',
            'crm_delete_worklog',
            // Calendar
            'crm_list_calendar_events',
            'crm_get_calendar_event',
            'crm_get_calendar_agenda',
            'crm_get_calendar_my_month',
            'crm_create_calendar_event',
            'crm_update_calendar_event',
            'crm_delete_calendar_event',
            // Business calendars
            'crm_list_business_calendars',
            'crm_get_business_calendar',
            'crm_create_business_calendar',
            'crm_update_business_calendar',
            'crm_delete_business_calendar',
            // Holidays
            'crm_list_holidays',
            'crm_get_holiday',
            'crm_create_holiday',
            'crm_update_holiday',
            'crm_delete_holiday',
            // Working hours
            'crm_list_working_hours',
            'crm_get_working_hours',
            'crm_create_working_hours',
            'crm_update_working_hours',
            'crm_delete_working_hours',
        ],
    ],
    'admin' => [
        'title' => 'Administration',
        'description' => 'System administration: settings, feature flags, cache, modules, core updates, ops, API clients and keys, webhooks, audit/security/request logs, custom fields, statuses/priorities/tags, AI configuration and jobs, intake, import/export, recycle bin, analytics and admin widgets.',
        'tools' => [
            // Settings, flags, retention
            'crm_list_settings',
            'crm_get_setting',
            'crm_get_retention_metadata',
            'crm_set_retention_metadata',
            'crm_list_feature_flags',
            'crm_update_feature_flag',
            // Cache
            'crm_get_cache_stats',
            'crm_clear_cache',
            // Modules
            'crm_list_modules',
            'crm_get_module',
            'crm_install_module',
            'crm_activate_module',
            'crm_deactivate_module',
            'crm_uninstall_module',
            'crm_get_module_config',
            'crm_update_module_config',
            'crm_get_module_health',
            'crm_get_module_migrations',
            'crm_get_module_errors',
            'crm_clear_module_errors',
            // Core version and updates
            'crm_get_core_version',
            'crm_get_core_update_status',
            'crm_check_core_update',
            'crm_run_core_update_preflight',
            'crm_get_core_update_changes',
            'crm_get_core_update_session',
            'crm_get_core_update_history',
            'crm_get_core_update_log',
            // Ops
            'crm_get_ops_system',
            'crm_get_ops_metrics',
            'crm_run_ops_jobs',
            // API clients and keys
            'crm_list_api_clients',
            'crm_get_api_client',
            'crm_create_api_client',
            'crm_update_api_client',
            'crm_delete_api_client',
            'crm_list_api_client_keys',
            'crm_issue_api_client_key',
            'crm_revoke_api_key',
            'crm_rotate_api_key',
            'crm_get_api_key_usage',
            // Webhooks
            'crm_list_webhooks',
            'crm_list_webhook_deliveries',
            'crm_create_webhook',
            'crm_update_webhook',
            'crm_delete_webhook',
            'crm_test_webhook',
            // Logs
            'crm_list_audit_log',
            'crm_list_security_log',
            'crm_list_request_logs',
            // Custom fields
            'crm_list_custom_fields',
            'crm_get_custom_field',
            'crm_get_custom_field_values',
            'crm_set_custom_field_values',
            'crm_create_custom_field',
            'crm_update_custom_field',
            'crm_delete_custom_field',
            // Statuses, priorities, tags management
            'crm_list_statuses',
            'crm_list_priorities',
            'crm_create_status',
            'crm_update_status',
            'crm_delete_status',
            'crm_create_priority',
            'crm_update_priority',
            'crm_delete_priority',
            'crm_create_tag',
            'crm_update_tag',
            'crm_delete_tag',
            // Admin widgets and settings
            'crm_get_admin_summary_widget',
            'crm_get_admin_system_widget',
            'crm_get_frontend_errors_chart',
            'crm_get_admin_knowledge_settings',
            'crm_update_admin_knowledge_settings',
            'crm_get_admin_role_matrix',
            'crm_update_admin_role_matrix',
            // OpenAPI inventory
            'crm_get_openapi_spec',
            'crm_list_api_endpoints',
            // Intake
            'crm_list_intake_items',
            'crm_get_intake_item',
            'crm_create_intake_item',
            'crm_update_intake_item',
            'crm_delete_intake_item',
            'crm_accept_intake_item',
            'crm_reject_intake_item',
            'crm_snooze_intake_item',
            'crm_reopen_intake_item',
            'crm_duplicate_intake_item',
            // Import / export
            'crm_list_import_jobs',
            'crm_get_import_job',
            'crm_create_import_job',
            'crm_cancel_import_job',
            'crm_retry_import_job',
            'crm_list_export_jobs',
            'crm_get_export_job',
            'crm_create_export_job',
            'crm_cancel_export_job',
            'crm_retry_export_job',
            'crm_download_export_job',
            // Recycle bin
            'crm_list_recycle_bin',
            'crm_restore_recycle_bin_item',
            'crm_purge_recycle_bin_item',
            // Analytics
            'crm_get_analytics_summary',
            'crm_list_analytics_projects',
            'crm_list_analytics_users',
            // AI configuration, jobs and usage
            'crm_get_ai_settings',
            'crm_update_ai_settings',
            'crm_list_ai_providers',
            'crm_get_ai_provider',
            'crm_list_ai_models',
            'crm_list_ai_intents',
            'crm_update_ai_intent',
            'crm_list_ai_prompts',
            'crm_create_ai_prompt',
            'crm_update_ai_prompt',
            'crm_list_ai_json_schemas',
            'crm_create_ai_json_schema',
            'crm_update_ai_json_schema',
            'crm_list_ai_usage',
            'crm_list_ai_audit',
            'crm_list_ai_retention_policies',
            'crm_get_ai_preferences',
            'crm_update_ai_preferences',
            'crm_get_ai_availability',
            'crm_list_ai_action_types',
            'crm_execute_ai_action',
            'crm_list_ai_suggestions',
            'crm_get_ai_suggestion',
            'crm_confirm_ai_suggestion',
            'crm_dismiss_ai_suggestion',
            'crm_preview_apply_ai_suggestion',
            'crm_list_ai_jobs',
            'crm_get_ai_job',
            'crm_run_once_ai_job',
            'crm_dry_run_ai_job',
            'crm_retry_ai_job',
            // AI intents (user-facing helpers)
            'crm_create_ai_task_summary',
            'crm_create_ai_task_decomposition',
            'crm_create_ai_task_checklist',
            'crm_create_ai_task_quality',
            'crm_create_ai_task_next_action',
            'crm_create_ai_project_summary',
            'crm_create_ai_project_risks',
            'crm_create_ai_dashboard_digest',
            'crm_create_ai_my_day_plan',
            'crm_create_ai_my_week_plan',
            'crm_create_ai_analytics_kpi_explanation',
            'crm_create_ai_analytics_risks_explanation',
            'crm_create_ai_analytics_team_workload_summary',
            'crm_search_ai_semantic',
        ],
    ],
];