<?php declare(strict_types=1); ?>
<?php $title = 'TropaTT — Статусы задач'; ?>
<body data-page="admin" data-protected="1"><div class="crm-app"><aside class="crm-sidebar"><div class="crm-brand"><span class="crm-brand-mark"></span> TropaTT</div><nav class="nav flex-column crm-nav"></nav></aside>
<div class="crm-main-wrap"><header class="crm-topbar py-2"><div class="container-fluid"></div></header>
<main class="crm-content crm-admin-page"><div class="crm-page-head"><div><ol class="breadcrumb mb-1"><li class="breadcrumb-item"><a href="index.php?route=admin">Админка</a></li><li class="breadcrumb-item active">Статусы задач</li></ol><h1 class="crm-page-title">Статусы задач</h1><p class="crm-subtitle">Справочник статусов задач: порядок, цвет и активность.</p></div><div class="d-flex gap-2"><button class="btn crm-btn-primary" id="statusCreateOpenBtn" type="button" data-bs-toggle="modal" data-bs-target="#statusCreateModal">Создать статус</button></div></div>

<div class="crm-card crm-section-card p-0 table-responsive mb-3"><table class="table crm-table mb-0"><thead><tr><th>Название</th><th>Вид в интерфейсе</th><th>Порядок</th><th>Тип</th><th style="width:170px">Действия</th></tr></thead><tbody id="adminStatusesTableBody"><tr><td colspan="5" class="text-muted">Загрузка статусов...</td></tr></tbody></table></div>

<div class="crm-card crm-section-card"><div class="crm-section-head"><div><h2 class="h6 mb-0">Предпросмотр статусов</h2><div class="crm-section-note">Проверка цветов, контраста и визуального порядка перед использованием в интерфейсе.</div></div></div><div id="adminStatusesPreview" class="d-flex flex-wrap gap-2"><span class="crm-badge archived">Загрузка...</span></div></div>

<div class="modal fade" id="statusCreateModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Создать статус</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button></div><form id="statusCreateForm"><div class="modal-body"><div class="mb-3"><label class="form-label">Название</label><input class="form-control" name="title" maxlength="255" required></div><div class="mb-3"><label class="form-label">Код</label><input class="form-control" name="code" maxlength="64" required placeholder="waiting_client"></div><div class="mb-3"><label class="form-label">Тип статуса</label><select class="form-select" name="scope"><option value="task">Задача</option><option value="project">Проект</option></select></div><div class="mb-3"><label class="form-label">Цвет (HEX)</label><div class="crm-status-color-picker"><input class="form-control form-control-color" type="color" id="statusCreateColorPicker" value="#64748b"><input class="form-control" name="color" maxlength="7" value="#64748b"><span class="crm-badge crm-status-color-preview" id="statusCreateColorPreview">Превью</span></div></div><div><label class="form-label">Порядок</label><input type="number" class="form-control" name="sort_order" value="100"></div></div><div class="modal-footer"><button class="btn crm-btn-secondary" type="button" data-bs-dismiss="modal">Отмена</button><button class="btn crm-btn-primary" type="submit">Создать</button></div></form></div></div></div>

<div class="modal fade" id="statusEditModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Редактировать статус</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button></div><form id="statusEditForm"><div class="modal-body"><input type="hidden" name="public_id"><div class="mb-3"><label class="form-label">Название</label><input class="form-control" name="title" maxlength="255" required></div><div class="mb-3"><label class="form-label">Код</label><input class="form-control" name="code" maxlength="64" required></div><div class="mb-3"><label class="form-label">Тип статуса</label><select class="form-select" name="scope"><option value="task">Задача</option><option value="project">Проект</option></select></div><div class="mb-3"><label class="form-label">Цвет (HEX)</label><div class="crm-status-color-picker"><input class="form-control form-control-color" type="color" id="statusEditColorPicker" value="#64748b"><input class="form-control" name="color" maxlength="7" value="#64748b"><span class="crm-badge crm-status-color-preview" id="statusEditColorPreview">Превью</span></div></div><div><label class="form-label">Порядок</label><input type="number" class="form-control" name="sort_order"></div></div><div class="modal-footer"><button class="btn crm-btn-secondary" type="button" data-bs-dismiss="modal">Отмена</button><button class="btn crm-btn-primary" type="submit">Сохранить</button></div></form></div></div></div>

<div class="modal fade" id="statusDeleteModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Удалить статус</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button></div><form id="statusDeleteForm"><div class="modal-body"><input type="hidden" name="public_id"><p id="statusDeleteText" class="mb-2">Статус будет удален.</p><label class="form-label">Перенести элементы в другой статус (опционально)</label><select class="form-select" name="remap_to_public_id"><option value="">Не переносить</option></select></div><div class="modal-footer"><button class="btn crm-btn-secondary" type="button" data-bs-dismiss="modal">Отмена</button><button class="btn crm-btn-danger-soft" type="submit">Удалить</button></div></form></div></div></div>

</main></div></div>
