<?php declare(strict_types=1); ?>
<?php $title = 'TropaTT — Роли пользователей'; ?>
<body data-page="admin" data-protected="1"><div class="crm-app"><aside class="crm-sidebar"><div class="crm-brand"><span class="crm-brand-mark"></span> TropaTT</div><nav class="nav flex-column crm-nav"></nav></aside>
<div class="crm-main-wrap"><header class="crm-topbar py-2"><div class="container-fluid"></div></header>
<main class="crm-content crm-admin-page"><div class="crm-page-head"><div><ol class="breadcrumb mb-1"><li class="breadcrumb-item"><a href="index.php?route=admin">Админка</a></li><li class="breadcrumb-item active">Роли</li></ol><h1 class="crm-page-title">Роли</h1><p class="crm-subtitle">Роли пользователей и наборы прав доступа.</p></div><div class="d-flex gap-2"><button class="btn crm-btn-primary" id="roleCreateOpenBtn" type="button">Создать роль</button></div></div>

<div class="row g-3 mb-3 crm-kpi-row"><div class="col-md-4"><div class="crm-card crm-kpi-card"><small class="text-muted">Всего ролей</small><h2 class="h4 mb-0" id="rolesMetricTotal">0</h2></div></div><div class="col-md-4"><div class="crm-card crm-kpi-card"><small class="text-muted">Кастомных ролей</small><h2 class="h4 mb-0" id="rolesMetricCustom">0</h2></div></div><div class="col-md-4"><div class="crm-card crm-kpi-card"><small class="text-muted">Системных ролей</small><h2 class="h4 mb-0" id="rolesMetricSystem">0</h2></div></div></div>

<div class="crm-card crm-section-card p-0 table-responsive"><table class="table crm-table mb-0"><thead><tr><th>Роль</th><th>Доступы</th><th>Тип</th><th>Изменено</th><th style="width:170px">Действия</th></tr></thead><tbody id="adminRolesTableBody"><tr><td colspan="5" class="text-muted">Загрузка ролей...</td></tr></tbody></table></div>

<div class="modal fade" id="roleCreateModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Создать роль</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button></div><form id="roleCreateForm"><div class="modal-body"><div class="row g-2 mb-3"><div class="col-md-6"><label class="form-label">Код роли</label><input class="form-control" name="code" maxlength="64" placeholder="qa_lead"></div><div class="col-md-6"><label class="form-label">Название роли</label><input class="form-control" name="title" maxlength="255" placeholder="Руководитель QA"></div></div><label class="form-label">Доступы</label><div class="border rounded p-2 crm-max-h-320 crm-overflow-auto" id="roleCreatePermissionsList"><div class="text-muted">Загрузка доступов...</div></div></div><div class="modal-footer"><button class="btn crm-btn-secondary" type="button" data-bs-dismiss="modal">Отмена</button><button class="btn crm-btn-primary" type="submit">Создать</button></div></form></div></div></div>

<div class="modal fade" id="roleEditModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Редактировать роль</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button></div><form id="roleEditForm"><div class="modal-body"><input type="hidden" name="public_id"><div class="row g-2 mb-3"><div class="col-md-6"><label class="form-label">Код роли</label><input class="form-control" name="code" maxlength="64"></div><div class="col-md-6"><label class="form-label">Название роли</label><input class="form-control" name="title" maxlength="255"></div></div><label class="form-label">Доступы</label><div class="border rounded p-2 crm-max-h-320 crm-overflow-auto" id="roleEditPermissionsList"><div class="text-muted">Загрузка доступов...</div></div></div><div class="modal-footer"><button class="btn crm-btn-secondary" type="button" data-bs-dismiss="modal">Отмена</button><button class="btn crm-btn-primary" type="submit">Сохранить</button></div></form></div></div></div>

<div class="modal fade" id="roleDeleteModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Удалить роль?</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button></div><div class="modal-body"><input type="hidden" id="roleDeletePublicId"><p class="mb-0" id="roleDeleteText">Роль будет удалена без возможности восстановления.</p></div><div class="modal-footer"><button class="btn crm-btn-secondary" type="button" data-bs-dismiss="modal">Отмена</button><button class="btn crm-btn-danger-soft" type="button" id="roleDeleteConfirmBtn">Удалить</button></div></div></div></div>

</main></div></div>
