<?php declare(strict_types=1); ?>
<?php $title = 'TropaTT — Админка'; ?>
<body data-page="admin" data-protected="1"><div class="crm-app"><aside class="crm-sidebar"><div class="crm-brand"><span class="crm-brand-mark"></span> TropaTT</div><nav class="nav flex-column crm-nav"></nav></aside>
<div class="crm-main-wrap"><header class="crm-topbar py-2"><div class="container-fluid"></div></header>
<main class="crm-content crm-admin-page crm-admin-overview-page"><div class="crm-page-head"><div><h1 class="crm-page-title">Админка</h1><p class="crm-subtitle">Пользователи, роли, статусы, автоматизация, логи и интеграции.</p></div></div>
<div class="row g-3 mb-3 crm-admin-overview-nav">
  <div class="col-md-3"><a class="crm-card crm-card-hover crm-section-card d-block text-decoration-none" href="index.php?route=admin-statuses"><h2 class="h6">Статусы задач</h2><p class="text-muted mb-0">Справочник статусов: добавить, редактировать, удалить.</p></a></div>
  <div class="col-md-3"><a class="crm-card crm-card-hover crm-section-card d-block text-decoration-none" href="index.php?route=admin-tags"><h2 class="h6">Теги</h2><p class="text-muted mb-0">Управление тегами для задач и проектов.</p></a></div>
  <div class="col-md-3"><a class="crm-card crm-card-hover crm-section-card d-block text-decoration-none" href="index.php?route=admin-users"><h2 class="h6">Пользователи</h2><p class="text-muted mb-0">Управление учетными записями сотрудников.</p></a></div>
  <div class="col-md-3"><a class="crm-card crm-card-hover crm-section-card d-block text-decoration-none" href="index.php?route=admin-roles"><h2 class="h6">Роли</h2><p class="text-muted mb-0">Настройка прав доступа по ролям.</p></a></div>
  <div class="col-md-3"><a class="crm-card crm-card-hover crm-section-card d-block text-decoration-none" href="index.php?route=admin-logs"><h2 class="h6">Логи пользователей</h2><p class="text-muted mb-0">История действий по каждому пользователю.</p></a></div>
  <div class="col-md-3"><a class="crm-card crm-card-hover crm-section-card d-block text-decoration-none" href="index.php?route=admin-workflow"><h2 class="h6">Правила автоматизации</h2><p class="text-muted mb-0">Триггеры, действия и логи выполнения workflow.</p></a></div>
  <div class="col-md-3"><a class="crm-card crm-card-hover crm-section-card d-block text-decoration-none" href="index.php?route=approvals"><h2 class="h6">Согласования</h2><p class="text-muted mb-0">Запросы на утверждение задач и проектов внутри CRM.</p></a></div>
  <div class="col-md-3"><a class="crm-card crm-card-hover crm-section-card d-block text-decoration-none" href="index.php?route=recurring"><h2 class="h6">Периодические задачи</h2><p class="text-muted mb-0">Шаблоны, которые создают задачи по расписанию.</p></a></div>
  <div class="col-md-3"><a class="crm-card crm-card-hover crm-section-card d-block text-decoration-none" href="index.php?route=admin-api-clients"><h2 class="h6">API-клиенты</h2><p class="text-muted mb-0">Интеграционные клиенты, ключи и журналы использования.</p></a></div>
  <div class="col-md-3"><a class="crm-card crm-card-hover crm-section-card d-block text-decoration-none" href="index.php?route=admin-settings"><h2 class="h6">Системные настройки</h2><p class="text-muted mb-0">Обзор системных настроек и политики хранения данных.</p></a></div>
  <div class="col-md-3"><a class="crm-card crm-card-hover crm-section-card d-block text-decoration-none" href="index.php?route=admin-jobs"><h2 class="h6">Задания / импорт / экспорт</h2><p class="text-muted mb-0">Очередь задач импорта, экспорта и фоновых AI-заданий.</p></a></div>
  <div class="col-md-3"><a class="crm-card crm-card-hover crm-section-card d-block text-decoration-none" href="index.php?route=admin-ai" data-requires-ai-admin="1"><h2 class="h6">AI-интеграция</h2><p class="text-muted mb-0">LLM-провайдеры, секреты доступа и retention policy.</p></a></div>
  <div class="col-md-3"><a class="crm-card crm-card-hover crm-section-card d-block text-decoration-none" href="index.php?route=admin-modules"><h2 class="h6">Модули</h2><p class="text-muted mb-0">Установка, активация и управление модулями расширения.</p></a></div>
</div>
<div class="row g-3 mb-3 crm-kpi-row"><div class="col-md-3"><div class="crm-card crm-kpi-card"><small class="text-muted">Сервисы онлайн</small><div id="adminKpiServicesValue" class="h4 crm-kpi-value" aria-label="Сервисы онлайн">Загрузка...</div><span id="adminKpiServicesBadge" class="crm-badge archived">Ожидание данных</span></div></div><div class="col-md-3"><div class="crm-card crm-kpi-card"><small class="text-muted">Ошибки за 24ч</small><div id="adminKpiErrorsValue" class="h4 crm-kpi-value" aria-label="Ошибки за 24 часа">Загрузка...</div><span id="adminKpiErrorsBadge" class="crm-badge archived">Ожидание данных</span></div></div><div class="col-md-3"><div class="crm-card crm-kpi-card"><small class="text-muted">Активные API-ключи</small><div id="adminKpiKeysValue" class="h4 crm-kpi-value" aria-label="Активные API-ключи">Загрузка...</div><span id="adminKpiKeysBadge" class="crm-badge archived">Ожидание данных</span></div></div><div class="col-md-3"><div class="crm-card crm-kpi-card"><small class="text-muted">Пользователи онлайн</small><div id="adminKpiUsersValue" class="h4 crm-kpi-value" aria-label="Пользователи онлайн">Загрузка...</div><span id="adminKpiUsersBadge" class="crm-badge archived">Ожидание данных</span></div></div></div>
<div class="row g-3"><div class="col-lg-8"><div class="crm-card crm-section-card"><div class="crm-section-head"><div><h2 class="h6 mb-0">Последние логи</h2><div class="crm-section-note">Последние события аудита и системных действий.</div></div><a class="btn btn-sm btn-light" href="index.php?route=admin-logs">Открыть все</a></div><div id="adminLogsPreview"><div class="crm-metric-tile mb-2 text-muted">Загрузка событий аудита...</div></div></div></div><div class="col-lg-4"><div class="crm-side-stack"><div class="crm-card crm-section-card"><div class="crm-section-head"><div><h2 class="h6 mb-0">Справка</h2><div class="crm-section-note">Внутренние правила доступа, процессы и регламенты.</div></div></div><a class="btn crm-btn-secondary" href="index.php?route=docs">Открыть справку</a></div><div class="crm-card crm-section-card"><div class="crm-section-head"><div><h2 class="h6 mb-0">Интеграции</h2><div class="crm-section-note">Системные метрики и состояние служебных модулей.</div></div><a class="btn btn-sm btn-light" href="index.php?route=admin-statuses">Статусы задач</a></div><div id="adminIntegrationsPreview"><div class="crm-metric-tile mb-2 text-muted">Загрузка состояния интеграций...</div></div></div></div></div><div class="col-lg-12"><div class="crm-card crm-section-card"><div class="crm-section-head"><div><h2 class="h6 mb-0">Пользователи и роли</h2><div class="crm-section-note">Краткая сводка активных учетных записей и текущих ролей доступа.</div></div><div class="d-flex gap-2"><a class="btn btn-sm btn-light" href="index.php?route=admin-users">Пользователи</a><a class="btn btn-sm btn-light" href="index.php?route=admin-roles">Роли</a></div></div><div class="table-responsive crm-admin-overview-users-table"><table class="table crm-table mb-0"><thead><tr><th>Пользователь</th><th>Роль</th><th>Доступ</th></tr></thead><tbody id="adminUsersRolesPreviewBody"><tr><td colspan="3" class="text-muted">Загрузка пользователей...</td></tr></tbody></table></div></div></div></div>
</main></div></div>
