<?php declare(strict_types=1); ?>
<?php $title = 'TropaTT — Рабочее пространство'; ?>
<body data-page="dashboard" data-protected="1"><div class="crm-app"><aside class="crm-sidebar"><div class="crm-brand"><span class="crm-brand-mark"></span> TropaTT</div><nav class="nav flex-column crm-nav"></nav></aside>
<div class="crm-main-wrap"><header class="crm-topbar py-2"><div class="container-fluid"></div></header>
<main class="crm-content"><div class="crm-page-head"><div><h1 class="crm-page-title">Главная</h1><p class="crm-subtitle">Быстрый вход в задачи, проекты, календарь, Канбан и аналитику.</p></div><div class="d-flex gap-2"><a class="btn crm-btn-secondary" href="index.php?route=tasks">Задачи</a><a class="btn crm-btn-primary" href="index.php?route=dashboard">Открыть главную</a></div></div>
<div class="row g-3"><div class="col-lg-8"><div class="crm-card"><h2 class="h6">Быстрые действия</h2><div class="d-flex flex-wrap gap-2 mb-3"><button class="btn crm-btn-secondary" data-open-modal="createProjectModal">Создать проект</button><button class="btn crm-btn-secondary" data-open-modal="createTaskModal">Создать задачу</button><a class="btn crm-btn-secondary" href="index.php?route=tasks">Задачи</a><a class="btn crm-btn-secondary" href="index.php?route=docs">Справка</a></div></div></div><div class="col-lg-4"><div class="crm-card"><h2 class="h6">Сессия</h2><div class="crm-metric-tile mb-2">Пользователь: <span data-session-user>Гость</span></div><button class="btn crm-btn-secondary w-100" type="button" data-action="logout">Выйти</button></div></div></div>
</main></div></div>

<div class="modal fade" id="createProjectModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Создать проект</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button></div><form id="createProjectForm" novalidate><div class="modal-body"><div class="row g-3"><div class="col-md-8"><label class="form-label">Название проекта</label><input class="form-control" name="title" maxlength="255" placeholder="Запуск клиентского портала"></div><div class="col-md-4"><label class="form-label">Статус</label><select class="form-select" name="status"><option value="active">Активный</option><option value="new">К выполнению</option><option value="in_progress">В работе</option><option value="blocked">Блокирован</option><option value="done">Завершен</option></select></div><div class="col-md-6"><label class="form-label">Клиент</label><select class="form-select" name="client_public_id"><option value="">Без клиента</option></select></div><div class="col-md-6"><label class="form-label">Команда</label><select class="form-select" name="team_public_id"><option value="">Команда не назначена</option></select></div><div class="col-md-6"><label class="form-label">Менеджер проекта</label><select class="form-select" name="manager_user_public_id"><option value="">Без менеджера</option></select></div><div class="col-md-6"><label class="form-label">Приоритет</label><select class="form-select" name="priority"><option value="normal">Нормальный</option><option value="low">Низкий</option><option value="high">Высокий</option><option value="urgent">Срочный</option></select></div><div class="col-12"><label class="form-label">Описание</label><textarea class="form-control" name="description" rows="4" placeholder="Цели, контекст и основные ожидания по проекту"></textarea></div><div class="col-12"><div class="form-text" data-project-create-hint>Проект будет создан сразу в рабочей модели API, включая клиента, команду и менеджера.</div></div></div></div><div class="modal-footer"><button type="button" class="btn crm-btn-secondary" data-bs-dismiss="modal">Отмена</button><button type="submit" class="btn crm-btn-primary">Создать</button></div></form></div></div></div>
