<?php declare(strict_types=1); ?>
<?php $title = $t('counterparty_detail.title', 'TropaTT — Карточка контрагента'); ?>
<body data-page="counterparties" data-protected="1"><div class="crm-app">
<aside class="crm-sidebar"><div class="crm-brand"><span class="crm-brand-mark"></span> TropaTT</div><nav class="nav flex-column crm-nav"></nav></aside>
<div class="crm-main-wrap"><header class="crm-topbar py-2"><div class="container-fluid"></div></header>
<main class="crm-content crm-counterparty-detail-page"><div class="crm-page-head"><div><ol class="breadcrumb mb-1"><li class="breadcrumb-item"><a href="index.php?route=dashboard" data-i18n="page.dashboard"><?= htmlspecialchars($t('page.dashboard', 'Главная'), ENT_QUOTES, 'UTF-8') ?></a></li><li class="breadcrumb-item"><a href="index.php?route=counterparties" data-i18n="counterparties.page_title"><?= htmlspecialchars($t('counterparties.page_title', 'Контрагенты'), ENT_QUOTES, 'UTF-8') ?></a></li><li class="breadcrumb-item active" data-i18n="counterparty_detail.breadcrumb"><?= htmlspecialchars($t('counterparty_detail.breadcrumb', 'Карточка контрагента'), ENT_QUOTES, 'UTF-8') ?></li></ol><h1 class="crm-page-title" id="counterpartyDetailTitle" data-i18n="counterparty_detail.loading_title"><?= htmlspecialchars($t('counterparty_detail.loading_title', 'Загрузка контрагента...'), ENT_QUOTES, 'UTF-8') ?></h1><p class="crm-subtitle" id="counterpartyDetailSubtitle" data-i18n="counterparty_detail.loading_subtitle"><?= htmlspecialchars($t('counterparty_detail.loading_subtitle', 'Загрузка параметров контрагента...'), ENT_QUOTES, 'UTF-8') ?></p></div><div class="d-flex gap-2 flex-wrap"><button class="btn crm-btn-secondary" id="counterpartyDetailEditBtn" type="button" data-i18n="counterparty_detail.btn_edit"><?= htmlspecialchars($t('counterparty_detail.btn_edit', 'Редактировать контрагента'), ENT_QUOTES, 'UTF-8') ?></button><a class="btn crm-btn-secondary" href="index.php?route=counterparties" data-i18n="counterparty_detail.link_back"><?= htmlspecialchars($t('counterparty_detail.link_back', 'Назад к списку'), ENT_QUOTES, 'UTF-8') ?></a></div></div>

<div class="row g-3">
  <div class="col-lg-8">
    <div class="crm-card crm-section-card">
      <div class="crm-section-head"><div><h2 class="h6 mb-0" data-i18n="counterparty_detail.section_profile"><?= htmlspecialchars($t('counterparty_detail.section_profile', 'Профиль контрагента'), ENT_QUOTES, 'UTF-8') ?></h2><div class="crm-section-note" data-i18n="counterparty_detail.section_profile_note"><?= htmlspecialchars($t('counterparty_detail.section_profile_note', 'Основные реквизиты, контакты и юридическая информация.'), ENT_QUOTES, 'UTF-8') ?></div></div><button class="btn btn-sm crm-inline-icon-btn" id="counterpartyProfileEditBtn" type="button" aria-label="<?= htmlspecialchars($t('counterparty_detail.btn_edit_profile_aria', 'Редактировать профиль'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-aria-label="counterparty_detail.btn_edit_profile_aria"><span class="crm-icon" aria-hidden="true"><i class="fa-solid fa-pen"></i></span></button></div>
      <div id="counterpartyDetailProfile"><div class="text-muted" data-i18n="counterparty_detail.loading_profile"><?= htmlspecialchars($t('counterparty_detail.loading_profile', 'Загрузка карточки...'), ENT_QUOTES, 'UTF-8') ?></div></div>
    </div>
    <div class="crm-card crm-section-card mt-3">
      <div class="crm-section-head"><div><h2 class="h6 mb-0" data-i18n="counterparty_detail.section_contacts"><?= htmlspecialchars($t('counterparty_detail.section_contacts', 'Контакты'), ENT_QUOTES, 'UTF-8') ?></h2><div class="crm-section-note" data-i18n="counterparty_detail.section_contacts_note"><?= htmlspecialchars($t('counterparty_detail.section_contacts_note', 'Связанные контакты контрагента.'), ENT_QUOTES, 'UTF-8') ?></div></div><button class="btn btn-sm crm-btn-primary" id="counterpartyContactAddBtn" type="button" data-i18n="counterparty_detail.btn_add_contact"><?= htmlspecialchars($t('counterparty_detail.btn_add_contact', 'Добавить контакт'), ENT_QUOTES, 'UTF-8') ?></button></div>
      <div class="table-responsive"><table class="table crm-table mb-0"><thead><tr><th data-i18n="counterparty_detail.th_full_name"><?= htmlspecialchars($t('counterparty_detail.th_full_name', 'ФИО'), ENT_QUOTES, 'UTF-8') ?></th><th data-i18n="counterparty_detail.th_role"><?= htmlspecialchars($t('counterparty_detail.th_role', 'Роль'), ENT_QUOTES, 'UTF-8') ?></th><th data-i18n="counterparty_detail.th_email"><?= htmlspecialchars($t('counterparty_detail.th_email', 'Email'), ENT_QUOTES, 'UTF-8') ?></th><th data-i18n="counterparty_detail.th_phone"><?= htmlspecialchars($t('counterparty_detail.th_phone', 'Телефон'), ENT_QUOTES, 'UTF-8') ?></th><th style="width:100px"></th></tr></thead><tbody id="counterpartyDetailContactsBody"><tr><td colspan="5" class="text-muted" data-i18n="counterparty_detail.loading_contacts"><?= htmlspecialchars($t('counterparty_detail.loading_contacts', 'Загрузка контактов...'), ENT_QUOTES, 'UTF-8') ?></td></tr></tbody></table></div>
    </div>
    <div class="crm-card crm-section-card mt-3">
      <div class="crm-section-head"><div><h2 class="h6 mb-0" data-i18n="counterparty_detail.section_tasks"><?= htmlspecialchars($t('counterparty_detail.section_tasks', 'Связанные задачи'), ENT_QUOTES, 'UTF-8') ?></h2><div class="crm-section-note" data-i18n="counterparty_detail.section_tasks_note"><?= htmlspecialchars($t('counterparty_detail.section_tasks_note', 'Последние задачи по этому контрагенту.'), ENT_QUOTES, 'UTF-8') ?></div></div></div>
      <div class="table-responsive"><table class="table crm-table mb-0"><thead><tr><th data-i18n="counterparty_detail.th_task"><?= htmlspecialchars($t('counterparty_detail.th_task', 'Задача'), ENT_QUOTES, 'UTF-8') ?></th><th data-i18n="counterparty_detail.th_status"><?= htmlspecialchars($t('counterparty_detail.th_status', 'Статус'), ENT_QUOTES, 'UTF-8') ?></th><th data-i18n="counterparty_detail.th_project"><?= htmlspecialchars($t('counterparty_detail.th_project', 'Проект'), ENT_QUOTES, 'UTF-8') ?></th><th data-i18n="counterparty_detail.th_updated"><?= htmlspecialchars($t('counterparty_detail.th_updated', 'Обновлена'), ENT_QUOTES, 'UTF-8') ?></th></tr></thead><tbody id="counterpartyDetailTasksBody"><tr><td colspan="4" class="text-muted" data-i18n="counterparty_detail.loading_tasks"><?= htmlspecialchars($t('counterparty_detail.loading_tasks', 'Загрузка задач...'), ENT_QUOTES, 'UTF-8') ?></td></tr></tbody></table></div>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="crm-card crm-section-card mb-3">
      <div class="crm-section-head"><div><h2 class="h6 mb-0" data-i18n="counterparty_detail.section_summary"><?= htmlspecialchars($t('counterparty_detail.section_summary', 'Сводка'), ENT_QUOTES, 'UTF-8') ?></h2><div class="crm-section-note" data-i18n="counterparty_detail.section_summary_note"><?= htmlspecialchars($t('counterparty_detail.section_summary_note', 'Быстрые метрики по карточке контрагента.'), ENT_QUOTES, 'UTF-8') ?></div></div></div>
      <div id="counterpartyDetailSummary"><div class="text-muted" data-i18n="page.loading"><?= htmlspecialchars($t('page.loading', 'Загрузка...'), ENT_QUOTES, 'UTF-8') ?></div></div>
    </div>
    <div class="crm-card crm-section-card mt-3">
      <div class="crm-section-head"><div><h2 class="h6 mb-0" data-i18n="counterparty_detail.section_requisites"><?= htmlspecialchars($t('counterparty_detail.section_requisites', 'Реквизиты'), ENT_QUOTES, 'UTF-8') ?></h2><div class="crm-section-note" data-i18n="counterparty_detail.section_requisites_note"><?= htmlspecialchars($t('counterparty_detail.section_requisites_note', 'Юридические и банковские данные.'), ENT_QUOTES, 'UTF-8') ?></div></div><button class="btn btn-sm crm-inline-icon-btn" id="counterpartyRequisitesEditBtn" type="button" aria-label="<?= htmlspecialchars($t('counterparty_detail.btn_edit_requisites_aria', 'Редактировать реквизиты'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-aria-label="counterparty_detail.btn_edit_requisites_aria"><span class="crm-icon" aria-hidden="true"><i class="fa-solid fa-pen"></i></span></button></div>
      <div id="counterpartyDetailRequisites"><div class="text-muted" data-i18n="page.loading"><?= htmlspecialchars($t('page.loading', 'Загрузка...'), ENT_QUOTES, 'UTF-8') ?></div></div>
    </div>
    <div class="crm-card crm-section-card mt-3">
      <div class="crm-section-head"><div><h2 class="h6 mb-0" data-i18n="counterparty_detail.section_extra"><?= htmlspecialchars($t('counterparty_detail.section_extra', 'Дополнительные поля'), ENT_QUOTES, 'UTF-8') ?></h2><div class="crm-section-note" data-i18n="counterparty_detail.section_extra_note"><?= htmlspecialchars($t('counterparty_detail.section_extra_note', 'Кастомные поля контрагента.'), ENT_QUOTES, 'UTF-8') ?></div></div><button class="btn btn-sm crm-inline-icon-btn" id="counterpartyExtraEditBtn" type="button" aria-label="<?= htmlspecialchars($t('counterparty_detail.btn_edit_extra_aria', 'Редактировать дополнительные поля'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-aria-label="counterparty_detail.btn_edit_extra_aria"><span class="crm-icon" aria-hidden="true"><i class="fa-solid fa-pen"></i></span></button></div>
      <div id="counterpartyDetailExtra"><div class="text-muted" data-i18n="counterparty_detail.extra_empty"><?= htmlspecialchars($t('counterparty_detail.extra_empty', 'Нет дополнительных атрибутов'), ENT_QUOTES, 'UTF-8') ?></div></div>
    </div>
  </div>
</div>
</main></div></div>

<div class="modal fade" id="counterpartyDetailEditModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-xl modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" data-i18n="counterparty_detail.edit_modal_title"><?= htmlspecialchars($t('counterparty_detail.edit_modal_title', 'Редактировать контрагента'), ENT_QUOTES, 'UTF-8') ?></h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="<?= htmlspecialchars($t('page.close', 'Закрыть'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-aria-label="page.close"></button></div><form id="counterpartyDetailEditForm" novalidate><div class="modal-body"><input type="hidden" name="public_id"><div class="row g-3">
  <div class="col-12 d-none" data-form-error-summary></div>
  <div class="col-md-4"><label class="form-label" data-i18n="counterparties.field_type"><?= htmlspecialchars($t('counterparties.field_type', 'Тип контрагента'), ENT_QUOTES, 'UTF-8') ?></label><select class="form-select" name="counterparty_type" data-counterparty-type-input><option value="organization" data-i18n="counterparties.type_organization"><?= htmlspecialchars($t('counterparties.type_organization', 'Организация'), ENT_QUOTES, 'UTF-8') ?></option><option value="individual" data-i18n="counterparties.type_individual"><?= htmlspecialchars($t('counterparties.type_individual', 'Физлицо'), ENT_QUOTES, 'UTF-8') ?></option><option value="sole_proprietor" data-i18n="counterparties.type_sole_proprietor"><?= htmlspecialchars($t('counterparties.type_sole_proprietor', 'ИП'), ENT_QUOTES, 'UTF-8') ?></option><option value="legal_entity" data-i18n="counterparties.type_legal_entity"><?= htmlspecialchars($t('counterparties.type_legal_entity', 'Юрлицо'), ENT_QUOTES, 'UTF-8') ?></option></select></div>
  <div class="col-md-8"><label class="form-label" data-i18n="counterparties.field_title"><?= htmlspecialchars($t('counterparties.field_title', 'Название'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="title" maxlength="255" required></div>
  <div class="col-md-6" data-counterparty-type-group="sole_proprietor,legal_entity"><label class="form-label" data-i18n="counterparties.field_legal_name"><?= htmlspecialchars($t('counterparties.field_legal_name', 'Юридическое наименование / ФИО ИП'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="legal_name" maxlength="255"></div>
  <div class="col-md-4" data-counterparty-type-group="sole_proprietor,legal_entity"><label class="form-label" data-i18n="counterparties.field_inn"><?= htmlspecialchars($t('counterparties.field_inn', 'ИНН'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="tax_inn" maxlength="12"></div>
  <div class="col-md-4" data-counterparty-type-group="legal_entity"><label class="form-label" data-i18n="counterparties.field_kpp"><?= htmlspecialchars($t('counterparties.field_kpp', 'КПП'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="tax_kpp" maxlength="9"></div>
  <div class="col-md-4" data-counterparty-type-group="legal_entity"><label class="form-label" data-i18n="counterparties.field_ogrn"><?= htmlspecialchars($t('counterparties.field_ogrn', 'ОГРН'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="tax_ogrn" maxlength="13"></div>
  <div class="col-md-4" data-counterparty-type-group="sole_proprietor"><label class="form-label" data-i18n="counterparties.field_ogrnip"><?= htmlspecialchars($t('counterparties.field_ogrnip', 'ОГРНИП'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="tax_ogrnip" maxlength="15"></div>
  <div class="col-md-4"><label class="form-label" data-i18n="counterparties.field_email"><?= htmlspecialchars($t('counterparties.field_email', 'Email'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" type="email" name="email" maxlength="190"></div>
  <div class="col-md-4"><label class="form-label" data-i18n="counterparties.field_phone"><?= htmlspecialchars($t('counterparties.field_phone', 'Телефон'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="phone" maxlength="64"></div>
  <div class="col-md-4"><label class="form-label" data-i18n="counterparties.field_website"><?= htmlspecialchars($t('counterparties.field_website', 'Сайт'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="website" maxlength="2048"></div>
  <div class="col-md-4"><label class="form-label" data-i18n="counterparties.field_messenger"><?= htmlspecialchars($t('counterparties.field_messenger', 'Мессенджер'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="messenger" maxlength="190"></div>
  <div class="col-md-4" data-counterparty-type-group="sole_proprietor,legal_entity"><label class="form-label" data-i18n="counterparties.field_bank_account"><?= htmlspecialchars($t('counterparties.field_bank_account', 'Расчетный счет'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="bank_account" maxlength="34"></div>
  <div class="col-md-4" data-counterparty-type-group="sole_proprietor,legal_entity"><label class="form-label" data-i18n="counterparties.field_bik"><?= htmlspecialchars($t('counterparties.field_bik', 'БИК'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="bank_bik" maxlength="9"></div>
  <div class="col-md-4" data-counterparty-type-group="sole_proprietor,legal_entity"><label class="form-label" data-i18n="counterparties.field_corr_account"><?= htmlspecialchars($t('counterparties.field_corr_account', 'Корр. счет'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="bank_corr_account" maxlength="34"></div>
  <div class="col-md-8" data-counterparty-type-group="sole_proprietor,legal_entity"><label class="form-label" data-i18n="counterparties.field_bank_name"><?= htmlspecialchars($t('counterparties.field_bank_name', 'Банк'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="bank_name" maxlength="255"></div>
  <div class="col-md-4"><label class="form-label" data-i18n="counterparties.field_status"><?= htmlspecialchars($t('counterparties.field_status', 'Статус'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="status" maxlength="64"></div>
  <div class="col-md-6"><label class="form-label" data-i18n="counterparties.field_address_legal"><?= htmlspecialchars($t('counterparties.field_address_legal', 'Юридический адрес'), ENT_QUOTES, 'UTF-8') ?></label><textarea class="form-control" name="address_legal" rows="2"></textarea></div>
  <div class="col-md-6"><label class="form-label" data-i18n="counterparties.field_address_postal"><?= htmlspecialchars($t('counterparties.field_address_postal', 'Почтовый адрес'), ENT_QUOTES, 'UTF-8') ?></label><textarea class="form-control" name="address_postal" rows="2"></textarea></div>
  <div class="col-12"><label class="form-label" data-i18n="counterparties.field_notes"><?= htmlspecialchars($t('counterparties.field_notes', 'Комментарий'), ENT_QUOTES, 'UTF-8') ?></label><textarea class="form-control" name="notes" rows="2"></textarea></div>
</div></div><div class="modal-footer"><button class="btn crm-btn-secondary" type="button" data-bs-dismiss="modal" data-i18n="page.cancel"><?= htmlspecialchars($t('page.cancel', 'Отмена'), ENT_QUOTES, 'UTF-8') ?></button><button class="btn crm-btn-primary" type="submit" data-i18n="page.save"><?= htmlspecialchars($t('page.save', 'Сохранить'), ENT_QUOTES, 'UTF-8') ?></button></div></form></div></div></div>

<div class="modal fade" id="counterpartyProfileEditModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" data-i18n="counterparty_detail.profile_edit_modal_title"><?= htmlspecialchars($t('counterparty_detail.profile_edit_modal_title', 'Редактировать профиль'), ENT_QUOTES, 'UTF-8') ?></h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="<?= htmlspecialchars($t('page.close', 'Закрыть'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-aria-label="page.close"></button></div><form id="counterpartyProfileEditForm" novalidate><div class="modal-body"><input type="hidden" name="public_id"><div class="row g-3">
  <div class="col-12 d-none" data-form-error-summary></div>
  <div class="col-md-4"><label class="form-label" data-i18n="counterparties.field_type"><?= htmlspecialchars($t('counterparties.field_type', 'Тип контрагента'), ENT_QUOTES, 'UTF-8') ?></label><select class="form-select" name="counterparty_type" data-profile-type-input><option value="organization" data-i18n="counterparties.type_organization"><?= htmlspecialchars($t('counterparties.type_organization', 'Организация'), ENT_QUOTES, 'UTF-8') ?></option><option value="individual" data-i18n="counterparties.type_individual"><?= htmlspecialchars($t('counterparties.type_individual', 'Физлицо'), ENT_QUOTES, 'UTF-8') ?></option><option value="sole_proprietor" data-i18n="counterparties.type_sole_proprietor"><?= htmlspecialchars($t('counterparties.type_sole_proprietor', 'ИП'), ENT_QUOTES, 'UTF-8') ?></option><option value="legal_entity" data-i18n="counterparties.type_legal_entity"><?= htmlspecialchars($t('counterparties.type_legal_entity', 'Юрлицо'), ENT_QUOTES, 'UTF-8') ?></option></select></div>
  <div class="col-md-8"><label class="form-label" data-i18n="counterparties.field_title"><?= htmlspecialchars($t('counterparties.field_title', 'Название'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="title" maxlength="255" required></div>
  <div class="col-md-4"><label class="form-label" data-i18n="counterparties.field_email"><?= htmlspecialchars($t('counterparties.field_email', 'Email'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" type="email" name="email" maxlength="190"></div>
  <div class="col-md-4"><label class="form-label" data-i18n="counterparties.field_phone"><?= htmlspecialchars($t('counterparties.field_phone', 'Телефон'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="phone" maxlength="64"></div>
  <div class="col-md-4"><label class="form-label" data-i18n="counterparties.field_website"><?= htmlspecialchars($t('counterparties.field_website', 'Сайт'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="website" maxlength="2048"></div>
  <div class="col-md-4"><label class="form-label" data-i18n="counterparties.field_messenger"><?= htmlspecialchars($t('counterparties.field_messenger', 'Мессенджер'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="messenger" maxlength="190"></div>
  <div class="col-md-4"><label class="form-label" data-i18n="counterparties.field_status"><?= htmlspecialchars($t('counterparties.field_status', 'Статус'), ENT_QUOTES, 'UTF-8') ?></label><select class="form-select" name="status"><option value="active" data-i18n="counterparties.status_active"><?= htmlspecialchars($t('counterparties.status_active', 'Активен'), ENT_QUOTES, 'UTF-8') ?></option><option value="inactive" data-i18n="counterparties.status_inactive"><?= htmlspecialchars($t('counterparties.status_inactive', 'Неактивен'), ENT_QUOTES, 'UTF-8') ?></option><option value="blocked" data-i18n="counterparties.status_blocked"><?= htmlspecialchars($t('counterparties.status_blocked', 'Заблокирован'), ENT_QUOTES, 'UTF-8') ?></option></select></div>
  <div class="col-12"><label class="form-label" data-i18n="counterparties.field_notes"><?= htmlspecialchars($t('counterparties.field_notes', 'Комментарий'), ENT_QUOTES, 'UTF-8') ?></label><textarea class="form-control" name="notes" rows="2"></textarea></div>
</div></div><div class="modal-footer"><button class="btn crm-btn-secondary" type="button" data-bs-dismiss="modal" data-i18n="page.cancel"><?= htmlspecialchars($t('page.cancel', 'Отмена'), ENT_QUOTES, 'UTF-8') ?></button><button class="btn crm-btn-primary" type="submit" data-i18n="page.save"><?= htmlspecialchars($t('page.save', 'Сохранить'), ENT_QUOTES, 'UTF-8') ?></button></div></form></div></div></div>

<div class="modal fade" id="counterpartyContactModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="counterpartyContactModalTitle" data-i18n="counterparty_detail.contact_modal_title"><?= htmlspecialchars($t('counterparty_detail.contact_modal_title', 'Добавить контакт'), ENT_QUOTES, 'UTF-8') ?></h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="<?= htmlspecialchars($t('page.close', 'Закрыть'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-aria-label="page.close"></button></div><form id="counterpartyContactForm" novalidate><div class="modal-body"><input type="hidden" name="public_id"><input type="hidden" name="counterparty_public_id"><div class="row g-3">
  <div class="col-12 d-none" data-form-error-summary></div>
  <div class="col-12"><label class="form-label" data-i18n="counterparty_detail.contact_field_full_name"><?= htmlspecialchars($t('counterparty_detail.contact_field_full_name', 'ФИО'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="full_name" maxlength="255" required></div>
  <div class="col-md-6"><label class="form-label" data-i18n="counterparty_detail.contact_field_role"><?= htmlspecialchars($t('counterparty_detail.contact_field_role', 'Роль'), ENT_QUOTES, 'UTF-8') ?></label><select class="form-select" name="role"><option value="decision_maker" data-i18n="contacts.role_decision_maker"><?= htmlspecialchars($t('contacts.role_decision_maker', 'ЛПР'), ENT_QUOTES, 'UTF-8') ?></option><option value="influencer" data-i18n="contacts.role_influencer"><?= htmlspecialchars($t('contacts.role_influencer', 'Влияющий'), ENT_QUOTES, 'UTF-8') ?></option><option value="user" data-i18n="contacts.role_user"><?= htmlspecialchars($t('contacts.role_user', 'Пользователь'), ENT_QUOTES, 'UTF-8') ?></option><option value="technical" data-i18n="contacts.role_technical"><?= htmlspecialchars($t('contacts.role_technical', 'Технический'), ENT_QUOTES, 'UTF-8') ?></option><option value="contact" data-i18n="contacts.role_contact"><?= htmlspecialchars($t('contacts.role_contact', 'Контакт'), ENT_QUOTES, 'UTF-8') ?></option></select></div>
  <div class="col-md-6"><label class="form-label" data-i18n="counterparty_detail.contact_field_email"><?= htmlspecialchars($t('counterparty_detail.contact_field_email', 'Email'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" type="email" name="email" maxlength="190"></div>
  <div class="col-md-6"><label class="form-label" data-i18n="counterparty_detail.contact_field_phone"><?= htmlspecialchars($t('counterparty_detail.contact_field_phone', 'Телефон'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="phone" maxlength="64"></div>
</div></div><div class="modal-footer"><button class="btn crm-btn-secondary" type="button" data-bs-dismiss="modal" data-i18n="page.cancel"><?= htmlspecialchars($t('page.cancel', 'Отмена'), ENT_QUOTES, 'UTF-8') ?></button><button class="btn crm-btn-primary" type="submit" data-i18n="page.save"><?= htmlspecialchars($t('page.save', 'Сохранить'), ENT_QUOTES, 'UTF-8') ?></button></div></form></div></div></div>

<div class="modal fade" id="counterpartyRequisitesEditModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" data-i18n="counterparty_detail.requisites_edit_modal_title"><?= htmlspecialchars($t('counterparty_detail.requisites_edit_modal_title', 'Редактировать реквизиты'), ENT_QUOTES, 'UTF-8') ?></h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="<?= htmlspecialchars($t('page.close', 'Закрыть'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-aria-label="page.close"></button></div><form id="counterpartyRequisitesEditForm" novalidate><div class="modal-body"><input type="hidden" name="public_id"><div class="row g-3">
  <div class="col-12 d-none" data-form-error-summary></div>
  <div class="col-md-4"><label class="form-label" data-i18n="counterparty_detail.requisites_field_legal_name"><?= htmlspecialchars($t('counterparty_detail.requisites_field_legal_name', 'Юридическое наименование'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="legal_name" maxlength="255"></div>
  <div class="col-md-4 position-relative" data-ru-field><label class="form-label" data-i18n="counterparty_detail.requisites_field_inn"><?= htmlspecialchars($t('counterparty_detail.requisites_field_inn', 'ИНН'), ENT_QUOTES, 'UTF-8') ?> <small class="text-muted" data-i18n="counterparty_detail.requisites_inn_hint"><?= htmlspecialchars($t('counterparty_detail.requisites_inn_hint', '(введите для поиска)'), ENT_QUOTES, 'UTF-8') ?></small></label><input class="form-control" name="tax_inn" maxlength="12" id="requisitesInnInput" autocomplete="off"><div id="dadataSuggestions" class="list-group position-absolute w-100" style="z-index:1050;display:none;"></div></div>
  <div class="col-md-4" data-ru-field><label class="form-label" data-i18n="counterparty_detail.requisites_field_kpp"><?= htmlspecialchars($t('counterparty_detail.requisites_field_kpp', 'КПП'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="tax_kpp" maxlength="9"></div>
  <div class="col-md-4" data-intl-field style="display:none"><label class="form-label" data-i18n="counterparty_detail.requisites_field_tax_id"><?= htmlspecialchars($t('counterparty_detail.requisites_field_tax_id', 'Tax ID / VAT Number'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="tax_inn" maxlength="32"></div>
  <div class="col-md-4" data-intl-field style="display:none"><label class="form-label" data-i18n="counterparty_detail.requisites_field_company_reg"><?= htmlspecialchars($t('counterparty_detail.requisites_field_company_reg', 'Company Registration No.'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="tax_kpp" maxlength="32"></div>
  <div class="col-md-4" data-ru-field data-req-type-group="organization,legal_entity"><label class="form-label" data-i18n="counterparty_detail.requisites_field_ogrn"><?= htmlspecialchars($t('counterparty_detail.requisites_field_ogrn', 'ОГРН'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="tax_ogrn" maxlength="13"></div>
  <div class="col-md-4" data-ru-field data-req-type-group="sole_proprietor"><label class="form-label" data-i18n="counterparty_detail.requisites_field_ogrnip"><?= htmlspecialchars($t('counterparty_detail.requisites_field_ogrnip', 'ОГРНИП'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="tax_ogrnip" maxlength="15"></div>
  <div class="col-md-4" data-intl-field style="display:none"><label class="form-label" data-i18n="counterparty_detail.requisites_field_reg_number"><?= htmlspecialchars($t('counterparty_detail.requisites_field_reg_number', 'Registration Number'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="tax_ogrn" maxlength="32"></div>
  <div class="col-md-4" data-intl-field style="display:none"><label class="form-label" data-i18n="counterparty_detail.requisites_field_tax_reg"><?= htmlspecialchars($t('counterparty_detail.requisites_field_tax_reg', 'Tax Registration No.'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="tax_ogrnip" maxlength="32"></div>
  <div class="col-md-4"><label class="form-label" data-i18n="counterparty_detail.requisites_field_bank_account"><?= htmlspecialchars($t('counterparty_detail.requisites_field_bank_account', 'Расчетный счет / Account No.'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="bank_account" maxlength="34"></div>
  <div class="col-md-4"><label class="form-label" data-i18n="counterparty_detail.requisites_field_bik_swift"><?= htmlspecialchars($t('counterparty_detail.requisites_field_bik_swift', 'БИК / SWIFT / BIC'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="bank_bik" maxlength="16"></div>
  <div class="col-md-4"><label class="form-label" data-i18n="counterparty_detail.requisites_field_corr_iban"><?= htmlspecialchars($t('counterparty_detail.requisites_field_corr_iban', 'Корр. счет / IBAN'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="bank_corr_account" maxlength="34"></div>
  <div class="col-md-8"><label class="form-label" data-i18n="counterparty_detail.requisites_field_bank_name"><?= htmlspecialchars($t('counterparty_detail.requisites_field_bank_name', 'Банк'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="bank_name" maxlength="255"></div>
  <div class="col-md-6"><label class="form-label" data-i18n="counterparty_detail.requisites_field_address_legal"><?= htmlspecialchars($t('counterparty_detail.requisites_field_address_legal', 'Юридический адрес'), ENT_QUOTES, 'UTF-8') ?></label><textarea class="form-control" name="address_legal" rows="2"></textarea></div>
  <div class="col-md-6"><label class="form-label" data-i18n="counterparty_detail.requisites_field_address_postal"><?= htmlspecialchars($t('counterparty_detail.requisites_field_address_postal', 'Почтовый адрес'), ENT_QUOTES, 'UTF-8') ?></label><textarea class="form-control" name="address_postal" rows="2"></textarea></div>
</div></div><div class="modal-footer"><button class="btn crm-btn-secondary" type="button" data-bs-dismiss="modal" data-i18n="page.cancel"><?= htmlspecialchars($t('page.cancel', 'Отмена'), ENT_QUOTES, 'UTF-8') ?></button><button class="btn crm-btn-primary" type="submit" data-i18n="page.save"><?= htmlspecialchars($t('page.save', 'Сохранить'), ENT_QUOTES, 'UTF-8') ?></button></div></form></div></div></div>

<div class="modal fade" id="counterpartyExtraEditModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" data-i18n="counterparty_detail.extra_edit_modal_title"><?= htmlspecialchars($t('counterparty_detail.extra_edit_modal_title', 'Редактировать дополнительные поля'), ENT_QUOTES, 'UTF-8') ?></h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="<?= htmlspecialchars($t('page.close', 'Закрыть'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-aria-label="page.close"></button></div><form id="counterpartyExtraEditForm" novalidate><div class="modal-body"><input type="hidden" name="public_id"><div class="row g-3">
  <div class="col-12 d-none" data-form-error-summary></div>
  <div id="counterpartyExtraFieldsContainer"><div class="text-muted" data-i18n="counterparty_detail.extra_fields_empty"><?= htmlspecialchars($t('counterparty_detail.extra_fields_empty', 'Нет дополнительных полей.'), ENT_QUOTES, 'UTF-8') ?></div></div>
  <div class="col-12 mt-3"><button type="button" class="btn btn-sm crm-btn-secondary" id="addExtraFieldBtn" data-i18n="counterparty_detail.btn_add_field"><?= htmlspecialchars($t('counterparty_detail.btn_add_field', 'Добавить поле'), ENT_QUOTES, 'UTF-8') ?></button></div>
</div></div><div class="modal-footer"><button class="btn crm-btn-secondary" type="button" data-bs-dismiss="modal" data-i18n="page.cancel"><?= htmlspecialchars($t('page.cancel', 'Отмена'), ENT_QUOTES, 'UTF-8') ?></button><button class="btn crm-btn-primary" type="submit" data-i18n="page.save"><?= htmlspecialchars($t('page.save', 'Сохранить'), ENT_QUOTES, 'UTF-8') ?></button></div></form></div></div></div>
</body>
