<?php declare(strict_types=1); ?>
<?php $title = 'TropaTT — Профиль'; ?>
<body data-page="profile" data-protected="1"><div class="crm-app"><aside class="crm-sidebar"><div class="crm-brand"><span class="crm-brand-mark"></span> TropaTT</div><nav class="nav flex-column crm-nav"></nav></aside>
<div class="crm-main-wrap"><header class="crm-topbar py-2"><div class="container-fluid"></div></header>
<main class="crm-content crm-profile-page"><div class="crm-page-head"><div><h1 class="crm-page-title">Профиль</h1><p class="crm-subtitle">Личные данные, настройки интерфейса, уведомления и безопасность.</p></div><div class="crm-page-actions"><button id="profileSaveBtn" class="btn crm-btn-primary" type="button" disabled>Сохранить изменения</button></div></div>
<div class="crm-card crm-section-card mb-3"><div class="d-flex align-items-center gap-3"><div class="crm-avatar" style="width:64px;height:64px;font-size:1.5rem;display:inline-flex;align-items:center;justify-content:center;border-radius:50%;background:var(--color-primary-50);color:var(--color-primary-700);font-weight:700;flex-shrink:0" aria-hidden="true">ТА</div><div><div class="fw-bold" id="profileNameDisplay">Тестовый администратор</div><div class="text-muted small" id="profileRoleDisplay">test_admin</div><div class="text-muted small" id="profileLastLoginDisplay">Последний вход: —</div></div></div></div>
<div class="crm-profile-grid">
  <div class="crm-card crm-section-card"><div class="crm-section-head"><div><h2 class="h6 mb-0">Личные данные</h2><div class="crm-section-note">Основная информация профиля и контактные данные пользователя.</div></div></div><label class="form-label" for="profileFullNameInput">ФИО</label><input id="profileFullNameInput" class="form-control mb-2" value="" placeholder="Загрузка профиля..."><label class="form-label" for="profileEmailInput">Email</label><input id="profileEmailInput" class="form-control mb-2" value="" placeholder="Загрузка email..."><label class="form-label" for="profileTitleInput">Должность</label><input id="profileTitleInput" class="form-control" value="" placeholder="Загрузка должности..."></div>
  <div class="crm-card crm-section-card"><div class="crm-section-head"><div><h2 class="h6 mb-0">Настройки интерфейса</h2><div class="crm-section-note">Стартовая страница и комфорт работы с таблицами.</div></div></div><label class="form-label" for="profileStartPageSelect">Стартовая страница</label><select id="profileStartPageSelect" class="form-select mb-2"><option value="dashboard">Главная</option><option value="tasks">Задачи</option><option value="projects">Проекты</option><option value="kanban">Канбан</option></select><label class="form-label" for="profileTableDensitySelect">Плотность таблиц</label><select id="profileTableDensitySelect" class="form-select"><option value="compact">Компактная</option><option value="normal">Обычная</option></select></div>
  <div class="crm-card crm-section-card"><div class="crm-section-head"><div><h2 class="h6 mb-0">Уведомления</h2><div class="crm-section-note">Каналы оповещений и частота служебных уведомлений.</div></div></div><div class="crm-settings-row"><div><span class="fw-medium">Email по критичным задачам</span><div class="crm-section-note">Мгновенные уведомления о просроченных и блокированных задачах</div></div><div class="form-check form-switch mb-0"><input class="form-check-input" type="checkbox" id="profileNotifyEmailCritical"><label class="form-check-label visually-hidden" for="profileNotifyEmailCritical">Email по критичным задачам</label></div></div><div class="crm-settings-row"><div><span class="fw-medium">Push по комментариям</span><div class="crm-section-note">Новые комментарии к задачам и проектам клиента</div></div><div class="form-check form-switch mb-0"><input class="form-check-input" type="checkbox" id="profileNotifyPushComments"><label class="form-check-label visually-hidden" for="profileNotifyPushComments">Push по комментариям</label></div></div><div class="crm-settings-row"><div><span class="fw-medium">Еженедельный отчет</span><div class="crm-section-note">Сводка по задачам, проектам и загрузке за неделю</div></div><div class="form-check form-switch mb-0"><input class="form-check-input" type="checkbox" id="profileNotifyWeeklyReport"><label class="form-check-label visually-hidden" for="profileNotifyWeeklyReport">Еженедельный отчет</label></div></div></div>
  <div class="crm-card crm-section-card"><div class="crm-section-head"><div><h2 class="h6 mb-0">Безопасность и сессии</h2><div class="crm-section-note">Последний вход, активные устройства и действия по защите аккаунта.</div></div></div><div id="profileLastLoginTile" class="crm-info-panel mb-2">Последний вход: загрузка...</div><div id="profileSessionsTile" class="crm-info-panel mb-2">Активные устройства: загрузка...</div><div id="profileTwoFactorTile" class="crm-info-panel mb-2">2FA: загрузка...</div><div id="profileSecurityLogTile" class="crm-info-panel mb-2">Журнал безопасности: загрузка...</div><div class="d-flex gap-2 flex-wrap mb-3"><button id="profileChangePasswordBtn" class="btn crm-btn-secondary" type="button">Сменить пароль</button><button id="profileToggleTwoFactorBtn" class="btn crm-btn-secondary" type="button">Управлять 2FA</button></div><div class="crm-danger-zone"><div class="crm-danger-zone-title">Опасная зона</div><div class="crm-settings-row"><div><span class="fw-medium">Завершить все сессии</span><div class="crm-section-note">Выход из всех устройств кроме текущего</div></div><button id="profileRevokeSessionsBtn" class="btn crm-btn-danger-soft crm-btn-compact" type="button" data-confirm-action>Завершить</button></div></div></div>
</div>
</main></div></div>
<div class="modal fade" id="profilePasswordModal" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <form class="modal-content" id="profilePasswordForm">
      <div class="modal-header"><h2 class="h6 mb-0">Сменить пароль</h2><button class="btn-close" type="button" data-profile-modal-close aria-label="Закрыть"></button></div>
      <div class="modal-body">
        <label class="form-label" for="profileCurrentPasswordInput">Текущий пароль</label><input id="profileCurrentPasswordInput" class="form-control mb-2" type="password" autocomplete="current-password" required>
        <label class="form-label" for="profileNewPasswordInput">Новый пароль</label><input id="profileNewPasswordInput" class="form-control mb-2" type="password" autocomplete="new-password" minlength="8" required>
        <label class="form-label" for="profileRepeatPasswordInput">Повторите новый пароль</label><input id="profileRepeatPasswordInput" class="form-control" type="password" autocomplete="new-password" minlength="8" required>
        <div class="form-text">Минимум 8 символов. Пароль не отображается и не сохраняется в браузере.</div><div class="small text-danger mt-2 d-none" id="profilePasswordError"></div>
      </div>
      <div class="modal-footer"><button class="btn crm-btn-secondary" type="button" data-profile-modal-close>Отмена</button><button class="btn crm-btn-primary" type="submit" id="profilePasswordSubmitBtn">Сменить пароль</button></div>
    </form>
  </div>
</div>
<div class="modal fade" id="profileTwoFactorModal" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <form class="modal-content" id="profileTwoFactorForm">
      <div class="modal-header"><h2 class="h6 mb-0" id="profileTwoFactorModalTitle">Управлять 2FA</h2><button class="btn-close" type="button" data-profile-modal-close aria-label="Закрыть"></button></div>
      <div class="modal-body">
        <p class="text-muted small" id="profileTwoFactorModalNote">Подтвердите действие текущим паролем.</p>
        <label class="form-label" for="profileTwoFactorPasswordInput">Текущий пароль</label><input id="profileTwoFactorPasswordInput" class="form-control" type="password" autocomplete="current-password" required>
        <div class="small text-danger mt-2 d-none" id="profileTwoFactorError"></div><div class="crm-soft-panel mt-3 d-none" id="profileTwoFactorResult" aria-live="polite"></div>
      </div>
      <div class="modal-footer"><button class="btn crm-btn-secondary" type="button" data-profile-modal-close>Закрыть</button><button class="btn crm-btn-primary" type="submit" id="profileTwoFactorSubmitBtn">Продолжить</button></div>
    </form>
  </div>
</div>
<script>(function(){var btn=document.getElementById('profileSaveBtn');if(!btn)return;var inputs=document.querySelectorAll('.crm-profile-page input:not([type=checkbox]),.crm-profile-page select,.crm-profile-page textarea');var checks=document.querySelectorAll('.crm-profile-page input[type=checkbox]');function markDirty(){if(!btn.classList.contains('is-dirty')){btn.classList.add('is-dirty');btn.disabled=false}}inputs.forEach(function(el){el.addEventListener('input',markDirty);el.addEventListener('change',markDirty)});checks.forEach(function(el){el.addEventListener('change',markDirty)});var origSave=btn.onclick;btn.addEventListener('click',function(){if(btn.disabled)return;setTimeout(function(){btn.classList.remove('is-dirty');btn.disabled=true},500)})})();</script>
