<?php declare(strict_types=1); ?>
<?php $title = 'TropaTT — Периодические задачи'; ?>
<body data-page="recurring" data-protected="1"><div class="crm-app"><aside class="crm-sidebar"><div class="crm-brand"><span class="crm-brand-mark"></span> TropaTT</div><nav class="nav flex-column crm-nav"></nav></aside>
<div class="crm-main-wrap"><header class="crm-topbar py-2"><div class="container-fluid"></div></header>
<main class="crm-content crm-automation-page"><div class="crm-page-head"><div><h1 class="crm-page-title">Периодические задачи</h1><p class="crm-subtitle">Шаблоны, по которым CRM сама создаёт повторяющиеся задачи, напоминания и события.</p></div><div class="d-flex gap-2"><button id="recurringRefreshBtn" class="btn crm-btn-secondary" type="button"><i class="fa-solid fa-rotate me-1" aria-hidden="true"></i>Обновить</button><button id="recurringCreateBtn" class="btn crm-btn-primary" type="button"><i class="fa-solid fa-plus me-1" aria-hidden="true"></i>Создать шаблон</button></div></div>

<div class="crm-automation-brief" aria-label="Как работают периодические задачи">
  <div class="crm-automation-brief-item"><span class="crm-automation-icon"><i class="fa-solid fa-repeat" aria-hidden="true"></i></span><strong>Автосоздание</strong><p>CRM берёт исходную сущность как шаблон и создаёт новый экземпляр по расписанию.</p></div>
  <div class="crm-automation-brief-item"><span class="crm-automation-icon"><i class="fa-solid fa-calendar-days" aria-hidden="true"></i></span><strong>Расписание</strong><p>Поддерживается RRULE: каждый день, по будням, раз в неделю или в выбранные дни месяца.</p></div>
  <div class="crm-automation-brief-item"><span class="crm-automation-icon"><i class="fa-solid fa-pause" aria-hidden="true"></i></span><strong>Контроль</strong><p>Любой шаблон можно временно остановить, возобновить или удалить без изменения исходной задачи.</p></div>
</div>

<div class="row g-3">
  <div class="col-12">
    <div class="crm-card crm-section-card">
      <div class="crm-section-head"><div><h2 class="h6 mb-0">Шаблоны автосоздания</h2><div class="crm-section-note">Что, когда и в каком состоянии будет повторяться.</div></div></div>
      <div class="table-responsive"><table class="table table-sm crm-table crm-automation-table mb-0"><thead><tr><th>Шаблон</th><th>Расписание</th><th>Следующий запуск</th><th>Статус</th><th class="text-end">Действия</th></tr></thead><tbody id="recurringBody"><tr><td colspan="5" class="text-muted">Загрузка...</td></tr></tbody></table></div>
    </div>
  </div>
</div>

<div class="modal fade" id="recurringCreateModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered modal-lg"><div class="modal-content"><div class="modal-header"><div><h5 class="modal-title">Создать шаблон периодической задачи</h5><div class="crm-modal-subtitle">Выберите исходную сущность и понятное расписание. API по-прежнему получает точный RRULE.</div></div><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button></div><form id="recurringCreateForm"><div class="modal-body"><div class="row g-3"><div class="col-md-5"><label class="form-label">Что повторять</label><select class="form-select" name="entity_type" required><option value="task">Задача</option><option value="project">Проект</option><option value="reminder">Напоминание</option><option value="calendar_event">Событие календаря</option></select></div><div class="col-md-7"><label class="form-label">Public ID исходной сущности</label><input class="form-control crm-monospace-input" name="entity_public_id" maxlength="64" required placeholder="Например: task_... или 01ABCD..."><div class="form-text">ID можно взять из URL карточки или API-ответа.</div></div></div><div class="mt-3"><label class="form-label">Быстрые варианты расписания</label><div class="crm-preset-row" role="group" aria-label="Пресеты RRULE"><button class="btn crm-btn-subtle crm-preset-btn" type="button" data-rrule-preset="FREQ=DAILY">Каждый день</button><button class="btn crm-btn-subtle crm-preset-btn" type="button" data-rrule-preset="FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR">По будням</button><button class="btn crm-btn-subtle crm-preset-btn" type="button" data-rrule-preset="FREQ=WEEKLY;BYDAY=MO,WE,FR">Пн, ср, пт</button><button class="btn crm-btn-subtle crm-preset-btn" type="button" data-rrule-preset="FREQ=MONTHLY;BYMONTHDAY=1">1-го числа</button></div></div><div class="mt-3"><label class="form-label">RRULE</label><input class="form-control crm-monospace-input" name="rrule" maxlength="1000" required placeholder="FREQ=WEEKLY;BYDAY=MO,WE,FR"><div class="crm-inline-help mt-2"><i class="fa-solid fa-circle-info" aria-hidden="true"></i><span>Формат RFC 5545. Если нужен сложный сценарий, можно оставить свой RRULE вручную.</span></div></div></div><div class="modal-footer"><button class="btn crm-btn-secondary" type="button" data-bs-dismiss="modal">Отмена</button><button class="btn crm-btn-primary" type="submit">Создать шаблон</button></div></form></div></div></div>

</main></div></div>
