SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `module_worksection_unresolved_entities`;
DROP TABLE IF EXISTS `module_worksection_job_logs`;
DROP TABLE IF EXISTS `module_worksection_rate_limits`;
DROP TABLE IF EXISTS `module_worksection_user_mappings`;
DROP TABLE IF EXISTS `module_worksection_source_mappings`;
DROP TABLE IF EXISTS `module_worksection_job_items`;
DROP TABLE IF EXISTS `module_worksection_jobs`;
DROP TABLE IF EXISTS `module_worksection_connections`;
SET FOREIGN_KEY_CHECKS = 1;
