<?php
declare(strict_types=1);

/**
 * Supplemental translations for keys added after the main locale catalogs.
 * Keep this file small and move entries into the main catalog during the next
 * language-file regeneration.
 */
return [
    'ru-ru' => [
        'admin_statuses' => ['section_task_statuses' => 'Статусы задач', 'section_project_statuses' => 'Статусы проектов'],
        'client_detail' => ['btn_create_task' => 'Создать задачу', 'btn_create_project' => 'Создать проект'],
        'clients' => ['extra_attributes_hint' => 'Укажите пары «поле — значение» в JSON. После сохранения они видны в карточке и доступны для поиска.', 'field_address_actual' => 'Фактический адрес', 'filter_extra_label' => 'Кастомные поля', 'filter_extra_placeholder' => 'Например: VIP или источник', 'th_extra' => 'Доп. поля'],
        'contacts' => ['opt_custom_role' => 'Другая роль (своя)...', 'role_custom_placeholder' => 'Введите свою роль'],
        'counterparties' => ['extra_attributes_hint' => 'Укажите дополнительные поля в формате JSON.', 'field_address_actual' => 'Фактический адрес', 'field_extra_attributes' => 'Дополнительные поля (JSON)', 'th_extra' => 'Доп. поля'],
        'counterparty_detail' => ['btn_create_task' => 'Создать задачу', 'btn_create_project' => 'Создать проект', 'contact_role_custom' => 'Своя роль...', 'contact_role_custom_placeholder' => 'Введите свою роль', 'requisites_field_address_actual' => 'Фактический адрес'],
        'intake' => ['accept_confirm_btn' => 'Принять и создать задачу', 'accept_field_project' => 'Проект', 'create_btn' => 'Создать заявку', 'delete_confirm' => 'Удалить эту заявку? Это действие необратимо.', 'delete_confirm_btn' => 'Удалить', 'delete_title' => 'Удалить заявку', 'duplicate_confirm_btn' => 'Отметить дубликатом', 'duplicate_field_target' => 'ID заявки-дубликата', 'duplicate_field_target_hint' => 'Укажите public_id существующей заявки, дубликатом которой является текущая', 'duplicate_field_target_placeholder' => 'Введите public_id заявки', 'field_due_date' => 'Срок', 'field_source_ref' => 'Ссылка источника', 'field_source_ref_placeholder' => 'Email или внешняя ссылка', 'option_no_assignee' => 'Не назначен', 'option_no_client' => 'Не выбран', 'option_no_project' => 'Не выбран', 'priority_high' => 'Высокий', 'priority_low' => 'Низкий', 'priority_normal' => 'Средний', 'priority_urgent' => 'Срочный', 'reject_confirm_btn' => 'Отклонить', 'reject_field_reason' => 'Причина отклонения', 'reopen_confirm' => 'Вернуть эту заявку в статус «Ожидает» для повторного рассмотрения?', 'reopen_confirm_btn' => 'Восстановить', 'reopen_title' => 'Восстановить заявку', 'section_list_title' => 'Заявки', 'snooze_confirm_btn' => 'Отложить', 'snooze_field_date' => 'Отложить до', 'th_client' => 'Клиент', 'th_id' => 'ID'],
        'projects' => ['th_updated' => 'Обновлён'],
        'tasks' => ['filter_all_clients' => 'Все клиенты', 'filter_client' => 'Клиент', 'th_assignee' => 'Исполнитель', 'th_client' => 'Клиент', 'th_manager' => 'Менеджер'],
    ],
    'en-gb' => [
        'admin_statuses' => ['section_task_statuses' => 'Task statuses', 'section_project_statuses' => 'Project statuses'],
        'client_detail' => ['btn_create_task' => 'Create task', 'btn_create_project' => 'Create project'],
        'clients' => ['extra_attributes_hint' => 'Enter field-value pairs as JSON. They appear in the card and can be searched after saving.', 'field_address_actual' => 'Actual address', 'filter_extra_label' => 'Custom fields', 'filter_extra_placeholder' => 'For example: VIP or source', 'th_extra' => 'Extra fields'],
        'contacts' => ['opt_custom_role' => 'Other (custom) role...', 'role_custom_placeholder' => 'Enter a custom role'],
        'counterparties' => ['extra_attributes_hint' => 'Enter additional fields as a JSON object.', 'field_address_actual' => 'Actual address', 'field_extra_attributes' => 'Additional fields (JSON)', 'th_extra' => 'Extra fields'],
        'counterparty_detail' => ['btn_create_task' => 'Create task', 'btn_create_project' => 'Create project', 'contact_role_custom' => 'Custom role...', 'contact_role_custom_placeholder' => 'Enter a custom role', 'requisites_field_address_actual' => 'Actual address'],
        'intake' => ['accept_confirm_btn' => 'Accept and create task', 'accept_field_project' => 'Project', 'create_btn' => 'Create request', 'delete_confirm' => 'Delete this request? This action cannot be undone.', 'delete_confirm_btn' => 'Delete', 'delete_title' => 'Delete request', 'duplicate_confirm_btn' => 'Mark as duplicate', 'duplicate_field_target' => 'Duplicate request ID', 'duplicate_field_target_hint' => 'Enter the public_id of the existing request that duplicates this one', 'duplicate_field_target_placeholder' => 'Enter request public_id', 'field_due_date' => 'Due date', 'field_source_ref' => 'Source link', 'field_source_ref_placeholder' => 'Email or external link', 'option_no_assignee' => 'Unassigned', 'option_no_client' => 'No client selected', 'option_no_project' => 'No project selected', 'priority_high' => 'High', 'priority_low' => 'Low', 'priority_normal' => 'Medium', 'priority_urgent' => 'Urgent', 'reject_confirm_btn' => 'Reject', 'reject_field_reason' => 'Rejection reason', 'reopen_confirm' => 'Return this request to Pending for review again?', 'reopen_confirm_btn' => 'Restore', 'reopen_title' => 'Restore request', 'section_list_title' => 'Requests', 'snooze_confirm_btn' => 'Snooze', 'snooze_field_date' => 'Snooze until', 'th_client' => 'Client', 'th_id' => 'ID'],
        'projects' => ['th_updated' => 'Updated'],
        'tasks' => ['filter_all_clients' => 'All clients', 'filter_client' => 'Client', 'th_assignee' => 'Assignee', 'th_client' => 'Client', 'th_manager' => 'Manager'],
    ],
    'de-de' => [
        'admin_statuses' => ['section_task_statuses' => 'Aufgabenstatus', 'section_project_statuses' => 'Projektstatus'],
        'client_detail' => ['btn_create_task' => 'Aufgabe erstellen', 'btn_create_project' => 'Projekt erstellen'],
        'clients' => ['extra_attributes_hint' => 'Geben Sie Feld-Wert-Paare als JSON ein. Nach dem Speichern erscheinen sie in der Karte und sind durchsuchbar.', 'field_address_actual' => 'Tatsächliche Adresse', 'filter_extra_label' => 'Benutzerdefinierte Felder', 'filter_extra_placeholder' => 'Zum Beispiel: VIP oder Quelle', 'th_extra' => 'Zusatzfelder'],
        'contacts' => ['opt_custom_role' => 'Andere (eigene) Rolle...', 'role_custom_placeholder' => 'Eigene Rolle eingeben'],
        'counterparties' => ['extra_attributes_hint' => 'Geben Sie zusätzliche Felder als JSON-Objekt ein.', 'field_address_actual' => 'Tatsächliche Adresse', 'field_extra_attributes' => 'Zusätzliche Felder (JSON)', 'th_extra' => 'Zusatzfelder'],
        'counterparty_detail' => ['btn_create_task' => 'Aufgabe erstellen', 'btn_create_project' => 'Projekt erstellen', 'contact_role_custom' => 'Eigene Rolle...', 'contact_role_custom_placeholder' => 'Eigene Rolle eingeben', 'requisites_field_address_actual' => 'Tatsächliche Adresse'],
        'intake' => ['accept_confirm_btn' => 'Annehmen und Aufgabe erstellen', 'accept_field_project' => 'Projekt', 'create_btn' => 'Anfrage erstellen', 'delete_confirm' => 'Diese Anfrage löschen? Die Aktion kann nicht rückgängig gemacht werden.', 'delete_confirm_btn' => 'Löschen', 'delete_title' => 'Anfrage löschen', 'duplicate_confirm_btn' => 'Als Duplikat markieren', 'duplicate_field_target' => 'ID der doppelten Anfrage', 'duplicate_field_target_hint' => 'Geben Sie die public_id der bestehenden doppelten Anfrage ein', 'duplicate_field_target_placeholder' => 'public_id der Anfrage eingeben', 'field_due_date' => 'Frist', 'field_source_ref' => 'Quelllink', 'field_source_ref_placeholder' => 'E-Mail oder externer Link', 'option_no_assignee' => 'Nicht zugewiesen', 'option_no_client' => 'Kein Kunde ausgewählt', 'option_no_project' => 'Kein Projekt ausgewählt', 'priority_high' => 'Hoch', 'priority_low' => 'Niedrig', 'priority_normal' => 'Mittel', 'priority_urgent' => 'Dringend', 'reject_confirm_btn' => 'Ablehnen', 'reject_field_reason' => 'Ablehnungsgrund', 'reopen_confirm' => 'Anfrage zur erneuten Prüfung auf Ausstehend setzen?', 'reopen_confirm_btn' => 'Wiederherstellen', 'reopen_title' => 'Anfrage wiederherstellen', 'section_list_title' => 'Anfragen', 'snooze_confirm_btn' => 'Zurückstellen', 'snooze_field_date' => 'Zurückstellen bis', 'th_client' => 'Kunde', 'th_id' => 'ID'],
        'projects' => ['th_updated' => 'Aktualisiert'],
        'tasks' => ['filter_all_clients' => 'Alle Kunden', 'filter_client' => 'Kunde', 'th_assignee' => 'Zuständig', 'th_client' => 'Kunde', 'th_manager' => 'Manager'],
    ],
    'es-es' => [
        'admin_statuses' => ['section_task_statuses' => 'Estados de tareas', 'section_project_statuses' => 'Estados de proyectos'],
        'client_detail' => ['btn_create_task' => 'Crear tarea', 'btn_create_project' => 'Crear proyecto'],
        'clients' => ['extra_attributes_hint' => 'Introduzca pares campo-valor en JSON. Después de guardar, aparecerán en la ficha y podrán buscarse.', 'field_address_actual' => 'Dirección real', 'filter_extra_label' => 'Campos personalizados', 'filter_extra_placeholder' => 'Por ejemplo: VIP u origen', 'th_extra' => 'Campos extra'],
        'contacts' => ['opt_custom_role' => 'Otro rol personalizado...', 'role_custom_placeholder' => 'Introduzca un rol personalizado'],
        'counterparties' => ['extra_attributes_hint' => 'Introduzca los campos adicionales como un objeto JSON.', 'field_address_actual' => 'Dirección real', 'field_extra_attributes' => 'Campos adicionales (JSON)', 'th_extra' => 'Campos extra'],
        'counterparty_detail' => ['btn_create_task' => 'Crear tarea', 'btn_create_project' => 'Crear proyecto', 'contact_role_custom' => 'Rol personalizado...', 'contact_role_custom_placeholder' => 'Introduzca un rol personalizado', 'requisites_field_address_actual' => 'Dirección real'],
        'intake' => ['accept_confirm_btn' => 'Aceptar y crear tarea', 'accept_field_project' => 'Proyecto', 'create_btn' => 'Crear solicitud', 'delete_confirm' => '¿Eliminar esta solicitud? Esta acción no se puede deshacer.', 'delete_confirm_btn' => 'Eliminar', 'delete_title' => 'Eliminar solicitud', 'duplicate_confirm_btn' => 'Marcar como duplicada', 'duplicate_field_target' => 'ID de solicitud duplicada', 'duplicate_field_target_hint' => 'Introduzca el public_id de la solicitud existente que duplica esta', 'duplicate_field_target_placeholder' => 'Introduzca el public_id de la solicitud', 'field_due_date' => 'Fecha límite', 'field_source_ref' => 'Enlace de origen', 'field_source_ref_placeholder' => 'Correo o enlace externo', 'option_no_assignee' => 'Sin asignar', 'option_no_client' => 'Sin cliente seleccionado', 'option_no_project' => 'Sin proyecto seleccionado', 'priority_high' => 'Alta', 'priority_low' => 'Baja', 'priority_normal' => 'Media', 'priority_urgent' => 'Urgente', 'reject_confirm_btn' => 'Rechazar', 'reject_field_reason' => 'Motivo del rechazo', 'reopen_confirm' => '¿Volver a poner esta solicitud en Pendiente para revisarla de nuevo?', 'reopen_confirm_btn' => 'Restaurar', 'reopen_title' => 'Restaurar solicitud', 'section_list_title' => 'Solicitudes', 'snooze_confirm_btn' => 'Posponer', 'snooze_field_date' => 'Posponer hasta', 'th_client' => 'Cliente', 'th_id' => 'ID'],
        'projects' => ['th_updated' => 'Actualizado'],
        'tasks' => ['filter_all_clients' => 'Todos los clientes', 'filter_client' => 'Cliente', 'th_assignee' => 'Responsable', 'th_client' => 'Cliente', 'th_manager' => 'Gerente'],
    ],
    'fr-fr' => [
        'admin_statuses' => ['section_task_statuses' => 'Statuts des tâches', 'section_project_statuses' => 'Statuts des projets'],
        'client_detail' => ['btn_create_task' => 'Créer une tâche', 'btn_create_project' => 'Créer un projet'],
        'clients' => ['extra_attributes_hint' => 'Saisissez les paires champ-valeur en JSON. Après l’enregistrement, elles apparaîtront dans la fiche et seront recherchables.', 'field_address_actual' => 'Adresse réelle', 'filter_extra_label' => 'Champs personnalisés', 'filter_extra_placeholder' => 'Par exemple : VIP ou source', 'th_extra' => 'Champs supplémentaires'],
        'contacts' => ['opt_custom_role' => 'Autre rôle personnalisé...', 'role_custom_placeholder' => 'Saisissez un rôle personnalisé'],
        'counterparties' => ['extra_attributes_hint' => 'Saisissez les champs supplémentaires comme objet JSON.', 'field_address_actual' => 'Adresse réelle', 'field_extra_attributes' => 'Champs supplémentaires (JSON)', 'th_extra' => 'Champs supplémentaires'],
        'counterparty_detail' => ['btn_create_task' => 'Créer une tâche', 'btn_create_project' => 'Créer un projet', 'contact_role_custom' => 'Rôle personnalisé...', 'contact_role_custom_placeholder' => 'Saisissez un rôle personnalisé', 'requisites_field_address_actual' => 'Adresse réelle'],
        'intake' => ['accept_confirm_btn' => 'Accepter et créer une tâche', 'accept_field_project' => 'Projet', 'create_btn' => 'Créer une demande', 'delete_confirm' => 'Supprimer cette demande ? Cette action est irréversible.', 'delete_confirm_btn' => 'Supprimer', 'delete_title' => 'Supprimer la demande', 'duplicate_confirm_btn' => 'Marquer comme doublon', 'duplicate_field_target' => 'ID de la demande doublon', 'duplicate_field_target_hint' => 'Saisissez le public_id de la demande existante qui est le doublon', 'duplicate_field_target_placeholder' => 'Saisissez le public_id de la demande', 'field_due_date' => 'Échéance', 'field_source_ref' => 'Lien source', 'field_source_ref_placeholder' => 'E-mail ou lien externe', 'option_no_assignee' => 'Non attribué', 'option_no_client' => 'Aucun client sélectionné', 'option_no_project' => 'Aucun projet sélectionné', 'priority_high' => 'Élevée', 'priority_low' => 'Faible', 'priority_normal' => 'Moyenne', 'priority_urgent' => 'Urgente', 'reject_confirm_btn' => 'Refuser', 'reject_field_reason' => 'Motif du refus', 'reopen_confirm' => 'Renvoyer cette demande au statut En attente pour une nouvelle vérification ?', 'reopen_confirm_btn' => 'Restaurer', 'reopen_title' => 'Restaurer la demande', 'section_list_title' => 'Demandes', 'snooze_confirm_btn' => 'Reporter', 'snooze_field_date' => 'Reporter jusqu’au', 'th_client' => 'Client', 'th_id' => 'ID'],
        'projects' => ['th_updated' => 'Mis à jour'],
        'tasks' => ['filter_all_clients' => 'Tous les clients', 'filter_client' => 'Client', 'th_assignee' => 'Responsable', 'th_client' => 'Client', 'th_manager' => 'Responsable'],
    ],
    'pt-br' => [
        'admin_statuses' => ['section_task_statuses' => 'Status das tarefas', 'section_project_statuses' => 'Status dos projetos'],
        'client_detail' => ['btn_create_task' => 'Criar tarefa', 'btn_create_project' => 'Criar projeto'],
        'clients' => ['extra_attributes_hint' => 'Informe pares campo-valor em JSON. Após salvar, eles aparecem no cadastro e podem ser pesquisados.', 'field_address_actual' => 'Endereço real', 'filter_extra_label' => 'Campos personalizados', 'filter_extra_placeholder' => 'Por exemplo: VIP ou origem', 'th_extra' => 'Campos extras'],
        'contacts' => ['opt_custom_role' => 'Outro papel personalizado...', 'role_custom_placeholder' => 'Digite um papel personalizado'],
        'counterparties' => ['extra_attributes_hint' => 'Informe os campos adicionais como um objeto JSON.', 'field_address_actual' => 'Endereço real', 'field_extra_attributes' => 'Campos adicionais (JSON)', 'th_extra' => 'Campos extras'],
        'counterparty_detail' => ['btn_create_task' => 'Criar tarefa', 'btn_create_project' => 'Criar projeto', 'contact_role_custom' => 'Papel personalizado...', 'contact_role_custom_placeholder' => 'Digite um papel personalizado', 'requisites_field_address_actual' => 'Endereço real'],
        'intake' => ['accept_confirm_btn' => 'Aceitar e criar tarefa', 'accept_field_project' => 'Projeto', 'create_btn' => 'Criar solicitação', 'delete_confirm' => 'Excluir esta solicitação? Esta ação não pode ser desfeita.', 'delete_confirm_btn' => 'Excluir', 'delete_title' => 'Excluir solicitação', 'duplicate_confirm_btn' => 'Marcar como duplicada', 'duplicate_field_target' => 'ID da solicitação duplicada', 'duplicate_field_target_hint' => 'Informe o public_id da solicitação existente que duplica esta', 'duplicate_field_target_placeholder' => 'Informe o public_id da solicitação', 'field_due_date' => 'Prazo', 'field_source_ref' => 'Link de origem', 'field_source_ref_placeholder' => 'E-mail ou link externo', 'option_no_assignee' => 'Não atribuído', 'option_no_client' => 'Nenhum cliente selecionado', 'option_no_project' => 'Nenhum projeto selecionado', 'priority_high' => 'Alta', 'priority_low' => 'Baixa', 'priority_normal' => 'Média', 'priority_urgent' => 'Urgente', 'reject_confirm_btn' => 'Rejeitar', 'reject_field_reason' => 'Motivo da rejeição', 'reopen_confirm' => 'Retornar esta solicitação para Pendente para nova análise?', 'reopen_confirm_btn' => 'Restaurar', 'reopen_title' => 'Restaurar solicitação', 'section_list_title' => 'Solicitações', 'snooze_confirm_btn' => 'Adiar', 'snooze_field_date' => 'Adiar até', 'th_client' => 'Cliente', 'th_id' => 'ID'],
        'projects' => ['th_updated' => 'Atualizado'],
        'tasks' => ['filter_all_clients' => 'Todos os clientes', 'filter_client' => 'Cliente', 'th_assignee' => 'Responsável', 'th_client' => 'Cliente', 'th_manager' => 'Gerente'],
    ],
    'zh-cn' => [
        'admin_statuses' => ['section_task_statuses' => '任务状态', 'section_project_statuses' => '项目状态'],
        'client_detail' => ['btn_create_task' => '创建任务', 'btn_create_project' => '创建项目'],
        'clients' => ['extra_attributes_hint' => '请以 JSON 格式填写字段和值。保存后会显示在卡片中并支持搜索。', 'field_address_actual' => '实际地址', 'filter_extra_label' => '自定义字段', 'filter_extra_placeholder' => '例如：VIP 或来源', 'th_extra' => '额外字段'],
        'contacts' => ['opt_custom_role' => '其他自定义角色...', 'role_custom_placeholder' => '请输入自定义角色'],
        'counterparties' => ['extra_attributes_hint' => '请以 JSON 对象格式填写额外字段。', 'field_address_actual' => '实际地址', 'field_extra_attributes' => '额外字段（JSON）', 'th_extra' => '额外字段'],
        'counterparty_detail' => ['btn_create_task' => '创建任务', 'btn_create_project' => '创建项目', 'contact_role_custom' => '自定义角色...', 'contact_role_custom_placeholder' => '请输入自定义角色', 'requisites_field_address_actual' => '实际地址'],
        'intake' => ['accept_confirm_btn' => '接受并创建任务', 'accept_field_project' => '项目', 'create_btn' => '创建请求', 'delete_confirm' => '删除此请求？此操作无法撤销。', 'delete_confirm_btn' => '删除', 'delete_title' => '删除请求', 'duplicate_confirm_btn' => '标记为重复', 'duplicate_field_target' => '重复请求 ID', 'duplicate_field_target_hint' => '请输入当前请求对应的现有重复请求 public_id', 'duplicate_field_target_placeholder' => '请输入请求 public_id', 'field_due_date' => '截止日期', 'field_source_ref' => '来源链接', 'field_source_ref_placeholder' => '电子邮件或外部链接', 'option_no_assignee' => '未分配', 'option_no_client' => '未选择客户', 'option_no_project' => '未选择项目', 'priority_high' => '高', 'priority_low' => '低', 'priority_normal' => '中', 'priority_urgent' => '紧急', 'reject_confirm_btn' => '拒绝', 'reject_field_reason' => '拒绝原因', 'reopen_confirm' => '将此请求恢复为待处理状态以便重新审核？', 'reopen_confirm_btn' => '恢复', 'reopen_title' => '恢复请求', 'section_list_title' => '请求', 'snooze_confirm_btn' => '稍后处理', 'snooze_field_date' => '推迟至', 'th_client' => '客户', 'th_id' => 'ID'],
        'projects' => ['th_updated' => '已更新'],
        'tasks' => ['filter_all_clients' => '所有客户', 'filter_client' => '客户', 'th_assignee' => '负责人', 'th_client' => '客户', 'th_manager' => '经理'],
    ],
];
