SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `module_toggl_unresolved_entities`;
DROP TABLE IF EXISTS `module_toggl_job_logs`;
DROP TABLE IF EXISTS `module_toggl_rate_limits`;
DROP TABLE IF EXISTS `module_toggl_user_mappings`;
DROP TABLE IF EXISTS `module_toggl_source_mappings`;
DROP TABLE IF EXISTS `module_toggl_job_items`;
DROP TABLE IF EXISTS `module_toggl_jobs`;
DROP TABLE IF EXISTS `module_toggl_connections`;
SET FOREIGN_KEY_CHECKS = 1;
