<?php
declare(strict_types=1);

namespace Module\Crm\Bitrix24Migration\Controller;

use Api\System\Library\Container;
use Api\System\Library\Http\JsonResponse;
use Module\Crm\Bitrix24Migration\Repository\Bitrix24MigrationRepository;
use Module\Crm\Bitrix24Migration\Service\Bitrix24Client;
use Module\Crm\Bitrix24Migration\Service\Bitrix24Crawler;
use Module\Crm\Bitrix24Migration\Service\Bitrix24ImportService;
use Module\Crm\Bitrix24Migration\Service\Bitrix24TargetWriter;
use Module\Crm\Bitrix24Migration\Service\EncryptionService;

final class Bitrix24MigrationController
{
    private Bitrix24MigrationRepository $repo;
    public function __construct(private readonly Container $container){$this->repo=new Bitrix24MigrationRepository($container->get('db.pdo'));}
    private function body(): array {$req=$this->container->get('request');$decoded=json_decode((string)($req->rawBody??''),true);return is_array($decoded)?$decoded:(array)($req->allInput()??[]);}
    private function actor(): array {$auth=$this->container->has('auth_user')?$this->container->get('auth_user'):[];return is_array($auth)&&is_array($auth['user']??null)?$auth['user']:[];}
    private function actorId(): int{return(int)($this->actor()['id']??0);}
    private function can(string $p): bool {$a=$this->actor();return!empty($a['is_root'])||in_array('*',(array)($a['permission_codes']??[]),true)||in_array($p,(array)($a['permission_codes']??[]),true);}
    private function connection(string $id): array|JsonResponse {$r=$this->repo->getConnection($id);if(!$r)return JsonResponse::error('NOT_FOUND','Bitrix24 connection not found',404);if(!$this->can('module.bitrix24-migration.manage')&&(int)$r['created_by_user_id']!==$this->actorId())return JsonResponse::error('FORBIDDEN','Connection access denied',403);return$r;}
    private function job(string $id): array|JsonResponse {$r=$this->repo->getJob($id);if(!$r)return JsonResponse::error('NOT_FOUND','Bitrix24 job not found',404);if(!$this->can('module.bitrix24-migration.manage')&&(int)$r['created_by_user_id']!==$this->actorId())return JsonResponse::error('FORBIDDEN','Job access denied',403);return$r;}
    private function publicConnection(array $r): array {unset($r['webhook_url_encrypted'],$r['access_token_encrypted'],$r['refresh_token_encrypted'],$r['client_id_encrypted'],$r['client_secret_encrypted']);return$r;}
    private function publicJob(array $r): array {unset($r['lease_token'],$r['lease_until']);return$r;}

    public function listConnections(): JsonResponse{return JsonResponse::success('BITRIX24_CONNECTIONS_LIST','OK',['connections'=>array_map([$this,'publicConnection'],$this->repo->listConnections($this->actorId(),$this->can('module.bitrix24-migration.manage')))]);}
    public function createConnection(): JsonResponse
    {
        $in=$this->body();$name=trim((string)($in['name']??''));$type=(string)($in['auth_type']??'webhook');$portal=rtrim(trim((string)($in['portal_url']??'')),'/');if($name===''||!in_array($type,['webhook','oauth'],true)||!$this->validPublicHttpsUrl($portal))return JsonResponse::error('VALIDATION_ERROR','name, public https portal_url and a supported auth_type are required',422);
        $d=['name'=>mb_substr($name,0,255),'auth_type'=>$type,'portal_url'=>$portal,'created_by_user_id'=>$this->actorId()];
        if($type==='webhook'){$webhook=trim((string)($in['webhook_url']??''));if(!$this->validWebhook($webhook,$portal))return JsonResponse::error('VALIDATION_ERROR','webhook_url must be an https Bitrix24 REST webhook for the selected portal',422);$d['webhook_url_encrypted']=EncryptionService::encrypt($webhook);}else{$access=trim((string)($in['access_token']??''));$refresh=trim((string)($in['refresh_token']??''));$clientId=trim((string)($in['client_id']??''));$clientSecret=trim((string)($in['client_secret']??''));if($access===''||$refresh===''||$clientId===''||$clientSecret==='')return JsonResponse::error('VALIDATION_ERROR','OAuth access_token, refresh_token, client_id and client_secret are required',422);$d['access_token_encrypted']=EncryptionService::encrypt($access);$d['refresh_token_encrypted']=EncryptionService::encrypt($refresh);$d['client_id_encrypted']=EncryptionService::encrypt($clientId);$d['client_secret_encrypted']=EncryptionService::encrypt($clientSecret);}
        $row=$this->repo->createConnection($d);try{$client=$this->client($row);$me=$client->test();$this->repo->updateConnectionCheck((string)$row['public_id'],true);return JsonResponse::success('BITRIX24_CONNECTION_CREATED','Connection created and verified',['connection'=>$this->publicConnection($this->repo->getConnection((string)$row['public_id'])??$row),'user'=>$me],201);}catch(\Throwable $e){$this->repo->updateConnectionCheck((string)$row['public_id'],false,'Bitrix24 credentials could not be verified');return JsonResponse::error('BITRIX24_CONNECTION_TEST_FAILED','Bitrix24 credentials could not be verified',422);}
    }
    public function getConnection(array $p): JsonResponse {$r=$this->connection((string)($p['public_id']??''));return$r instanceof JsonResponse?$r:JsonResponse::success('BITRIX24_CONNECTION','OK',['connection'=>$this->publicConnection($r)]);}
    public function updateConnection(array $p): JsonResponse {$r=$this->connection((string)($p['public_id']??''));if($r instanceof JsonResponse)return$r;$in=$this->body();$d=[];if(array_key_exists('name',$in))$d['name']=mb_substr(trim((string)$in['name']),0,255);if(array_key_exists('portal_url',$in)){if(!$this->validPublicHttpsUrl((string)$in['portal_url']))return JsonResponse::error('VALIDATION_ERROR','portal_url must be a public HTTPS URL',422);$d['portal_url']=rtrim(trim((string)$in['portal_url']),'/');}if(($r['auth_type']??'')==='webhook'&&(string)($in['webhook_url']??'')!==''){$u=trim((string)$in['webhook_url']);if(!$this->validWebhook($u,(string)($d['portal_url']??$r['portal_url'])))return JsonResponse::error('VALIDATION_ERROR','Invalid webhook URL',422);$d['webhook_url_encrypted']=EncryptionService::encrypt($u);}foreach(['access_token','refresh_token','client_id','client_secret'] as $field)if((string)($in[$field]??'')!=='')$d[$field.'_encrypted']=EncryptionService::encrypt(trim((string)$in[$field]));if($d!==[])$this->repo->updateConnection((string)$p['public_id'],$d);return JsonResponse::success('BITRIX24_CONNECTION_UPDATED','Connection updated',['connection'=>$this->publicConnection($this->repo->getConnection((string)$p['public_id'])??[])]);}
    public function deleteConnection(array $p): JsonResponse {$r=$this->connection((string)($p['public_id']??''));if($r instanceof JsonResponse)return$r;if($this->repo->hasRunningJobs((int)$r['id']))return JsonResponse::error('CONNECTION_HAS_RUNNING_JOBS','Cancel running jobs first',409);$this->repo->deleteConnection((int)$r['id']);return JsonResponse::success('BITRIX24_CONNECTION_DELETED','Connection deleted');}
    public function testConnection(array $p): JsonResponse {$r=$this->connection((string)($p['public_id']??''));if($r instanceof JsonResponse)return$r;try{$me=$this->client($r)->test();$this->repo->updateConnectionCheck((string)$r['public_id'],true);return JsonResponse::success('BITRIX24_CONNECTION_TEST_OK','Connection successful',['user'=>$me]);}catch(\Throwable){$this->repo->updateConnectionCheck((string)$r['public_id'],false,'Bitrix24 connection test failed');return JsonResponse::error('BITRIX24_CONNECTION_TEST_FAILED','Bitrix24 connection test failed',400);}}
    public function discover(array $p): JsonResponse {$r=$this->connection((string)($p['public_id']??''));if($r instanceof JsonResponse)return$r;$in=$this->body();$types=(array)($in['entities']??['department','user','company','contact','lead','deal','project','task']);$client=$this->client($r);$out=[];foreach(array_values(array_intersect(array_map('strval',$types),['department','user','company','contact','lead','deal','invoice','quote','product','project','task'])) as $type){try{$out[$type]=match($type){'department'=>$client->departments(),'user'=>$client->users(),'company'=>$client->companies(),'contact'=>$client->contacts(),'lead'=>$client->leads(),'deal'=>$client->deals(),'invoice'=>$client->invoices(),'quote'=>$client->quotes(),'product'=>$client->products(),'project'=>$client->projects(),'task'=>$client->tasks(),default=>[]};if($type==='user')foreach($out[$type] as $u)$this->repo->upsertUserMapping((int)$r['id'],$u);}catch(\Throwable){$out[$type]=[];}}return JsonResponse::success('BITRIX24_DISCOVERY_COMPLETE','Discovery completed',['entities'=>$out,'user_mappings'=>$this->repo->listUserMappings((int)$r['id'])]);}
    public function listUserMappings(array $p): JsonResponse {$r=$this->connection((string)($p['public_id']??''));return$r instanceof JsonResponse?$r:JsonResponse::success('BITRIX24_USER_MAPPINGS','OK',['items'=>$this->repo->listUserMappings((int)$r['id'])]);}
    public function updateUserMapping(array $p): JsonResponse {$r=$this->connection((string)($p['public_id']??''));if($r instanceof JsonResponse)return$r;$in=$this->body();$crm=!empty($in['crm_user_public_id'])?(string)$in['crm_user_public_id']:null;if($crm!==null&&$this->repo->activeUserPublicId($crm)===null)return JsonResponse::error('USER_NOT_FOUND','Active CRM user not found',404);if(!$this->repo->updateUserMapping((int)$r['id'],(int)($p['mapping_id']??0),$crm))return JsonResponse::error('MAPPING_NOT_FOUND','Mapping not found',404);return JsonResponse::success('BITRIX24_USER_MAPPING_UPDATED','Mapping updated');}
    public function listJobs(): JsonResponse{return JsonResponse::success('BITRIX24_JOBS_LIST','OK',['items'=>array_map([$this,'publicJob'],$this->repo->listJobs($this->actorId(),$this->can('module.bitrix24-migration.manage')))]);}
    public function createJob(): JsonResponse {$in=$this->body();$r=$this->connection((string)($in['connection_public_id']??''));if($r instanceof JsonResponse)return$r;$mode=(string)($in['mode']??'import');if(!in_array($mode,['import','sync','dry_run'],true))return JsonResponse::error('VALIDATION_ERROR','mode must be import, sync or dry_run',422);$scope=(array)($in['source_scope']??[]);$scope['entities']=array_values(array_intersect(array_map('strval',(array)($in['entities']??$scope['entities']??['department','user','company','contact','lead','deal','project','task'])),['department','user','company','contact','lead','deal','invoice','quote','product','project','task','activity','event']));if($scope['entities']===[])return JsonResponse::error('VALIDATION_ERROR','At least one supported entity is required',422);$job=$this->repo->createJob(['connection_id'=>(int)$r['id'],'mode'=>$mode,'source_scope'=>$scope,'target_options'=>(array)($in['target_options']??$in['options']??[]),'created_by_user_id'=>$this->actorId()]);return JsonResponse::success('BITRIX24_JOB_CREATED','Job created',['job'=>$this->publicJob($job)],201);}
    public function getJob(array $p): JsonResponse {$r=$this->job((string)($p['public_id']??''));return$r instanceof JsonResponse?$r:JsonResponse::success('BITRIX24_JOB','OK',['job'=>$this->publicJob($r)]);}
    public function startJob(array $p): JsonResponse{return$this->changeJob((string)$p['public_id'],'queued','BITRIX24_JOB_QUEUED');}
    public function pauseJob(array $p): JsonResponse{return$this->changeJob((string)$p['public_id'],'pausing','BITRIX24_JOB_PAUSING');}
    public function resumeJob(array $p): JsonResponse{return$this->changeJob((string)$p['public_id'],'queued','BITRIX24_JOB_RESUMED');}
    public function cancelJob(array $p): JsonResponse{return$this->changeJob((string)$p['public_id'],'cancelling','BITRIX24_JOB_CANCELLING');}
    public function retryFailed(array $p): JsonResponse {$r=$this->job((string)$p['public_id']);if($r instanceof JsonResponse)return$r;$n=$this->repo->resetFailed((string)$p['public_id']);if($n===null)return JsonResponse::error('INVALID_JOB_STATUS','Only finished jobs can be retried',409);return JsonResponse::success('BITRIX24_JOB_RETRY_QUEUED','Failed items queued for retry',['reset_items'=>$n]);}
    public function rollbackJob(array $p): JsonResponse {$r=$this->job((string)$p['public_id']);if($r instanceof JsonResponse)return$r;if(empty($this->actor()['is_root']))return JsonResponse::error('ROOT_REQUIRED','Only a root user may roll back imported CRM data',403);try{$this->buildImportService((string)$p['public_id'])->rollback((string)$p['public_id'],$this->actor());return JsonResponse::success('BITRIX24_JOB_ROLLED_BACK','Job rolled back');}catch(\Throwable){return JsonResponse::error('BITRIX24_ROLLBACK_FAILED','Rollback failed; inspect the migration log',409);}}
    public function listJobItems(array $p): JsonResponse {$r=$this->job((string)$p['public_id']);if($r instanceof JsonResponse)return$r;$in=$this->container->get('request')->allInput();return JsonResponse::success('BITRIX24_JOB_ITEMS','OK',['items'=>$this->repo->items((int)$r['id'],!empty($in['status'])?(string)$in['status']:null,max(1,min(1000,(int)($in['limit']??200))))]);}
    public function listJobLogs(array $p): JsonResponse {$r=$this->job((string)$p['public_id']);return$r instanceof JsonResponse?$r:JsonResponse::success('BITRIX24_JOB_LOGS','OK',['items'=>$this->repo->logs((int)$r['id'])]);}
    public function getReport(array $p): JsonResponse {$r=$this->job((string)$p['public_id']);return$r instanceof JsonResponse?$r:JsonResponse::success('BITRIX24_JOB_REPORT','OK',['report'=>$this->repo->report((string)$p['public_id'])]);}
    private function changeJob(string $id,string $status,string $code): JsonResponse {$r=$this->job($id);if($r instanceof JsonResponse)return$r;$current=(string)($r['status']??'');$allowed=match($status){'queued'=>in_array($current,['draft','paused','failed','cancelled'],true),'pausing'=>in_array($current,['queued','running'],true),'cancelling'=>in_array($current,['draft','queued','running','paused','pausing'],true),default=>false};if(!$allowed)return JsonResponse::error('INVALID_JOB_STATUS','Job cannot be changed from '.$current,409);if($status==='queued'&&($r['mode']??'import')!=='dry_run'&&empty($this->actor()['is_root']))return JsonResponse::error('ROOT_REQUIRED','Only root may run a write migration',403);if(!$this->repo->requestStatus($id,$status))return JsonResponse::error('INVALID_JOB_STATUS','Job changed concurrently',409);return JsonResponse::success($code,'Job state updated');}
    private function client(array $r): Bitrix24Client {$c=new Bitrix24Client($this->repo);$c->setConnection($r);return$c;}
    private function buildImportService(string $jobPublicId): Bitrix24ImportService {$c=new Bitrix24Client($this->repo);$j=$this->repo->getJob($jobPublicId);$conn=$j?$this->repo->getConnectionById((int)$j['connection_id']):null;if(!$conn)throw new \RuntimeException('BITRIX24_CONNECTION_NOT_FOUND');$c->setConnection($conn);$crawler=new Bitrix24Crawler($c,$this->repo);$writer=new Bitrix24TargetWriter($this->container,$this->repo,$c);return new Bitrix24ImportService($this->repo,$crawler,$writer);}
    private function validPublicHttpsUrl(string $url): bool {$p=parse_url($url);if(!is_array($p)||($p['scheme']??'')!=='https'||trim((string)($p['host']??''))==='')return false;$host=strtolower((string)$p['host']);$ip=filter_var($host,FILTER_VALIDATE_IP);if($ip!==false)return filter_var($ip,FILTER_VALIDATE_IP,FILTER_FLAG_NO_PRIV_RANGE|FILTER_FLAG_NO_RES_RANGE)!==false;$resolved=gethostbynamel($host)?:[];if($resolved===[])return false;foreach($resolved as $address)if(filter_var($address,FILTER_VALIDATE_IP,FILTER_FLAG_NO_PRIV_RANGE|FILTER_FLAG_NO_RES_RANGE)===false)return false;return true;}
    private function validWebhook(string $url,string $portal): bool {$p=parse_url($url);$portalHost=strtolower((string)(parse_url($portal,PHP_URL_HOST)??''));return$this->validPublicHttpsUrl($url)&&strtolower((string)($p['host']??''))===$portalHost&&str_contains((string)($p['path']??''),'/rest/');}
}
