<?php
declare(strict_types=1);

/**
 * Runtime parity translations for keys that are shared by several pages.
 * Keep this supplemental layer separate from generated locale catalogs so a
 * catalog regeneration cannot reintroduce mixed-language UI strings.
 */
return [
    'ar-sa' => [
        'page' => ['dashboard' => 'الرئيسية', 'home' => 'الرئيسية', 'refresh' => 'تحديث', 'reset' => 'إعادة ضبط', 'apply' => 'تطبيق', 'all_statuses' => 'كل الحالات', 'all_priorities' => 'كل الأولويات'],
        'priority' => ['low' => 'منخفض', 'normal' => 'عادي', 'high' => 'مرتفع', 'urgent' => 'عاجل'],
        'projects' => ['breadcrumb' => 'المشاريع', 'page_subtitle' => 'قائمة المشاريع مع الحالات والعملاء والفرق والمواعيد النهائية.'],
        'counterparties' => ['page_subtitle' => 'دليل موحد للجهات: كيانات قانونية وأفراد ومنشآت فردية.'],
        'dashboard' => ['extra_open' => 'فتح', 'kpi_active_aria' => 'عرض المهام النشطة', 'kpi_overdue_aria' => 'عرض المهام المتأخرة', 'kpi_projects_aria' => 'عرض المشاريع النشطة', 'kpi_sla_aria' => 'عرض مهام SLA الأسبوعية', 'cycles_title' => 'الدورات النشطة', 'cycles_more' => 'كل الدورات', 'knowledge_title' => 'قاعدة المعرفة', 'knowledge_more' => 'فتح', 'widget_kpi' => 'مؤشرات KPI', 'widget_quick_actions' => 'إجراءات سريعة', 'widget_ai_digest' => 'ملخص الذكاء الاصطناعي', 'widget_today_tasks' => 'مهام اليوم', 'widget_risks' => 'المخاطر', 'widget_activity' => 'النشاط', 'widget_projects_overview' => 'نظرة عامة على المشاريع', 'widget_knowledge' => 'قاعدة المعرفة', 'widget_cycles' => 'الدورات النشطة', 'widget_reminders' => 'تذكيراتي', 'widget_my_day' => 'يومي', 'widget_sticky_notes' => 'الملاحظات اللاصقة', 'widget_worklog' => 'وقتي', 'widget_my_tasks' => 'مهامي', 'widget_approvals' => 'الموافقات المعلقة', 'widget_milestones' => 'المراحل القادمة', 'widget_favorites' => 'المفضلة', 'widget_intake' => 'الطلبات الواردة', 'widget_my_week' => 'أسبوعي', 'widget_mentions' => 'الإشارات إليّ', 'widget_unassigned' => 'مهام بلا منفذ', 'extra_insights_overdue' => 'متأخرة', 'extra_insights_total' => 'إجمالي الساعات', 'extra_insights_median' => 'الوسيط لكل مهمة', 'extra_insights_average' => 'المتوسط لكل مهمة', 'extra_insights_covered' => 'المهام ذات سجلات الوقت', 'extra_insights_no_project' => 'بدون مشروع', 'extra_insights_sessions' => 'الجلسات', 'extra_period' => 'الفترة', 'extra_period_7' => '7 أيام', 'extra_period_30' => '30 يوماً', 'extra_period_90' => '90 يوماً'],
        'tasks' => ['page_title' => 'المهام', 'page_subtitle' => 'التخطيط وإدارة المواعيد والعمل مع المهام الرئيسية والفرعية.', 'view_list' => 'قائمة', 'view_tree' => 'شجرة', 'view_cards' => 'بطاقات', 'ai_priority' => 'أولوية الذكاء الاصطناعي', 'kanban_link' => 'كانبان', 'filter_search' => 'بحث', 'filter_status' => 'الحالة', 'filter_assignee' => 'المسؤول', 'filter_manager' => 'المدير', 'filter_project' => 'المشروع', 'filter_client' => 'العميل', 'filter_cycle' => 'الدورة', 'filter_tag' => 'الوسم', 'filter_hide_done' => 'إخفاء المكتملة', 'filter_include_archived_projects' => 'تضمين المشاريع المؤرشفة', 'filter_overdue' => 'متأخرة', 'filter_today' => 'اليوم', 'filter_week' => 'هذا الأسبوع', 'filter_reset' => 'إعادة تعيين', 'btn_create_task' => 'إنشاء مهمة', 'th_task' => 'المهمة', 'th_project' => 'المشروع', 'th_due' => 'الموعد النهائي', 'th_status' => 'الحالة', 'th_priority' => 'الأولوية', 'th_actions' => 'الإجراءات', 'subtitle' => 'التخطيط وإدارة المواعيد والعمل مع المهام الرئيسية والفرعية.', 'view_toggle_aria' => 'عرض قائمة المهام', 'ai_priority_title' => 'إنشاء ترتيب ذكي للمهام حسب المخاطر والإلحاح', 'ai_priority_reset_title' => 'استعادة ترتيب المهام العادي', 'filters_aria' => 'مرشحات المهام', 'filter_search_placeholder' => 'اسم المهمة أو الوصف أو الرمز', 'filter_all_statuses' => 'كل الحالات', 'filter_assignee_placeholder' => 'المسؤول', 'filter_manager_placeholder' => 'المدير', 'filter_all_projects' => 'كل المشاريع', 'filter_all_clients' => 'كل العملاء', 'filter_all_cycles' => 'كل الدورات', 'filter_all_tags' => 'كل الوسوم', 'filter_include_archived_projects_title' => 'إظهار مهام المشاريع المؤرشفة. مخفية افتراضياً مثل عدادات لوحة التحكم.', 'result_summary' => 'عرض 0 من 0 مهمة', 'bulk_aria' => 'إجراءات جماعية', 'bulk_selected' => 'المهام المحددة: ', 'bulk_status_aria' => 'تغيير الحالة', 'bulk_status_placeholder' => 'الحالة...', 'bulk_priority_aria' => 'تغيير الأولوية', 'bulk_priority_placeholder' => 'الأولوية...', 'select_all_aria' => 'تحديد جميع المهام', 'global_search_placeholder' => 'البحث في المهام', 'global_search_aria' => 'البحث العام في المهام', 'notifications_aria' => 'الإشعارات', 'sidebar_toggle_aria' => 'فتح القائمة'],
        'analytics' => ['note_ai_explanation' => 'يشرح الذكاء الاصطناعي مؤشرات الأداء والمخاطر ولا يستبدل المقاييس الرقمية.', 'btn_ai_kpi' => 'شرح المؤشرات', 'ai_summary_empty' => 'اضغط «شرح المؤشرات» للحصول على تفسير للمقاييس الحالية.', 'ai_facts_label' => 'الحقائق / المؤشرات'],
        'profile' => ['field_email' => 'البريد الإلكتروني', 'setting_email_critical' => 'البريد للمهام الحرجة', 'setting_push_comments' => 'إشعارات التعليقات'],
        'notifications' => ['section_push' => 'إشعارات الدفع', 'label_push_enable' => 'تفعيل إشعارات الدفع', 'section_sound' => 'الصوت وساعات الهدوء', 'label_quiet_hours_enable' => 'استخدام ساعات الهدوء', 'hint_security' => 'تبقى إشعارات الأمان داخل التطبيق دائمًا لمنع فقدان الأحداث الحرجة.'],

        'js' => ['br1' => ['quick_client_btn' => '+ إنشاء', 'quick_client_btn_aria' => 'إنشاء عميل', 'quick_project_btn' => '+ إنشاء', 'quick_project_btn_aria' => 'إنشاء مشروع'], 'pab' => ['create_project' => 'إنشاء مشروع', 'priority_low' => 'منخفض', 'priority_normal' => 'عادي', 'priority_high' => 'مرتفع', 'priority_urgent' => 'عاجل', 'status_active' => 'نشطة', 'active_prefix' => 'نشطة', 'overdue_prefix' => 'متأخرة', 'time_logged_prefix' => 'الوقت المسجل', 'min' => 'دقيقة'], 'modal' => ['create_project' => 'إنشاء مشروع', 'quick_client_create' => 'إنشاء عميل', 'cancel' => 'إلغاء', 'create' => 'إنشاء', 'label_title' => 'عنوان', 'label_description' => 'الوصف', 'label_status' => 'الحالة', 'status_new' => 'جديد', 'label_priority' => 'الأولوية', 'priority_normal' => 'عادي', 'priority_low' => 'منخفض', 'priority_high' => 'مرتفع', 'priority_urgent' => 'عاجل', 'label_assignee' => 'المسند إليه', 'no_assignee' => 'غير مسند', 'label_start' => 'تاريخ البدء', 'label_due' => 'الموعد النهائي', 'label_end' => 'الإكمال المخطط', 'label_tags' => 'الوسوم', 'tags_hint' => 'اختر وسوماً متعددة.', 'placeholder_desc' => 'السياق والخطوات والمخاطر ومعايير القبول']],
    ],
    'ru-ru' => [
        'page' => ['dashboard' => 'Главная', 'home' => 'Главная', 'refresh' => 'Обновить', 'reset' => 'Сбросить', 'apply' => 'Применить'],
        'projects' => ['breadcrumb' => 'Проекты', 'page_subtitle' => 'Список проектов со статусами, клиентами, командами и сроками.'],
        'counterparties' => ['page_subtitle' => 'Единый справочник контрагентов: юридические лица, физические лица и ИП.'],
        'analytics' => ['note_ai_explanation' => 'ИИ объясняет KPI и риски, но не заменяет числовые метрики.', 'btn_ai_kpi' => 'Пояснить KPI', 'ai_summary_empty' => 'Нажмите «Пояснить KPI», чтобы получить объяснение текущих метрик.', 'ai_facts_label' => 'Факты / KPI'],
        'profile' => ['field_email' => 'Электронная почта', 'setting_email_critical' => 'Почта о критичных задачах', 'setting_push_comments' => 'Push для комментариев'],
        'notifications' => ['section_push' => 'Push-уведомления', 'label_push_enable' => 'Включить push-уведомления', 'section_sound' => 'Звук и часы тишины', 'label_quiet_hours_enable' => 'Использовать часы тишины', 'hint_security' => 'Уведомления безопасности всегда остаются внутри приложения, чтобы не пропустить критичные события.'],
    ],
    'en-gb' => [
        'page' => ['dashboard' => 'Home', 'home' => 'Home', 'refresh' => 'Refresh', 'reset' => 'Reset', 'apply' => 'Apply'],
        'projects' => ['breadcrumb' => 'Projects', 'page_subtitle' => 'List of projects with statuses, clients, teams and deadlines.'],
        'counterparties' => ['page_subtitle' => 'Unified counterparty directory: legal entities, individuals, sole proprietors.'],
        'analytics' => ['note_ai_explanation' => 'AI explains KPIs and risks but does not replace numeric metrics.', 'btn_ai_kpi' => 'Explain KPIs', 'ai_summary_empty' => 'Click “Explain KPIs” to get an explanation of current metrics.', 'ai_facts_label' => 'Facts / KPIs'],
        'profile' => ['field_email' => 'Email', 'setting_email_critical' => 'Email for critical tasks', 'setting_push_comments' => 'Push for comments'],
        'notifications' => ['section_push' => 'Push notifications', 'label_push_enable' => 'Enable push notifications', 'section_sound' => 'Sound & quiet hours', 'label_quiet_hours_enable' => 'Use quiet hours', 'hint_security' => 'Security notifications always remain in-app to prevent missing critical events.'],
    ],
    'de-de' => [
        'page' => ['dashboard' => 'Startseite', 'home' => 'Startseite', 'refresh' => 'Aktualisieren', 'reset' => 'Zurücksetzen', 'apply' => 'Anwenden', 'all_statuses' => 'Alle Statuswerte', 'all_priorities' => 'Alle Prioritäten'],
        'priority' => ['low' => 'Niedrig', 'normal' => 'Normal', 'high' => 'Hoch', 'urgent' => 'Dringend'],
        'projects' => ['breadcrumb' => 'Projekte', 'page_subtitle' => 'Liste der Projekte mit Status, Kunden, Teams und Fristen.'],
        'counterparties' => ['page_subtitle' => 'Einheitliches Verzeichnis der Geschäftspartner: Unternehmen, Personen und Einzelunternehmen.'],
        'calendar' => ['btn_day' => 'Tag', 'btn_week' => 'Woche', 'btn_month' => 'Monat', 'btn_create_event' => 'Ereignis erstellen', 'btn_today' => 'Kalender', 'loading_calendar' => 'Kalender wird geladen...', 'loading_events' => 'Ereignisse werden geladen...', 'section_events' => 'Ereignisse des Zeitraums', 'note_events' => 'Kommende Ereignisse im ausgewählten Zeitraum.', 'section_ai_plan' => 'KI-Tagesblöcke', 'note_ai_plan' => 'Vorschau des Tagesplans mit manueller Bestätigung vor der Anwendung.', 'ai_plan_empty_title' => 'Noch kein Plan erstellt', 'ai_plan_empty_text' => 'Klicken Sie auf „Vorschau erstellen“, um einen KI-Vorschlag zu erhalten.', 'ai_plan_slots_hint' => 'Zeitfenster erscheinen nach der Erstellung.', 'btn_ai_generate' => 'Vorschau erstellen', 'btn_ai_apply' => 'Ausgewählte Zeitfenster anwenden', 'page_title' => 'Kalender', 'subtitle' => 'Ereignisse, Besprechungen und Teamfristen in der Kalenderansicht.', 'period_free' => 'In diesem Zeitraum frei', 'period_free_desc' => 'Für den ausgewählten Zeitraum gibt es keine Besprechungen, Fristen oder Ereignisse. Fügen Sie unten ein Ereignis hinzu.', 'ai_day_plan_title' => 'KI-Tagesblöcke', 'ai_plan_not_generated_title' => 'Noch kein Plan erstellt', 'ai_plan_not_generated_body' => 'Klicken Sie auf „Vorschau erstellen“, um einen KI-Vorschlag zu erhalten.', 'btn_ai_generate' => 'Vorschau erstellen', 'btn_ai_apply' => 'Ausgewählte Zeitfenster anwenden', 'note_ai_plan' => 'Vorschau des Tagesplans mit manueller Bestätigung vor der Anwendung.', 'btn_prev_aria' => 'Vorheriger Zeitraum', 'btn_next_aria' => 'Nächster Zeitraum', 'jump_current_period' => 'Zum aktuellen Zeitraum', 'view_day' => 'Tag', 'view_week' => 'Woche', 'view_month' => 'Monat', 'btn_prev_title' => 'Vorheriger Zeitraum', 'btn_next_title' => 'Nächster Zeitraum', 'btn_today_aria' => 'Zum aktuellen Zeitraum', 'btn_today_title' => 'Zum aktuellen Zeitraum', 'link_my_day' => 'Mein Tag öffnen'],
        'teams' => ['btn_create' => 'Erstellen'], 'organizations' => ['search' => 'Suchen', 'th_actions' => 'Aktionen'],
        'knowledge' => ['page_title' => 'Wissensdatenbank', 'subtitle' => 'Richtlinien, Anleitungen, FAQ und Projektwissen für das Team.'],
        'chat' => ['search_label' => 'Chats durchsuchen'],
        'admin_settings' => ['link_admin' => 'Administration', 'refresh_btn' => 'Aktualisieren', 'tab_all' => 'Alle Einstellungen', 'tab_system' => 'System & Cache', 'tab_tasks' => 'Aufgabenrichtlinien', 'tab_finance' => 'Finanzen', 'tab_retention' => 'Aufbewahrung & Audit', 'tab_sysinfo' => 'Umgebung'],

        'js' => ['br1' => ['quick_client_btn' => '+ Erstellen', 'quick_client_btn_aria' => 'Kunde erstellen', 'quick_project_btn' => '+ Erstellen', 'quick_project_btn_aria' => 'Projekt erstellen'], 'pab' => ['period_free' => 'Zeitraum ist frei', 'period_free_desc' => 'Keine Besprechungen, Fristen oder Ereignisse im ausgewählten Zeitraum. Fügen Sie unten schnell ein Ereignis hinzu.', 'create_event' => 'Ereignis erstellen', 'cannot_create_past' => 'Ereignis in der Vergangenheit nicht möglich', 'create_project' => 'Projekt erstellen', 'priority_low' => 'Niedrig', 'priority_normal' => 'Normal', 'priority_high' => 'Hoch', 'priority_urgent' => 'Dringend', 'status_active' => 'Aktiv', 'active_prefix' => 'Aktiv', 'overdue_prefix' => 'Überfällig', 'time_logged_prefix' => 'Erfasste Zeit', 'min' => 'Min.'], 'modal' => ['create_project' => 'Projekt erstellen', 'quick_client_create' => 'Kunde erstellen', 'cancel' => 'Abbrechen', 'create' => 'Erstellen', 'label_title' => 'Titel', 'label_description' => 'Beschreibung', 'label_status' => 'Status', 'status_new' => 'Neu', 'label_priority' => 'Priorität', 'priority_normal' => 'Normal', 'priority_low' => 'Niedrig', 'priority_high' => 'Hoch', 'priority_urgent' => 'Dringend', 'label_assignee' => 'Zugewiesener', 'no_assignee' => 'Nicht zugewiesen', 'label_start' => 'Startdatum', 'label_due' => 'Deadline', 'label_end' => 'Geplante Fertigstellung', 'label_tags' => 'Tags', 'tags_hint' => 'Mehrere Tags auswählen.', 'placeholder_desc' => 'Kontext, Schritte, Risiken, Annahmekriterien']],
    ],
    'es-es' => [
        'page' => ['dashboard' => 'Inicio', 'home' => 'Inicio', 'refresh' => 'Actualizar', 'reset' => 'Restablecer', 'apply' => 'Aplicar', 'all_statuses' => 'Todos los estados', 'all_priorities' => 'Todas las prioridades'],
        'priority' => ['low' => 'Baja', 'normal' => 'Normal', 'high' => 'Alta', 'urgent' => 'Urgente'],
        'projects' => ['breadcrumb' => 'Proyectos', 'page_subtitle' => 'Lista de proyectos con estados, clientes, equipos y plazos.'],
        'counterparties' => ['page_subtitle' => 'Directorio unificado de contrapartes: personas jurídicas, personas físicas y autónomos.'],
        'calendar' => ['btn_day' => 'Día', 'btn_week' => 'Semana', 'btn_month' => 'Mes', 'btn_create_event' => 'Crear evento', 'btn_today' => 'Calendario', 'loading_calendar' => 'Cargando calendario...', 'loading_events' => 'Cargando eventos...', 'section_events' => 'Eventos del periodo', 'note_events' => 'Próximos eventos del intervalo seleccionado.', 'section_ai_plan' => 'Bloques del día con IA', 'note_ai_plan' => 'Vista previa del plan diario con confirmación manual antes de aplicarlo.', 'ai_plan_empty_title' => 'No se ha generado ningún plan', 'ai_plan_empty_text' => 'Haz clic en «Generar vista previa» para obtener una sugerencia de IA.', 'ai_plan_slots_hint' => 'Los bloques aparecerán después de generarlos.', 'btn_ai_generate' => 'Generar vista previa', 'btn_ai_apply' => 'Aplicar bloques seleccionados', 'page_title' => 'Calendario', 'subtitle' => 'Eventos, reuniones y plazos del equipo en una vista de calendario.', 'period_free' => 'Periodo libre', 'period_free_desc' => 'No hay reuniones, plazos ni eventos en el periodo seleccionado. Añade un evento con el botón inferior.', 'ai_day_plan_title' => 'Bloques del día con IA', 'ai_plan_not_generated_title' => 'No se ha generado ningún plan', 'ai_plan_not_generated_body' => 'Haz clic en «Generar vista previa» para obtener una sugerencia de IA.', 'btn_ai_generate' => 'Generar vista previa', 'btn_ai_apply' => 'Aplicar bloques seleccionados', 'note_ai_plan' => 'Vista previa del plan diario con confirmación manual antes de aplicarlo.', 'btn_prev_aria' => 'Periodo anterior', 'btn_next_aria' => 'Periodo siguiente', 'jump_current_period' => 'Ir al periodo actual', 'view_day' => 'Día', 'view_week' => 'Semana', 'view_month' => 'Mes', 'btn_prev_title' => 'Periodo anterior', 'btn_next_title' => 'Periodo siguiente', 'btn_today_aria' => 'Ir al periodo actual', 'btn_today_title' => 'Ir al periodo actual', 'link_my_day' => 'Abrir Mi Día'],
        'teams' => ['btn_create' => 'Crear'], 'organizations' => ['search' => 'Buscar', 'th_actions' => 'Acciones'],
        'knowledge' => ['page_title' => 'Base de conocimiento', 'subtitle' => 'Políticas, instrucciones, FAQ y conocimiento de proyectos para el equipo.'],
        'chat' => ['search_label' => 'Buscar chats'],
        'admin_settings' => ['link_admin' => 'Administración', 'refresh_btn' => 'Actualizar', 'tab_all' => 'Todos los ajustes', 'tab_system' => 'Sistema y caché', 'tab_tasks' => 'Políticas de tareas', 'tab_finance' => 'Finanzas', 'tab_retention' => 'Retención y auditoría', 'tab_sysinfo' => 'Entorno'],

        'js' => ['br1' => ['quick_client_btn' => '+ Crear', 'quick_client_btn_aria' => 'Crear cliente', 'quick_project_btn' => '+ Crear', 'quick_project_btn_aria' => 'Crear proyecto'], 'pab' => ['period_free' => 'Periodo libre', 'period_free_desc' => 'No hay reuniones, plazos ni eventos en el periodo seleccionado. Añade rápidamente un evento con el botón inferior.', 'create_event' => 'Crear evento', 'cannot_create_past' => 'No se puede crear un evento en el pasado', 'create_project' => 'Crear proyecto', 'priority_low' => 'Baja', 'priority_normal' => 'Normal', 'priority_high' => 'Alta', 'priority_urgent' => 'Urgente', 'status_active' => 'Activas', 'active_prefix' => 'Activas', 'overdue_prefix' => 'Atrasadas', 'time_logged_prefix' => 'Tiempo registrado', 'min' => 'min'], 'modal' => ['create_project' => 'Crear proyecto', 'quick_client_create' => 'Crear cliente', 'cancel' => 'Cancelar', 'create' => 'Crear', 'label_title' => 'Título', 'label_description' => 'Descripción', 'label_status' => 'Estado', 'status_new' => 'Nuevo', 'label_priority' => 'Prioridad', 'priority_normal' => 'Normal', 'priority_low' => 'Baja', 'priority_high' => 'Alta', 'priority_urgent' => 'Urgente', 'label_assignee' => 'Asignado', 'no_assignee' => 'Sin asignar', 'label_start' => 'Fecha de inicio', 'label_due' => 'Fecha límite', 'label_end' => 'Finalización prevista', 'label_tags' => 'Etiquetas', 'tags_hint' => 'Selecciona varias etiquetas.', 'placeholder_desc' => 'Contexto, pasos, riesgos y criterios de aceptación']],
    ],
    'fr-fr' => [
        'page' => ['dashboard' => 'Accueil', 'home' => 'Accueil', 'refresh' => 'Actualiser', 'reset' => 'Réinitialiser', 'apply' => 'Appliquer', 'all_statuses' => 'Tous les statuts', 'all_priorities' => 'Toutes les priorités'],
        'priority' => ['low' => 'Basse', 'normal' => 'Normale', 'high' => 'Haute', 'urgent' => 'Urgente'],
        'projects' => ['breadcrumb' => 'Projets', 'page_subtitle' => 'Liste des projets avec statuts, clients, équipes et échéances.'],
        'counterparties' => ['page_subtitle' => 'Répertoire unifié des contreparties : personnes morales, particuliers et entrepreneurs individuels.'],
        'calendar' => ['btn_day' => 'Jour', 'btn_week' => 'Semaine', 'btn_month' => 'Mois', 'btn_create_event' => 'Créer un événement', 'btn_today' => 'Calendrier', 'loading_calendar' => 'Chargement du calendrier...', 'loading_events' => 'Chargement des événements...', 'section_events' => 'Événements de la période', 'note_events' => 'Événements à venir dans la période sélectionnée.', 'section_ai_plan' => 'Blocs de la journée IA', 'note_ai_plan' => 'Aperçu du plan de la journée avec confirmation manuelle avant application.', 'ai_plan_empty_title' => 'Aucun plan généré', 'ai_plan_empty_text' => 'Cliquez sur « Générer l’aperçu » pour obtenir une suggestion IA.', 'ai_plan_slots_hint' => 'Les créneaux apparaîtront après la génération.', 'btn_ai_generate' => 'Générer l’aperçu', 'btn_ai_apply' => 'Appliquer les créneaux sélectionnés', 'page_title' => 'Calendrier', 'subtitle' => 'Événements, réunions et échéances de l’équipe dans une vue calendrier.', 'period_free' => 'Période libre', 'period_free_desc' => 'Aucune réunion, échéance ou événement dans la période sélectionnée. Ajoutez un événement avec le bouton ci-dessous.', 'ai_day_plan_title' => 'Blocs de la journée IA', 'ai_plan_not_generated_title' => 'Aucun plan généré', 'ai_plan_not_generated_body' => 'Cliquez sur « Générer l’aperçu » pour obtenir une suggestion IA.', 'btn_ai_generate' => 'Générer l’aperçu', 'btn_ai_apply' => 'Appliquer les créneaux sélectionnés', 'note_ai_plan' => 'Aperçu du plan de la journée avec confirmation manuelle avant application.', 'btn_prev_aria' => 'Période précédente', 'btn_next_aria' => 'Période suivante', 'jump_current_period' => 'Aller à la période en cours', 'view_day' => 'Jour', 'view_week' => 'Semaine', 'view_month' => 'Mois', 'btn_prev_title' => 'Période précédente', 'btn_next_title' => 'Période suivante', 'btn_today_aria' => 'Aller à la période en cours', 'btn_today_title' => 'Aller à la période en cours', 'link_my_day' => 'Ouvrir Ma journée'],
        'teams' => ['btn_create' => 'Créer'], 'organizations' => ['search' => 'Rechercher', 'th_actions' => 'Actions'],
        'knowledge' => ['page_title' => 'Base de connaissances', 'subtitle' => 'Politiques, instructions, FAQ et connaissances des projets pour l’équipe.'],
        'chat' => ['search_label' => 'Rechercher dans les discussions'],
        'admin_settings' => ['link_admin' => 'Administration', 'refresh_btn' => 'Actualiser', 'tab_all' => 'Tous les paramètres', 'tab_system' => 'Système et cache', 'tab_tasks' => 'Politiques des tâches', 'tab_finance' => 'Finance', 'tab_retention' => 'Rétention et audit', 'tab_sysinfo' => 'Environnement'],

        'js' => ['br1' => ['quick_client_btn' => '+ Créer', 'quick_client_btn_aria' => 'Créer un client', 'quick_project_btn' => '+ Créer', 'quick_project_btn_aria' => 'Créer un projet'], 'pab' => ['period_free' => 'Période libre', 'period_free_desc' => 'Aucune réunion, échéance ou événement dans la période sélectionnée. Ajoutez rapidement un événement avec le bouton ci-dessous.', 'create_event' => 'Créer un événement', 'cannot_create_past' => 'Impossible de créer un événement dans le passé', 'create_project' => 'Créer un projet', 'priority_low' => 'Basse', 'priority_normal' => 'Normale', 'priority_high' => 'Haute', 'priority_urgent' => 'Urgente', 'status_active' => 'Actives', 'active_prefix' => 'Actives', 'overdue_prefix' => 'En retard', 'time_logged_prefix' => 'Temps enregistré', 'min' => 'min'], 'modal' => ['create_project' => 'Créer un projet', 'quick_client_create' => 'Créer un client', 'cancel' => 'Annuler', 'create' => 'Créer', 'label_title' => 'Titre', 'label_description' => 'Description', 'label_status' => 'Statut', 'status_new' => 'Nouveau', 'label_priority' => 'Priorité', 'priority_normal' => 'Normale', 'priority_low' => 'Basse', 'priority_high' => 'Haute', 'priority_urgent' => 'Urgente', 'label_assignee' => 'Assigné', 'no_assignee' => 'Non assigné', 'label_start' => 'Date de début', 'label_due' => 'Échéance', 'label_end' => 'Achèvement prévu', 'label_tags' => 'Étiquettes', 'tags_hint' => 'Sélectionnez plusieurs étiquettes.', 'placeholder_desc' => 'Contexte, étapes, risques et critères d’acceptation']],
    ],
    'pt-br' => [
        'page' => ['dashboard' => 'Início', 'home' => 'Início', 'refresh' => 'Atualizar', 'reset' => 'Redefinir', 'apply' => 'Aplicar', 'all_statuses' => 'Todos os status', 'all_priorities' => 'Todas as prioridades'],
        'priority' => ['low' => 'Baixa', 'normal' => 'Normal', 'high' => 'Alta', 'urgent' => 'Urgente'],
        'projects' => ['breadcrumb' => 'Projetos', 'page_subtitle' => 'Lista de projetos com status, clientes, equipes e prazos.'],
        'counterparties' => ['page_subtitle' => 'Diretório unificado de contrapartes: pessoas jurídicas, pessoas físicas e empresários individuais.'],
        'calendar' => ['btn_day' => 'Dia', 'btn_week' => 'Semana', 'btn_month' => 'Mês', 'btn_create_event' => 'Criar evento', 'btn_today' => 'Calendário', 'loading_calendar' => 'Carregando calendário...', 'loading_events' => 'Carregando eventos...', 'section_events' => 'Eventos do período', 'note_events' => 'Próximos eventos no intervalo selecionado.', 'section_ai_plan' => 'Blocos do dia com IA', 'note_ai_plan' => 'Prévia do plano diário com confirmação manual antes de aplicar.', 'ai_plan_empty_title' => 'Nenhum plano gerado', 'ai_plan_empty_text' => 'Clique em “Gerar prévia” para receber uma sugestão da IA.', 'ai_plan_slots_hint' => 'Os horários aparecerão após a geração.', 'btn_ai_generate' => 'Gerar prévia', 'btn_ai_apply' => 'Aplicar horários selecionados', 'page_title' => 'Calendário', 'subtitle' => 'Eventos, reuniões e prazos da equipe em uma visão de calendário.', 'period_free' => 'Período livre', 'period_free_desc' => 'Não há reuniões, prazos ou eventos no período selecionado. Adicione um evento usando o botão abaixo.', 'ai_day_plan_title' => 'Blocos do dia com IA', 'ai_plan_not_generated_title' => 'Nenhum plano gerado', 'ai_plan_not_generated_body' => 'Clique em “Gerar prévia” para receber uma sugestão da IA.', 'btn_ai_generate' => 'Gerar prévia', 'btn_ai_apply' => 'Aplicar horários selecionados', 'note_ai_plan' => 'Prévia do plano diário com confirmação manual antes de aplicar.', 'btn_prev_aria' => 'Período anterior', 'btn_next_aria' => 'Próximo período', 'jump_current_period' => 'Ir para o período atual', 'view_day' => 'Dia', 'view_week' => 'Semana', 'view_month' => 'Mês', 'btn_prev_title' => 'Período anterior', 'btn_next_title' => 'Próximo período', 'btn_today_aria' => 'Ir para o período atual', 'btn_today_title' => 'Ir para o período atual', 'link_my_day' => 'Abrir Meu Dia'],
        'teams' => ['btn_create' => 'Criar'], 'organizations' => ['search' => 'Buscar', 'th_actions' => 'Ações'],
        'knowledge' => ['page_title' => 'Base de conhecimento', 'subtitle' => 'Políticas, instruções, FAQ e conhecimento dos projetos para a equipe.'],
        'chat' => ['search_label' => 'Pesquisar chats'],
        'admin_settings' => ['link_admin' => 'Administração', 'refresh_btn' => 'Atualizar', 'tab_all' => 'Todas as configurações', 'tab_system' => 'Sistema e cache', 'tab_tasks' => 'Políticas de tarefas', 'tab_finance' => 'Finanças', 'tab_retention' => 'Retenção e auditoria', 'tab_sysinfo' => 'Ambiente'],

        'js' => ['br1' => ['quick_client_btn' => '+ Criar', 'quick_client_btn_aria' => 'Criar cliente', 'quick_project_btn' => '+ Criar', 'quick_project_btn_aria' => 'Criar projeto'], 'pab' => ['period_free' => 'Período livre', 'period_free_desc' => 'Não há reuniões, prazos ou eventos no período selecionado. Adicione rapidamente um evento com o botão abaixo.', 'create_event' => 'Criar evento', 'cannot_create_past' => 'Não é possível criar um evento no passado', 'create_project' => 'Criar projeto', 'priority_low' => 'Baixa', 'priority_normal' => 'Normal', 'priority_high' => 'Alta', 'priority_urgent' => 'Urgente', 'status_active' => 'Ativos', 'active_prefix' => 'Ativos', 'overdue_prefix' => 'Atrasados', 'time_logged_prefix' => 'Tempo registrado', 'min' => 'min'], 'modal' => ['create_project' => 'Criar projeto', 'quick_client_create' => 'Criar cliente', 'cancel' => 'Cancelar', 'create' => 'Criar', 'label_title' => 'Título', 'label_description' => 'Descrição', 'label_status' => 'Status', 'status_new' => 'Novo', 'label_priority' => 'Prioridade', 'priority_normal' => 'Normal', 'priority_low' => 'Baixa', 'priority_high' => 'Alta', 'priority_urgent' => 'Urgente', 'label_assignee' => 'Responsável', 'no_assignee' => 'Não atribuído', 'label_start' => 'Data de início', 'label_due' => 'Prazo', 'label_end' => 'Conclusão planejada', 'label_tags' => 'Tags', 'tags_hint' => 'Selecione várias tags.', 'placeholder_desc' => 'Contexto, etapas, riscos e critérios de aceitação']],
    ],
    'zh-cn' => [
        'page' => ['dashboard' => '首页', 'home' => '首页', 'refresh' => '刷新', 'reset' => '重置', 'apply' => '应用', 'all_statuses' => '所有状态', 'all_priorities' => '所有优先级'],
        'priority' => ['low' => '低', 'normal' => '普通', 'high' => '高', 'urgent' => '紧急'],
        'projects' => ['breadcrumb' => '项目', 'page_subtitle' => '包含状态、客户、团队和截止日期的项目列表。'],
        'counterparties' => ['page_subtitle' => '统一的往来单位目录：法人、个人和个体经营者。'],
        'tasks' => ['filter_cycle' => '周期', 'th_key' => '编号'],
        'calendar' => ['btn_day' => '日', 'btn_week' => '周', 'btn_month' => '月', 'btn_create_event' => '创建事件', 'btn_today' => '日历', 'loading_calendar' => '正在加载日历...', 'section_events' => '期间事件', 'note_events' => '所选时间范围内的即将发生事件。', 'section_ai_plan' => 'AI 日程区块', 'note_ai_plan' => '应用前先手动确认日程预览。', 'ai_plan_empty_title' => '尚未生成计划', 'ai_plan_empty_text' => '点击“生成预览”获取 AI 建议。', 'ai_plan_slots_hint' => '生成后将显示时间段。', 'btn_ai_generate' => '生成预览', 'btn_ai_apply' => '应用所选时间段'],
        'analytics' => ['note_ai_explanation' => 'AI 解读 KPI 和风险，但不能替代数值指标。', 'btn_ai_kpi' => '解读 KPI', 'ai_summary_empty' => '点击“解读 KPI”获取当前指标的解读。', 'ai_facts_label' => '事实 / KPI', 'ai_facts_empty' => '暂无事实。', 'ai_risks_label' => '风险与问题', 'ai_risks_empty' => '暂无风险。'],
        'organizations' => ['search' => '搜索', 'th_actions' => '操作'], 'chat' => ['search_label' => '搜索聊天'],
        'admin_settings' => ['refresh_btn' => '刷新', 'tab_all' => '所有设置', 'tab_system' => '系统和缓存', 'tab_tasks' => '任务策略', 'tab_finance' => '财务', 'tab_retention' => '保留与审计', 'tab_sysinfo' => '环境'],

        'js' => ['br1' => ['quick_client_btn' => '+ 创建', 'quick_client_btn_aria' => '创建客户', 'quick_project_btn' => '+ 创建', 'quick_project_btn_aria' => '创建项目'], 'pab' => ['create_project' => '创建项目', 'priority_low' => '低', 'priority_normal' => '普通', 'priority_high' => '高', 'priority_urgent' => '紧急', 'status_active' => '活跃', 'active_prefix' => '活跃', 'overdue_prefix' => '逾期', 'time_logged_prefix' => '已记录时间', 'min' => '分钟'], 'modal' => ['create_project' => '创建项目', 'quick_client_create' => '创建客户', 'cancel' => '取消', 'create' => '创建', 'label_title' => '标题', 'label_description' => '描述', 'label_status' => '状态', 'status_new' => '新建', 'label_priority' => '优先级', 'priority_normal' => '普通', 'priority_low' => '低', 'priority_high' => '高', 'priority_urgent' => '紧急', 'label_assignee' => '负责人', 'no_assignee' => '未分配', 'label_start' => '开始日期', 'label_due' => '截止日期', 'label_end' => '计划完成', 'label_tags' => '标签', 'tags_hint' => '可多选标签。', 'placeholder_desc' => '背景、步骤、风险、验收标准']],
    ],
];
