<body data-page="module-toggl-migration" data-protected="1">
<div class="crm-app"><aside class="crm-sidebar"><div class="crm-brand"><span class="crm-brand-mark"></span> <?= htmlspecialchars($t('app.name', 'TropaTT'), ENT_QUOTES, 'UTF-8') ?></div><nav class="nav flex-column crm-nav"></nav></aside>
<div class="crm-main-wrap"><header class="crm-topbar py-2"><div class="container-fluid"></div></header>
<main class="crm-content crm-admin-page"><div class="crm-page-head"><div><ol class="breadcrumb mb-1"><li class="breadcrumb-item"><a href="index.php?route=admin"><?= htmlspecialchars($t('nav.admin', 'Администрирование'), ENT_QUOTES, 'UTF-8') ?></a></li><li class="breadcrumb-item active">Миграция из Toggl Track</li></ol><h1 class="crm-page-title">Миграция из Toggl Track</h1><p class="crm-subtitle">Перенос рабочих пространств, клиентов, проектов, задач, пользователей и учёта времени в TropaTT.</p></div></div>
<div id="togglMigrationApp" class="toggl-migration-grid">
<section class="crm-card toggl-panel"><div class="crm-card-header d-flex justify-content-between align-items-center"><h5 class="mb-0">Подключение Toggl</h5><button class="btn crm-btn-primary btn-sm" id="togglAddConnection"><i class="fa-solid fa-plus"></i> Добавить</button></div><div class="crm-card-body"><div id="togglConnections" class="toggl-state">Загрузка подключений…</div></div></section>
<section class="crm-card toggl-panel"><div class="crm-card-header d-flex justify-content-between align-items-center"><h5 class="mb-0">Источник</h5><button class="btn crm-btn-secondary btn-sm" id="togglDiscover" disabled><i class="fa-solid fa-rotate"></i> Обновить</button></div><div class="crm-card-body"><div id="togglWorkspaces" class="toggl-state">Выберите подключение.</div><div id="togglProjects" class="mt-3"></div><div id="togglSourceInfo" class="small text-muted mt-3"></div></div></section>
<section class="crm-card toggl-panel"><div class="crm-card-header"><h5 class="mb-0">Настройки миграции</h5></div><div class="crm-card-body"><label class="form-label" for="togglMode">Режим</label><select id="togglMode" class="form-select mb-3"><option value="import">Однократный импорт</option><option value="sync">Синхронизация</option><option value="dry_run">Предпросмотр без записи</option></select><div class="row g-2 mb-3"><div class="col-6"><label class="form-label" for="togglFrom">Записи с</label><input id="togglFrom" class="form-control" type="date" required></div><div class="col-6"><label class="form-label" for="togglTo">Записи по</label><input id="togglTo" class="form-control" type="date" required></div></div><div class="form-text mb-3">Диапазон обязателен: Reports API Toggl ограничивает объём отчёта, поэтому модуль загружает его окнами по 31 дню. Полный импорт time entries для нескольких пользователей запускайте от root: штатный WorklogService разрешает non-root только собственные записи.</div><div class="form-check mb-2"><input class="form-check-input" type="checkbox" id="togglArchived"><label class="form-check-label" for="togglArchived">Включать архивные проекты и задачи</label></div><div class="form-check mb-3"><input class="form-check-input" type="checkbox" id="togglMaxTasks"><label class="form-check-label" for="togglMaxTasks">Ограничить задачи для пробного запуска</label></div><input id="togglMaxTasksValue" class="form-control mb-3 d-none" type="number" min="1" placeholder="Максимум задач"><button class="btn crm-btn-primary w-100" id="togglStart" disabled><i class="fa-solid fa-play"></i> Создать job</button><div id="togglActionMessage" class="small mt-3" role="status"></div></div></section>
<section class="crm-card toggl-panel toggl-job-panel"><div class="crm-card-header d-flex justify-content-between align-items-center"><h5 class="mb-0">Выполнение</h5><button class="btn crm-btn-secondary btn-sm" id="togglRefreshJobs"><i class="fa-solid fa-rotate"></i></button></div><div class="crm-card-body"><div id="togglJobs" class="toggl-state">Загрузка jobs…</div><div id="togglProgress" class="mt-3"></div></div></section>
</div></main></div></div>
<div class="modal fade" id="togglConnectionModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><form id="togglConnectionForm"><div class="modal-header"><h5 class="modal-title">Новое подключение Toggl Track</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button></div><div class="modal-body"><p class="text-muted small">Используйте Personal API Token Toggl. В API Toggl токен передаётся через Basic Auth как token:api_token; CRM хранит его зашифрованным и не возвращает в API.</p><label class="form-label">Название</label><input class="form-control mb-3" name="name" maxlength="255" required placeholder="Основной workspace Toggl"><label class="form-label">Personal API Token</label><input class="form-control" name="access_token" type="password" required autocomplete="new-password"><div id="togglConnectionError" class="alert alert-danger d-none mt-3"></div></div><div class="modal-footer"><button type="button" class="btn crm-btn-secondary" data-bs-dismiss="modal">Отмена</button><button class="btn crm-btn-primary" type="submit">Сохранить и проверить</button></div></form></div></div></div>
