<body data-page="module-asana-migration" data-protected="1">
<div class="crm-app"><aside class="crm-sidebar"><div class="crm-brand"><span class="crm-brand-mark"></span> <?= htmlspecialchars($t('app.name', 'TropaTT'), ENT_QUOTES, 'UTF-8') ?></div><nav class="nav flex-column crm-nav"></nav></aside>
<div class="crm-main-wrap"><header class="crm-topbar py-2"><div class="container-fluid"></div></header>
<main class="crm-content crm-admin-page"><div class="crm-page-head"><div><ol class="breadcrumb mb-1"><li class="breadcrumb-item"><a href="index.php?route=admin"><?= htmlspecialchars($t('nav.admin', 'Администрирование'), ENT_QUOTES, 'UTF-8') ?></a></li><li class="breadcrumb-item active">Миграция из Asana</li></ol><h1 class="crm-page-title">Миграция из Asana</h1><p class="crm-subtitle">Перенос проектов, разделов, задач, подзадач, комментариев, тегов и вложений в TropaTT CRM.</p></div></div>
<div id="asanaMigrationApp" class="asana-migration-grid">
<section class="crm-card asana-panel"><div class="crm-card-header d-flex justify-content-between align-items-center"><h5 class="mb-0">Подключение Asana</h5><button class="btn crm-btn-primary btn-sm" id="asanaAddConnection"><i class="fa-solid fa-plus"></i> Добавить</button></div><div class="crm-card-body"><div id="asanaConnections" class="asana-state">Загрузка подключений…</div></div></section>
<section class="crm-card asana-panel"><div class="crm-card-header d-flex justify-content-between align-items-center"><h5 class="mb-0">Источник</h5><button class="btn crm-btn-secondary btn-sm" id="asanaDiscover" disabled><i class="fa-solid fa-rotate"></i> Обновить</button></div><div class="crm-card-body"><div id="asanaWorkspaces" class="asana-state">Выберите подключение.</div><div id="asanaProjects" class="mt-3"></div></div></section>
<section class="crm-card asana-panel"><div class="crm-card-header"><h5 class="mb-0">Настройки миграции</h5></div><div class="crm-card-body"><label class="form-label" for="asanaMode">Режим</label><select id="asanaMode" class="form-select mb-3"><option value="import">Однократный импорт</option><option value="sync">Синхронизация</option><option value="dry_run">Предпросмотр без записи</option></select><label class="form-label" for="asanaSectionMode">Разделы Asana</label><select id="asanaSectionMode" class="form-select mb-3"><option value="project_module">Проектные модули</option></select><div class="form-text mb-3">В MVP разделы переносятся в проектные модули; глобальные статусы сохраняются в исходных метаданных.</div><div class="form-check mb-2"><input class="form-check-input" type="checkbox" id="asanaComments" checked><label class="form-check-label" for="asanaComments">Импортировать комментарии</label></div><div class="form-check mb-3"><input class="form-check-input" type="checkbox" id="asanaAttachments"><label class="form-check-label" for="asanaAttachments">Скачивать вложения</label></div><button class="btn crm-btn-primary w-100" id="asanaStart" disabled><i class="fa-solid fa-play"></i> Создать job</button><div id="asanaActionMessage" class="small mt-3" role="status"></div></div></section>
<section class="crm-card asana-panel asana-job-panel"><div class="crm-card-header d-flex justify-content-between align-items-center"><h5 class="mb-0">Выполнение</h5><button class="btn crm-btn-secondary btn-sm" id="asanaRefreshJobs"><i class="fa-solid fa-rotate"></i></button></div><div class="crm-card-body"><div id="asanaJobs" class="asana-state">Загрузка jobs…</div><div id="asanaProgress" class="mt-3"></div></div></section>
</div></main></div></div>
<div class="modal fade" id="asanaConnectionModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><form id="asanaConnectionForm"><div class="modal-header"><h5 class="modal-title">Новое подключение Asana</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button></div><div class="modal-body"><p class="text-muted small">Создайте Personal Access Token в Asana. Токен хранится в CRM в зашифрованном виде и никогда не выводится в интерфейс.</p><label class="form-label">Название</label><input class="form-control mb-3" name="name" maxlength="255" required placeholder="Рабочая Asana"><label class="form-label">Personal Access Token</label><input class="form-control" name="access_token" type="password" required autocomplete="new-password"><div id="asanaConnectionError" class="alert alert-danger d-none mt-3"></div></div><div class="modal-footer"><button type="button" class="btn crm-btn-secondary" data-bs-dismiss="modal">Отмена</button><button class="btn crm-btn-primary" type="submit">Сохранить и проверить</button></div></form></div></div></div>
