<?php
declare(strict_types=1);

namespace Module\Crm\KaitenMigration\Service;

use Module\Crm\KaitenMigration\Repository\KaitenMigrationRepository;
use RuntimeException;

final class KaitenImportService
{
    public function __construct(private readonly KaitenMigrationRepository $repo, private readonly KaitenClient $client, private readonly KaitenCrawler $crawler, private readonly KaitenTargetWriter $writer) {}

    public function processJob(string $jobPublicId, ?string $leaseToken = null): void
    {
        $job=$this->repo->getJob($jobPublicId);if(!$job)return;$connection=$this->repo->getConnectionById((int)$job['connection_id']);if(!$connection)throw new RuntimeException('KAITEN_CONNECTION_NOT_FOUND');$token=EncryptionService::decrypt((string)($connection['access_token_encrypted']??''));if($token===null)throw new RuntimeException('KAITEN_CREDENTIAL_DECRYPT_FAILED');$this->client->setConnectionId((int)$connection['id']);$this->client->setBaseUrl((string)($connection['base_url']??''));
        $existing=json_decode((string)($job['last_source_cursor']??''),true);$resume=is_array($existing)&&($existing['phase']??'')==='import'&&$this->repo->itemCount((int)$job['id'])>0&&str_starts_with((string)($job['current_step']??''),'import_');$heartbeat=$leaseToken!==null?fn():bool=>$this->repo->heartbeat($jobPublicId,$leaseToken):null;
        if($resume)$crawl=['resumed'=>true,'warnings'=>[]];else{$this->repo->updateProgress($jobPublicId,'crawl',0,['message'=>'Loading Kaiten source graph'],$leaseToken);$crawl=$this->crawler->crawl($job,$token,$heartbeat);if($leaseToken!==null&&!$this->repo->heartbeat($jobPublicId,$leaseToken))throw new RuntimeException('KAITEN_JOB_LEASE_LOST');$this->repo->addLog((int)$job['id'],'info','crawl','Kaiten source graph loaded.',$crawl);if(($job['mode']??'import')!=='dry_run')$this->repo->updateCursor($jobPublicId,json_encode(['phase'=>'import','priority'=>0,'id'=>0],JSON_UNESCAPED_UNICODE),$leaseToken);}
        if(($job['mode']??'import')==='dry_run'){$summary=['crawled'=>$crawl,'items'=>$this->repo->itemCounts((int)$job['id'])];$this->repo->updateSummary($jobPublicId,$summary,$leaseToken);$this->repo->updateProgress($jobPublicId,'dry_run_complete',100,$summary,$leaseToken);$this->repo->updateJobStatus($jobPublicId,'completed_with_warnings',$leaseToken);return;}
        $actor=$this->repo->actor((int)$job['created_by_user_id']);$total=max(1,$this->repo->itemCount((int)$job['id']));$counts=$this->repo->itemCounts((int)$job['id']);$done=array_sum(array_intersect_key($counts,array_flip(['imported','updated','skipped','failed'])));$warnings=(array)($crawl['warnings']??[]);$cursor=$resume&&is_array($existing)?$existing:['phase'=>'import','priority'=>0,'id'=>0];$priority=(int)($cursor['priority']??0);$lastId=(int)($cursor['id']??0);
        while(($items=$this->repo->importItemsBatch((int)$job['id'],$priority,$lastId,250))!==[]){foreach($items as $item){if($leaseToken!==null&&!$this->repo->heartbeat($jobPublicId,$leaseToken))throw new RuntimeException('KAITEN_JOB_LEASE_LOST');$current=$this->repo->getJob($jobPublicId);$status=(string)($current['status']??'');if(in_array($status,['pausing','paused','cancelling','cancelled'],true)){if($status==='pausing')$this->repo->updateJobStatus($jobPublicId,'paused');if($status==='cancelling')$this->repo->updateJobStatus($jobPublicId,'cancelled');return;}
                $sourceType=(string)$item['source_type'];$payload=json_decode((string)($item['payload_json']??'{}'),true);$payload=is_array($payload)?$payload:[];$mappingType=in_array($sourceType,['subcard'],true)?'card':$sourceType;$this->repo->upsertItem((int)$job['id'],$sourceType,(string)$item['source_id'],['source_parent_id'=>$item['source_parent_id']??null,'source_project_id'=>$item['source_project_id']??null,'payload_json'=>$payload]);
                try{$result=match($sourceType){'space'=>$this->writer->space($job,$payload,$actor),'board'=>$this->writer->board($job,$payload,$actor),'column'=>$this->writer->column($job,$payload,$actor),'tag'=>$this->writer->tag($job,$payload),'custom_field'=>$this->writer->customField($job,$payload),'card','subcard'=>$this->writer->card($job,$payload,$actor),'comment'=>$this->writer->comment($job,$payload,$actor),'attachment'=>$this->writer->attachment($job,$payload,$actor,$token,max(1,(int)($job['target_options']['max_attachment_size_mb']??20))*1024*1024),'history'=>$this->writer->history($job,$payload,$actor),default=>['target_type'=>'','target_public_id'=>'','state'=>'skipped','warnings'=>[]]};$warnings=array_merge($warnings,(array)($result['warnings']??[]));$target=(string)($result['target_public_id']??'');if($target!=='')$this->repo->upsertMapping((int)$job['connection_id'],(string)$job['workspace_gid'],$mappingType,(string)$item['source_id'],['source_parent_id'=>$item['source_parent_id']??null,'target_type'=>$result['target_type'],'target_public_id'=>$target,'source_checksum'=>$item['checksum']??null,'target_checksum'=>hash('sha256',$target),'created_by_job_id'=>(int)$job['id']]);$this->repo->upsertItem((int)$job['id'],$sourceType,(string)$item['source_id'],['target_type'=>$result['target_type'],'target_public_id'=>$target,'created_by_job'=>$result['state']==='imported'?1:(int)($item['created_by_job']??0),'status'=>$result['state'],'error_code'=>null,'error_message'=>null]);}catch(\Throwable $e){$this->repo->upsertItem((int)$job['id'],$sourceType,(string)$item['source_id'],['status'=>'failed','attempts'=>(int)($item['attempts']??0)+1,'error_code'=>'IMPORT_FAILED','error_message'=>'Item import failed. Check the migration log.']);$this->repo->addLog((int)$job['id'],'error','import_'.$sourceType,'Source item import failed.',['source_type'=>$sourceType,'source_id'=>$item['source_id'],'error_code'=>$e->getCode()?:'KAITEN_IMPORT_ERROR']);}
                $done++;$priority=(int)($item['import_priority']??$priority);$lastId=(int)$item['id'];$this->repo->updateProgress($jobPublicId,'import_'.$sourceType,min(99,($done/$total)*100),['processed'=>$done,'total'=>$total,'warnings'=>count($warnings)],$leaseToken);
            }$this->repo->updateCursor($jobPublicId,json_encode(['phase'=>'import','priority'=>$priority,'id'=>$lastId],JSON_UNESCAPED_UNICODE),$leaseToken);
        }
        $afterParentId=0;while(($parentItems=$this->repo->subcardItemsBatch((int)$job['id'],$afterParentId,250))!==[]){foreach($parentItems as $parentItem){if($leaseToken!==null&&!$this->repo->heartbeat($jobPublicId,$leaseToken))throw new RuntimeException('KAITEN_JOB_LEASE_LOST');$parentPayload=json_decode((string)($parentItem['payload_json']??'{}'),true);$parentPayload=is_array($parentPayload)?$parentPayload:[];$parentItem['payload']=$parentPayload;$result=$this->writer->reconcileParent($job,$parentItem,$actor);$warnings=array_merge($warnings,(array)($result['warnings']??[]));$afterParentId=max($afterParentId,(int)$parentItem['id']);}$this->repo->updateProgress($jobPublicId,'reconcile_parents',min(99,($afterParentId/max(1,$this->repo->itemCount((int)$job['id'])))*100),['processed'=>$afterParentId],$leaseToken);}
        $summary=['crawled'=>$crawl,'items'=>$this->repo->itemCounts((int)$job['id']),'warnings'=>array_values(array_unique($warnings))];$this->repo->updateSummary($jobPublicId,$summary,$leaseToken);$this->repo->updateProgress($jobPublicId,'completed',100,$summary,$leaseToken);$failed=(int)($summary['items']['failed']??0);$this->repo->updateJobStatus($jobPublicId,$failed>0||$summary['warnings']!==[]?'completed_with_warnings':'completed',$leaseToken);$this->repo->addLog((int)$job['id'],'info','completed','Kaiten migration completed.',['failed'=>$failed,'warnings'=>count($summary['warnings'])]);
    }

    public function rollback(string $jobPublicId,array $actor): void
    {
        $job=$this->repo->beginRollback($jobPublicId);if(!$job)throw new RuntimeException('KAITEN_ROLLBACK_REQUIRES_TERMINAL_JOB');$lease=(string)($job['lease_token']??'');$cursor=json_decode((string)($job['last_source_cursor']??''),true);$rollbackPriority=is_array($cursor)?max(0,(int)($cursor['rollback_priority']??0)):0;$before=is_array($cursor)?max(1,(int)($cursor['before_id']??PHP_INT_MAX)):PHP_INT_MAX;$warnings=[];
        try{while(($items=$this->repo->rollbackItemsBatch((int)$job['id'],$rollbackPriority,$before,250))!==[]){foreach($items as $item){if(!$this->repo->heartbeat($jobPublicId,$lease))throw new RuntimeException('KAITEN_ROLLBACK_LEASE_LOST');if((int)($item['created_by_job']??0)!==1||empty($item['target_public_id']))continue;try{$type=(string)$item['target_type'];$serviceId=match($type){'project'=>'service.project','project_module'=>'service.project_module','task'=>'service.task','file'=>'service.file','status'=>'service.status','tag'=>'service.tag','comment'=>'service.comment',default=>''};if($serviceId==='')continue;$service=$this->writer->service($serviceId);$deleted=in_array($type,['status','tag'],true)?$service->delete((string)$item['target_public_id']):$service->delete((string)$item['target_public_id'],$actor);$deletedOk=is_array($deleted)?(bool)($deleted['ok']??false):$deleted===true;if(!$deletedOk)throw new RuntimeException('KAITEN_ROLLBACK_TARGET_NOT_DELETED');$this->repo->upsertItem((int)$job['id'],(string)$item['source_type'],(string)$item['source_id'],['status'=>'rolled_back']);$this->repo->markMappingRolledBack((int)$job['connection_id'],(string)(in_array((string)$item['source_type'],['subcard'],true)?'card':$item['source_type']),(string)$item['source_id']);}catch(\Throwable $e){$warnings[]=(string)$item['source_id'];$this->repo->upsertItem((int)$job['id'],(string)$item['source_type'],(string)$item['source_id'],['status'=>'rollback_failed','error_code'=>'ROLLBACK_FAILED','error_message'=>'Target could not be removed.']);$this->repo->addLog((int)$job['id'],'warning','rollback','Target item was not removed.',['source_id'=>$item['source_id'],'error_code'=>$e->getCode()?:'KAITEN_ROLLBACK_TARGET_NOT_DELETED']);}}
                if($warnings!==[])break;$lastItem=$items[count($items)-1];$rollbackPriority=(int)($lastItem['rollback_priority']??$rollbackPriority);$before=(int)$lastItem['id'];$this->repo->updateCursor($jobPublicId,json_encode(['phase'=>'rollback','rollback_priority'=>$rollbackPriority,'before_id'=>$before],JSON_UNESCAPED_UNICODE),$lease);}
            $this->repo->updateSummary($jobPublicId,['rollback_warnings'=>array_values(array_unique($warnings))],$lease);$this->repo->updateProgress($jobPublicId,'rolled_back',100,['warnings'=>count($warnings)],$lease);$this->repo->updateJobStatus($jobPublicId,$warnings===[]?'rolled_back':'rolled_back_with_warnings',$lease);$this->repo->releaseLease($jobPublicId,$lease);
        }catch(\Throwable $e){try{if($this->repo->ownsLease($jobPublicId,$lease)){$this->repo->updateJobStatus($jobPublicId,'rollback_failed',$lease);$this->repo->releaseLease($jobPublicId,$lease);}}catch(\Throwable){}throw $e;}
    }
}
