<?php
declare(strict_types=1);

namespace Module\Crm\Bitrix24Migration\Service;

use Api\System\Library\Container;
use Module\Crm\Bitrix24Migration\Repository\Bitrix24MigrationRepository;
use RuntimeException;

final class Bitrix24TargetWriter
{
    public function __construct(private readonly Container $container, private readonly Bitrix24MigrationRepository $repo, private readonly Bitrix24Client $client) {}
    public function service(string $id): mixed { return $this->container->get($id); }
    private function map(array $job,string $type,string $id): ?array { $id=trim($id);return$id===''?null:$this->repo->findMapping((int)$job['connection_id'],$type,$id); }
    private function actorId(array $actor): int { return(int)($actor['id']??0); }
    private function result(string $type,string $id,string $state,array $warnings=[]): array { return['target_type'=>$type,'target_public_id'=>$id,'state'=>$state,'warnings'=>$warnings]; }

    public function department(array $job,array $p,array $actor): array
    {
        $source=$this->sourceId($p);$mapping=$this->map($job,'department',$source);if($mapping&&!empty($mapping['target_public_id']))return$this->result('department',(string)$mapping['target_public_id'],'skipped');
        $created=$this->service('service.department')->create(['title'=>$this->title($p,'Bitrix department'),'code'=>'b24_'.$source],$actor);if(!is_array($created)||empty($created['public_id']))throw new RuntimeException('BITRIX24_DEPARTMENT_CREATE_FAILED');return$this->result('department',(string)$created['public_id'],'imported');
    }
    public function user(array $job,array $p): array { return$this->result('user','', 'skipped',['Bitrix24 user was discovered and is available for manual CRM mapping.']); }

    public function project(array $job,array $p,array $actor): array
    {
        $source=$this->sourceId($p);$mappingType=(string)($p['_source_type']??'project')==='task_project'?'task_project':'project';$mapping=$this->map($job,$mappingType,$source);if(!$mapping&&$mappingType==='task_project')$mapping=$this->map($job,'project',$source);$service=$this->service('service.project');$warnings=[];
        if($mapping&&!empty($mapping['target_public_id'])){ $existing=$service->get((string)$mapping['target_public_id'],$actor);if($existing){if(($job['mode']??'import')!=='sync')return$this->result('project',(string)$mapping['target_public_id'],'skipped');$updated=$service->update((string)$mapping['target_public_id'],['title'=>$this->title($p,'Bitrix project'),'description'=>$this->description($p)],$actor);return$this->result('project',(string)$mapping['target_public_id'],is_array($updated)?'updated':'warning',is_array($updated)?[]:['Project update failed.']);}$warnings[]='Stored Bitrix project mapping no longer resolves.';}
        $prefix='B2'.strtoupper(substr(hash('sha256',$source),0,5));$created=$service->create(['title'=>$this->title($p,'Bitrix project'),'description'=>$this->description($p),'status'=>$this->archived($p)?'archived':'active','priority'=>'normal','task_key_prefix'=>$prefix],$actor);if($created==='PROJECT_TASK_PREFIX_ALREADY_EXISTS'){$prefix.='X';$created=$service->create(['title'=>$this->title($p,'Bitrix project'),'description'=>$this->description($p),'status'=>'active','priority'=>'normal','task_key_prefix'=>$prefix],$actor);}if(!is_array($created)||empty($created['public_id']))throw new RuntimeException('BITRIX24_PROJECT_CREATE_FAILED');return$this->result('project',(string)$created['public_id'],'imported',$warnings);
    }

    public function company(array $job,array $p,array $actor): array
    {
        $source=$this->sourceId($p);$mapping=$this->map($job,'company',$source);$service=$this->service('service.company');$title=$this->title($p,'Bitrix company');
        if($mapping&&!empty($mapping['target_public_id'])){if(($job['mode']??'import')==='sync'){$updated=$service->update((string)$mapping['target_public_id'],['title'=>$title,'email'=>$this->email($p),'tax_number'=>(string)($p['RQ_INN']??$p['INN']??'')],$actor);return$this->result('company',(string)$mapping['target_public_id'],is_array($updated)?'updated':'warning',is_array($updated)?[]:['Company update failed.']);}return$this->result('company',(string)$mapping['target_public_id'],'skipped');}
        $created=$service->create(['title'=>$title,'email'=>$this->email($p),'tax_number'=>(string)($p['RQ_INN']??$p['INN']??''),'status'=>'active'],$actor);if(!is_array($created)||empty($created['public_id']))throw new RuntimeException('BITRIX24_COMPANY_CREATE_FAILED');return$this->result('company',(string)$created['public_id'],'imported');
    }
    public function contact(array $job,array $p,array $actor): array
    {
        $source=$this->sourceId($p);$mapping=$this->map($job,'contact',$source);$company=$this->map($job,'company',(string)($p['COMPANY_ID']??''));$input=['full_name'=>$this->personName($p),'email'=>$this->email($p),'phone'=>$this->phone($p),'role'=>(string)($p['POST']??'')];if($company&&!empty($company['target_public_id']))$input['company_public_id']=(string)$company['target_public_id'];if($mapping&&!empty($mapping['target_public_id'])){if(($job['mode']??'import')==='sync'){$updated=$this->service('service.contact')->update((string)$mapping['target_public_id'],$input,$actor);return$this->result('contact',(string)$mapping['target_public_id'],is_array($updated)?'updated':'warning',is_array($updated)?[]:['Contact update failed.']);}return$this->result('contact',(string)$mapping['target_public_id'],'skipped');}$created=$this->service('service.contact')->create($input,$actor);if(!is_array($created)||empty($created['public_id']))throw new RuntimeException('BITRIX24_CONTACT_CREATE_FAILED');return$this->result('contact',(string)$created['public_id'],'imported');
    }
    public function lead(array $job,array $p,array $actor): array
    {
        $source=$this->sourceId($p);$mapping=$this->map($job,'lead',$source);$input=['title'=>$this->title($p,$this->personName($p)),'counterparty_type'=>'person','person_first_name'=>(string)($p['NAME']??''),'person_last_name'=>(string)($p['LAST_NAME']??''),'email'=>$this->email($p),'phone'=>$this->phone($p),'notes'=>$this->description($p)."\n\n[Bitrix24 lead ID: {$source}]",'extra_attributes'=>['source'=>'bitrix24','lead_id'=>$source,'status_id'=>$p['STATUS_ID']??null]];if($mapping&&!empty($mapping['target_public_id'])){if(($job['mode']??'import')==='sync'){$updated=$this->service('service.counterparty')->update((string)$mapping['target_public_id'],$input,$actor);return$this->result('counterparty',(string)$mapping['target_public_id'],is_array($updated)?'updated':'warning',is_array($updated)?[]:['Lead update failed.']);}return$this->result('counterparty',(string)$mapping['target_public_id'],'skipped');}$created=$this->service('service.counterparty')->create(['title'=>$this->title($p,$this->personName($p)),'counterparty_type'=>'person','person_first_name'=>(string)($p['NAME']??''),'person_last_name'=>(string)($p['LAST_NAME']??''),'email'=>$this->email($p),'phone'=>$this->phone($p),'notes'=>$this->description($p)."\n\n[Bitrix24 lead ID: {$source}]",'extra_attributes'=>['source'=>'bitrix24','lead_id'=>$source,'status_id'=>$p['STATUS_ID']??null]],$actor);if(!is_array($created)||empty($created['public_id']))throw new RuntimeException('BITRIX24_LEAD_CREATE_FAILED');return$this->result('counterparty',(string)$created['public_id'],'imported',['Bitrix24 lead was mapped to a counterparty because TropaTT has no native lead entity.']);
    }

    public function task(array $job,array $p,array $actor): array
    {
        $source=$this->sourceId($p);$type=(string)($p['_source_type']??'task');$mapType=$type==='subtask'?'subtask':'task';$mapping=$this->map($job,$mapType,$source);$projectId=(string)($p['GROUP_ID']??$p['groupId']??'');$project=$this->map($job,'project',$projectId);if(!$project)$project=$this->map($job,'task_project','__bitrix24_tasks__');if(!$project||empty($project['target_public_id']))throw new RuntimeException('BITRIX24_TASK_PROJECT_NOT_READY');$parentSource=(string)($p['_source_parent_id']??$p['PARENT_ID']??$p['parentId']??'');$parent=$parentSource!==''?$this->map($job,'task',$parentSource):null;if(!$parent&&$parentSource!=='')$parent=$this->map($job,'subtask',$parentSource);$status=$this->taskStatus($p);$assignee=$this->repo->mappedUserId((int)$job['connection_id'],(string)($p['RESPONSIBLE_ID']??$p['responsibleId']??''));$input=['project_public_id'=>(string)$project['target_public_id'],'title'=>$this->title($p,'Bitrix task'),'description'=>$this->description($p),'status'=>$status,'priority'=>$this->taskPriority($p),'due_at'=>$this->date($p['DEADLINE']??$p['deadline']??null),'start_at'=>$this->date($p['START_DATE_PLAN']??null),'end_at'=>$this->date($p['END_DATE_PLAN']??null),'assignee_user_id'=>$assignee,'source_type'=>'bitrix24','source_id'=>$source,'source_url'=>'','source_payload_json'=>$p,'created_at'=>$this->date($p['DATE_CREATE']??null),'updated_at'=>$this->date($p['CHANGED_DATE']??$p['DATE_MODIFY']??null)];$warnings=[];if($parent&&!empty($parent['target_public_id']))$input['parent_task_public_id']=(string)$parent['target_public_id'];elseif($parentSource!=='')$warnings[]='Parent Bitrix task was not mapped; imported as a root task.';
        $service=$this->service('service.task');if($mapping&&!empty($mapping['target_public_id'])){ $target=(string)$mapping['target_public_id'];if(($job['mode']??'import')==='sync'){$updated=$service->update($target,$input,$this->actorId($actor),$actor);if(!is_array($updated))$warnings[]='Task update failed.';$state='updated';}else$state='skipped';}else{$created=$service->create($input,$actor);if(!is_array($created)||empty($created['public_id']))throw new RuntimeException(is_string($created)?'BITRIX24_'.$created:'BITRIX24_TASK_CREATE_FAILED');$target=(string)$created['public_id'];$state='imported';}
        $tags=$this->tags($p);foreach($tags as $tag){$tagId='tag:'.hash('sha256',(string)$job['connection_id'].':'.$tag);$tagMap=$this->map($job,'tag',$tagId);if(!$tagMap){$tagCreated=$this->service('service.tag')->create(['code'=>'b24_'.substr(hash('sha256',(string)$job['connection_id'].':'.$tag),0,24),'title'=>mb_substr($tag,0,120),'color'=>'#64748b','description'=>'Imported from Bitrix24 task tag']);if(is_array($tagCreated)&&!empty($tagCreated['public_id'])){$tagMap=$this->repo->upsertMapping((int)$job['connection_id'],'tag',$tagId,['target_type'=>'tag','target_public_id'=>$tagCreated['public_id'],'created_by_job_id'=>(int)$job['id']]);$this->repo->upsertItem((int)$job['id'],'tag',$tagId,['target_type'=>'tag','target_public_id'=>$tagCreated['public_id'],'created_by_job'=>1,'status'=>'imported','checksum'=>hash('sha256',$tagId)]);}}if($tagMap&&!empty($tagMap['target_public_id']))try{$this->service('service.tag')->attachToTask($target,(string)$tagMap['target_public_id'],$actor);}catch(\Throwable){$warnings[]='A task tag could not be attached.';}}
        return$this->result('task',$target,$state,$warnings);
    }

    public function deal(array $job,array $p,array $actor): array { return$this->crmRecordAsTask($job,$p,$actor,'deal','Bitrix deal'); }
    public function invoice(array $job,array $p,array $actor): array { return$this->crmRecordAsTask($job,$p,$actor,'invoice','Bitrix invoice'); }
    public function quote(array $job,array $p,array $actor): array { return$this->crmRecordAsTask($job,$p,$actor,'quote','Bitrix quote'); }
    public function product(array $job,array $p,array $actor): array { return$this->crmRecordAsTask($job,$p,$actor,'product','Bitrix product'); }
    public function productRow(array $job,array $p,array $actor): array
    {
        $source=$this->sourceId($p);$mapping=$this->map($job,'product_row',$source);if($mapping&&!empty($mapping['target_public_id']))return$this->result('comment',(string)$mapping['target_public_id'],'skipped');
        $ownerType=(string)($p['_owner_type']??'');$ownerId=(string)($p['_owner_id']??'');$parent=$ownerType!==''&&$ownerId!==''?$this->map($job,$ownerType,$ownerId):null;
        if(!$parent||($parent['target_type']??'')!=='task')return$this->result('comment','', 'skipped',['Bitrix product row has no mapped invoice, quote or deal task.']);
        $label=$this->title($p,'Bitrix product');$qty=(string)($p['quantity']??$p['QUANTITY']??'');$price=(string)($p['price']??$p['PRICE']??'');$body='Товарная позиция Битрикс24: '.$label;if($qty!=='')$body.="\nКоличество: {$qty}";if($price!=='')$body.="\nЦена: {$price}";
        $created=$this->service('service.comment')->createByTaskImported((string)$parent['target_public_id'],['body'=>$body],$this->actorId($actor));if(!is_array($created)||empty($created['public_id']))throw new RuntimeException('BITRIX24_PRODUCT_ROW_COMMENT_FAILED');return$this->result('comment',(string)$created['public_id'],'imported',['Product row was preserved as a comment on the imported CRM record task.']);
    }
    public function activity(array $job,array $p,array $actor): array { return$this->calendar($job,$p,$actor,'activity'); }
    public function event(array $job,array $p,array $actor): array { return$this->calendar($job,$p,$actor,'event'); }
    public function timelineComment(array $job,array $p,array $actor): array
    {
        $source=$this->sourceId($p);$mapping=$this->map($job,'timeline_comment',$source);if($mapping&&!empty($mapping['target_public_id']))return$this->result((string)$mapping['target_type'],(string)$mapping['target_public_id'],'skipped');$parentType=(string)($p['_source_parent_type']??'');$parentSource=(string)($p['_source_parent_id']??$p['ENTITY_ID']??'');$parent=$this->map($job,$parentType,$parentSource);$body=(string)($p['COMMENT']??$p['comment']??$p['POST_MESSAGE']??'');if(trim($body)==='')return$this->result('comment','', 'skipped',['Empty Bitrix timeline comment skipped.']);$author=$this->repo->mappedUserId((int)$job['connection_id'],(string)($p['AUTHOR_ID']??''))??$this->actorId($actor);
        if($parent&&($parent['target_type']??'')==='task'){$created=$this->service('service.comment')->createByTaskImported((string)$parent['target_public_id'],['body'=>$body,'created_at'=>$p['CREATED']??null,'author_user_id'=>$author],$this->actorId($actor));if(!is_array($created)||empty($created['public_id']))throw new RuntimeException('BITRIX24_COMMENT_CREATE_FAILED');return$this->result('comment',(string)$created['public_id'],'imported');}
        $synthetic=$this->map($job,'task_project','__bitrix24_tasks__');if(!$synthetic||empty($synthetic['target_public_id']))throw new RuntimeException('BITRIX24_COMMENT_PROJECT_NOT_READY');$createdTask=$this->service('service.task')->create(['project_public_id'=>$synthetic['target_public_id'],'title'=>'Битрикс24 комментарий: '.$parentType.' #'.$parentSource,'description'=>$body,'status'=>'completed','priority'=>'normal','source_type'=>'bitrix24_timeline_comment','source_id'=>$source,'source_payload_json'=>$p],$actor);if(!is_array($createdTask)||empty($createdTask['public_id']))throw new RuntimeException('BITRIX24_COMMENT_TASK_CREATE_FAILED');return$this->result('task',(string)$createdTask['public_id'],'imported',['Timeline comment was preserved as a task because TropaTT has no native comment target for '.$parentType.'.']);
    }
    public function comment(array $job,array $p,array $actor): array { return$this->timelineComment($job,$p,$actor); }    public function file(array $job,array $p,array $actor): array
    {
        $source=$this->sourceId($p);$mapping=$this->map($job,'file',$source);if($mapping&&!empty($mapping['target_public_id']))return$this->result('file',(string)$mapping['target_public_id'],'skipped');$parentSource=(string)($p['_source_parent_id']??'');$commentMapping=$this->map($job,'timeline_comment',$parentSource)??$this->map($job,'comment',$parentSource);$commentItem=$this->repo->findItem((int)$job['id'],'timeline_comment',$parentSource)??$this->repo->findItem((int)$job['id'],'comment',$parentSource);$parentType='';$parentId='';if(is_array($commentItem)){ $commentPayload=json_decode((string)($commentItem['payload_json']??'{}'),true)?:[];$parentType=(string)($commentPayload['_source_parent_type']??'');$parentId=(string)($commentPayload['_source_parent_id']??''); }        $url=(string)($p['_download_url']??$p['DOWNLOAD_URL']??$p['download_url']??$p['urlDownload']??'');if($url===''){$details=$source!==''?$this->client->fileDetails($source):[];$url=(string)($details['DOWNLOAD_URL']??$details['download_url']??$details['urlDownload']??'');if($url!=='')$p=array_merge($details,$p);}$url=trim($url);$warnings=[];if($url==='')return$this->result('file','', 'skipped',['Bitrix file has no downloadable URL.']);foreach(['DOWNLOAD_URL','download_url','urlDownload','VIEW_URL','view_url','URL','url','_download_url'] as $secretKey)unset($p[$secretKey]);$task=($commentMapping&&($commentMapping['target_type']??'')==='task')?$commentMapping:($parentType!==''&&$parentId!==''?$this->map($job,$parentType,$parentId):$this->map($job,'task',$parentSource));if(!$task||empty($task['target_public_id'])){$task=$this->ensureFileTask($job,$p,$actor);$warnings[]='Bitrix Disk file had no resolvable CRM parent and was attached to a generated import task.';}$taskId=(string)($task['target_public_id']??'');if($taskId==='')return$this->result('file','', 'skipped',array_merge($warnings,['Bitrix file has no import task parent.']));$download=$this->client->downloadFile($url,20*1024*1024);try{$content=file_get_contents($download['path']);if(!is_string($content))throw new RuntimeException('BITRIX24_FILE_READ_FAILED');$created=$this->service('service.file')->create(['entity_type'=>'task','entity_public_id'=>$taskId,'name'=>$this->fileName($p),'mime_type'=>$download['mime_type'],'content_base64'=>base64_encode($content)],[], $this->actorId($actor),$actor);if(!is_array($created)||empty($created['public_id']))throw new RuntimeException('BITRIX24_FILE_CREATE_FAILED');return$this->result('file',(string)$created['public_id'],'imported',$warnings);}finally{@unlink((string)$download['path']);}
    }
    private function ensureFileTask(array $job,array $p,array $actor): ?array
    {
        $source=$this->sourceId($p);$syntheticSource='file:'.$source;$existing=$this->map($job,'file_task',$syntheticSource);if($existing&&!empty($existing['target_public_id']))return$existing;$project=$this->map($job,'task_project','__bitrix24_tasks__');if(!$project||empty($project['target_public_id']))return null;$created=$this->service('service.task')->create(['project_public_id'=>$project['target_public_id'],'title'=>'Битрикс24 файл: '.$this->fileName($p),'description'=>'Импортированный файл из Битрикс24 Disk.','status'=>'new','priority'=>'normal','source_type'=>'bitrix24_file_parent','source_id'=>$source,'source_payload_json'=>$p],$actor);if(!is_array($created)||empty($created['public_id']))return null;$mapping=$this->repo->upsertMapping((int)$job['connection_id'],'file_task',$syntheticSource,['target_type'=>'task','target_public_id'=>$created['public_id'],'created_by_job_id'=>(int)$job['id']]);$this->repo->upsertItem((int)$job['id'],'file_task',$syntheticSource,['target_type'=>'task','target_public_id'=>$created['public_id'],'created_by_job'=>1,'status'=>'imported','checksum'=>hash('sha256',$syntheticSource)]);return$mapping;
    }

    public function unsupported(array $job,array $p,string $type): array { return$this->result($type,'','skipped',['Bitrix24 '.$type.' was preserved in the job payload but has no verified native TropaTT target.']); }

    private function crmRecordAsTask(array $job,array $p,array $actor,string $type,string $label): array { $source=$this->sourceId($p);$mapping=$this->map($job,$type,$source);$input=['title'=>$label.': '.$this->title($p,$source),'description'=>$this->description($p)."\n\n[Bitrix24 {$type} ID: {$source}]",'status'=>'new','priority'=>'normal','source_type'=>'bitrix24_'.$type,'source_id'=>$source,'source_payload_json'=>$p];if($mapping&&!empty($mapping['target_public_id'])){if(($job['mode']??'import')==='sync'){$updated=$this->service('service.task')->update((string)$mapping['target_public_id'],$input,$this->actorId($actor),$actor);return$this->result('task',(string)$mapping['target_public_id'],is_array($updated)?'updated':'warning',is_array($updated)?[]:['Bitrix '.$type.' task update failed.']);}return$this->result('task',(string)$mapping['target_public_id'],'skipped');}$project=$this->map($job,'task_project','__bitrix24_tasks__');if(!$project||empty($project['target_public_id']))throw new RuntimeException('BITRIX24_CRM_TASK_PROJECT_NOT_READY');$input['project_public_id']=$project['target_public_id'];$created=$this->service('service.task')->create($input,$actor);if(!is_array($created)||empty($created['public_id']))throw new RuntimeException('BITRIX24_'.$type.'_TASK_CREATE_FAILED');return$this->result('task',(string)$created['public_id'],'imported',['TropaTT has no native '.$type.' entity; it was imported as a task with the original payload.']); }
    private function calendar(array $job,array $p,array $actor,string $type): array { $source=$this->sourceId($p);$mapping=$this->map($job,$type,$source);if($mapping&&!empty($mapping['target_public_id']))return$this->result('calendar_event',(string)$mapping['target_public_id'],'skipped');$start=$this->date($p['DATE_START']??$p['DATE_CREATE']??$p['START_DATE']??$p['START_TIME']??null);if($start===null)return$this->result('calendar_event','', 'skipped',['Bitrix '.$type.' has no valid start date.']);$end=$this->date($p['DATE_END']??$p['END_DATE']??$p['END_TIME']??$start)??$start;$startTs=strtotime($start);$endTs=strtotime($end);if($startTs!==false&&$endTs!==false&&$endTs<$startTs)$end=$start;$owner=(string)($p['OWNER_ID']??$p['ownerId']??$p['CREATED_BY']??$p['USER_ID']??'');$description=$this->description($p);$warnings=[];$eventInput=['title'=>$this->title($p,'Bitrix '.$type),'description'=>$description,'starts_at'=>$start,'ends_at'=>$end];$mappedOwner=$owner!==''?$this->repo->mappedUserId((int)$job['connection_id'],$owner):null;if($mappedOwner!==null&&$mappedOwner>0)$eventInput['owner_user_id']=$mappedOwner;elseif($owner!==''){$description=rtrim($description)."\n\n[Bitrix24 calendar owner ID: {$owner}]";$eventInput['description']=$description;$warnings[]='Calendar owner was not mapped; the importing actor owns this event.';}$created=$this->service('service.calendar')->createEvent($eventInput,$actor);if(!is_array($created)||empty($created['public_id']))throw new RuntimeException('BITRIX24_EVENT_CREATE_FAILED');return$this->result('calendar_event',(string)$created['public_id'],'imported',$warnings); }
    private function sourceId(array $p): string { return trim((string)($p['_source_id']??$p['ID']??$p['id']??'')); }
    private function title(array $p,string $fallback): string { return trim((string)($p['TITLE']??$p['NAME']??$p['SUBJECT']??$p['ORDER_TOPIC']??$p['name']??$fallback))?:$fallback; }
    private function personName(array $p): string { return trim(implode(' ',array_filter([(string)($p['NAME']??''),(string)($p['SECOND_NAME']??''),(string)($p['LAST_NAME']??'')])))?:$this->title($p,'Bitrix contact'); }
    private function email(array $p): string { $v=$p['EMAIL']??'';if(is_array($v))$v=$v[0]['VALUE']??$v[0]??'';return trim((string)$v); }
    private function phone(array $p): string { $v=$p['PHONE']??'';if(is_array($v))$v=$v[0]['VALUE']??$v[0]??'';return trim((string)$v); }
    private function description(array $p): string { $v=(string)($p['COMMENTS']??$p['DESCRIPTION']??$p['desc']??'');$extra=[];foreach($p as $k=>$value){if(str_starts_with((string)$k,'UF_')&&!is_array($value)&&$value!=='')$extra[]='- '.$k.': '.$value;}if($extra!==[])$v=rtrim($v)."\n\nПоля Битрикс24:\n".implode("\n",$extra);return mb_substr($v,0,65000); }
    private function date(mixed $v): ?string {$v=trim((string)$v);if($v==='')return null;$ts=strtotime($v);return$ts===false?null:gmdate('Y-m-d H:i:s',$ts);}
    private function archived(array $p): bool {return in_array(strtoupper((string)($p['ACTIVE']??$p['CLOSED']??$p['archived']??'')),['N','Y'],true)&&strtoupper((string)($p['ACTIVE']??''))==='N';}
    private function taskStatus(array $p): string {$s=(string)($p['STATUS']??$p['status']??'');return in_array(strtolower($s),['5','completed','done','finished'],true)?'completed':(in_array(strtolower($s),['3','4','in_progress','in progress'],true)?'in_progress':'new');}
    private function taskPriority(array $p): string {$s=strtolower((string)($p['PRIORITY']??$p['priority']??''));return match($s){ '1','urgent','critical'=>'urgent','2','high'=>'high','4','low'=>'low',default=>'normal'};}
    private function tags(array $p): array {$v=$p['TAGS']??$p['tags']??[];if(is_string($v))return array_values(array_filter(array_map('trim',preg_split('/[,;]+/',$v)?:[])));$out=[];foreach((array)$v as $item){$out[]=is_array($item)?(string)($item['TITLE']??$item['NAME']??$item['title']??''):(string)$item;}return array_values(array_filter(array_map('trim',$out)));}
    private function fileName(array $p): string {return trim((string)($p['NAME']??$p['name']??$p['ORIGINAL_NAME']??'bitrix-file.bin'))?:'bitrix-file.bin';}
}
