<?php
declare(strict_types=1);

/**
 * Unit & Contract Tests for OpenCart 3.0, OpenCart 4.0, and WooCommerce Connectors.
 */

require_once dirname(__DIR__, 3) . '/api/system/library/support/Autoloader.php';
require_once dirname(__DIR__, 3) . '/api/system/library/support/Ulid.php';

$apiRoot = dirname(__DIR__, 3) . '/api';
$autoloader = new Api\System\Library\Support\Autoloader($apiRoot);
$autoloader->register();

// Register module autoloader
spl_autoload_register(function (string $class): void {
    $prefix = 'Module\\Crm\\EcommerceGateway\\';
    if (!str_starts_with($class, $prefix)) {
        return;
    }
    $relative = substr($class, strlen($prefix));
    $parts = explode('\\', $relative);

    $first = strtolower(array_shift($parts));
    $path = dirname(__DIR__) . '/api/' . $first . '/' . implode('/', $parts) . '.php';
    if (file_exists($path)) {
        require_once $path;
    }
});

use Module\Crm\EcommerceGateway\Service\SignatureService;
use Module\Crm\EcommerceGateway\Service\PayloadValidator;

$passed = 0;
$failed = 0;

function assert_true(bool $condition, string $msg): void {
    global $passed, $failed;
    if ($condition) {
        $passed++;
        echo "  [PASS] {$msg}\n";
    } else {
        $failed++;
        echo "  [FAIL] {$msg}\n";
    }
}

echo "Running E-Commerce Gateway Connectors Unit Tests...\n\n";

$validator = new PayloadValidator();
$secret = 'test_secret_for_connector_validation_12345678';
$storeKey = 'stk_test_opencart_store_key';

// --- 1. OpenCart 3.0 Connector Validation ---
echo "--- 1. OpenCart 3.0 Connector Contract & Signatures ---\n";

$timestamp = (string)time();
$nonce = bin2hex(random_bytes(16));
$emptySha = SignatureService::EMPTY_BODY_SHA256;

// Check canonical ping signature from OpenCart 3.0 controller
$canonicalPing = "GET\n/_module/crm.ecommerce-gateway/v1/ping\n{$timestamp}\n{$nonce}\n{$emptySha}";
$oc3Signature = base64_encode(hash_hmac('sha256', $canonicalPing, $secret, true));

$verifyPing = SignatureService::verify(
    $secret,
    $oc3Signature,
    'GET',
    '/_module/crm.ecommerce-gateway/v1/ping',
    $timestamp,
    $nonce,
    ''
);
assert_true($verifyPing, "OpenCart 3.0 ping signature verified by CRM SignatureService");

// Check Order Ingestion payload generated by OpenCart 3.0 Model
$oc3OrderPayload = [
    'external_id' => '1042',
    'payload' => [
        'order_number' => '1042',
        'order_status' => '1',
        'items' => [
            [
                'name' => 'Беспроводные наушники Pro',
                'sku' => 'ART-101',
                'quantity' => 1.0,
                'price' => ['amount_minor' => 150000, 'currency' => 'RUB'],
                'line_total' => ['amount_minor' => 150000, 'currency' => 'RUB'],
            ]
        ],
        'subtotal' => ['amount_minor' => 150000, 'currency' => 'RUB'],
        'delivery_total' => ['amount_minor' => 35000, 'currency' => 'RUB'],
        'total' => ['amount_minor' => 185000, 'currency' => 'RUB'],
        'customer' => [
            'full_name' => 'Иван Иванов',
            'phone' => '+7 (999) 111-22-33',
            'email' => 'ivan@example.ru'
        ],
        'delivery_method' => 'Доставка СДЭК',
        'delivery_address' => [
            'city' => 'Москва',
            'street' => 'ул. Ленина, д. 5',
            'country' => 'RU'
        ],
        'payment_method' => 'Банковская карта онлайн',
        'paid' => false,
        'custom_fields' => [
            'opencart_comment' => 'Позвонить перед доставкой',
            'opencart_ip' => '127.0.0.1'
        ]
    ]
];

$validation = $validator->validate('order', $oc3OrderPayload);
assert_true($validation['ok'], "OpenCart 3.0 order payload complies with PayloadValidator::validate('order')");

$rawOrderBody = json_encode($oc3OrderPayload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
$orderCanonical = "POST\n/_module/crm.ecommerce-gateway/v1/orders\n{$timestamp}\n{$nonce}\n" . hash('sha256', $rawOrderBody);
$orderSignature = base64_encode(hash_hmac('sha256', $orderCanonical, $secret, true));

$verifyOrder = SignatureService::verify(
    $secret,
    $orderSignature,
    'POST',
    '/_module/crm.ecommerce-gateway/v1/orders',
    $timestamp,
    $nonce,
    $rawOrderBody
);
assert_true($verifyOrder, "OpenCart 3.0 order POST signature verified by CRM SignatureService");

// Test OpenCart 3.0 inbound webhook verification
$webhookBody = json_encode([
    'event' => 'order.status_changed',
    'store_key' => $storeKey,
    'external_order_id' => '1042',
    'crm_task_public_id' => 'tsk_TEST123',
    'old_status' => 'new',
    'new_status' => 'completed',
    'external_status' => '5'
]);
$outboundSig = SignatureService::signOutbound($secret, $timestamp, $webhookBody);

$expectedInOc3 = base64_encode(hash_hmac('sha256', $timestamp . '.' . $webhookBody, $secret, true));
assert_true(hash_equals($expectedInOc3, $outboundSig), "OpenCart 3.0 webhook receiver validates outbound HMAC signature from CRM");


// --- 2. OpenCart 4.0 Connector Validation ---
echo "\n--- 2. OpenCart 4.0 Connector Contract & Signatures ---\n";

$oc4OrderPayload = $oc3OrderPayload;
$oc4OrderPayload['external_id'] = '2050';
$oc4OrderPayload['payload']['order_number'] = '2050';

$oc4Validation = $validator->validate('order', $oc4OrderPayload);
assert_true($oc4Validation['ok'], "OpenCart 4.0 order payload complies with PayloadValidator::validate('order')");

$oc4Raw = json_encode($oc4OrderPayload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
$oc4Canonical = "POST\n/_module/crm.ecommerce-gateway/v1/orders\n{$timestamp}\n{$nonce}\n" . hash('sha256', $oc4Raw);
$oc4Sig = base64_encode(hash_hmac('sha256', $oc4Canonical, $secret, true));

assert_true(
    SignatureService::verify($secret, $oc4Sig, 'POST', '/_module/crm.ecommerce-gateway/v1/orders', $timestamp, $nonce, $oc4Raw),
    "OpenCart 4.0 order POST signature verified by CRM SignatureService"
);


// --- 3. WooCommerce Connector Validation ---
echo "\n--- 3. WooCommerce Connector Contract & Signatures ---\n";

$wcOrderPayload = [
    'external_id' => '9981',
    'payload' => [
        'order_number' => 'WC-9981',
        'order_status' => 'processing',
        'items' => [
            [
                'name' => 'Кожаный кошелек Handmade',
                'sku' => 'WC-SKU-99',
                'quantity' => 1.0,
                'price' => ['amount_minor' => 200000, 'currency' => 'RUB'],
                'line_total' => ['amount_minor' => 200000, 'currency' => 'RUB'],
            ]
        ],
        'subtotal' => ['amount_minor' => 200000, 'currency' => 'RUB'],
        'discount_total' => ['amount_minor' => 20000, 'currency' => 'RUB'],
        'delivery_total' => ['amount_minor' => 45000, 'currency' => 'RUB'],
        'tax_total' => ['amount_minor' => 0, 'currency' => 'RUB'],
        'total' => ['amount_minor' => 225000, 'currency' => 'RUB'],
        'paid' => true,
        'customer' => [
            'full_name' => 'Анна Смирнова',
            'phone' => '+7 (916) 555-44-33',
            'email' => 'anna@smirnova.org'
        ],
        'delivery_method' => 'Курьерская доставка',
        'delivery_address' => [
            'country' => 'RU',
            'city' => 'Санкт-Петербург',
            'street' => 'Невский пр., д. 10 кв. 2',
            'postal_code' => '190000'
        ],
        'payment_method' => 'ЮKassa',
        'custom_fields' => [
            'customer_note' => 'Домофон 42B',
            'customer_ip' => '192.168.1.1'
        ]
    ]
];

$wcValidation = $validator->validate('order', $wcOrderPayload);
assert_true($wcValidation['ok'], "WooCommerce order payload complies with PayloadValidator::validate('order')");

$wcRaw = json_encode($wcOrderPayload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
$wcCanonical = "POST\n/_module/crm.ecommerce-gateway/v1/orders\n{$timestamp}\n{$nonce}\n" . hash('sha256', $wcRaw);
$wcSig = base64_encode(hash_hmac('sha256', $wcCanonical, $secret, true));

assert_true(
    SignatureService::verify($secret, $wcSig, 'POST', '/_module/crm.ecommerce-gateway/v1/orders', $timestamp, $nonce, $wcRaw),
    "WooCommerce order POST signature verified by CRM SignatureService"
);

// WooCommerce webhook handler HMAC verification
$wcExpectedSig = base64_encode(hash_hmac('sha256', $timestamp . '.' . $webhookBody, $secret, true));
assert_true(hash_equals($wcExpectedSig, $outboundSig), "WooCommerce webhook handler validates outbound HMAC signature from CRM");


// --- 4. Distribution Packages Verification ---
echo "\n--- 4. Distribution Packages (.zip & .ocmod.zip) ---\n";

$distDir = dirname(__DIR__) . '/connectors/dist';

$oc3Pkg = $distDir . '/tropatt-opencart-3.ocmod.zip';
assert_true(file_exists($oc3Pkg) && filesize($oc3Pkg) > 1000, "tropatt-opencart-3.ocmod.zip package exists and is non-empty");

$oc4Pkg = $distDir . '/tropatt-opencart-4.ocmod.zip';
assert_true(file_exists($oc4Pkg) && filesize($oc4Pkg) > 1000, "tropatt-opencart-4.ocmod.zip package exists and is non-empty");

$wcPkg = $distDir . '/tropatt-woocommerce.zip';
assert_true(file_exists($wcPkg) && filesize($wcPkg) > 1000, "tropatt-woocommerce.zip package exists and is non-empty");

// Verify zip contents
$zip = new ZipArchive();
if ($zip->open($oc3Pkg) === true) {
    assert_true($zip->locateName('upload/admin/controller/extension/module/tropatt.php') !== false, "OpenCart 3 zip contains admin controller");
    assert_true($zip->locateName('upload/catalog/controller/extension/module/tropatt.php') !== false, "OpenCart 3 zip contains catalog controller");
    assert_true($zip->locateName('upload/admin/view/template/extension/module/tropatt.twig') !== false, "OpenCart 3 zip contains Twig template");
    $zip->close();
} else {
    assert_true(false, "Failed to open OpenCart 3 zip archive");
}

if ($zip->open($oc4Pkg) === true) {
    assert_true($zip->locateName('extension/tropatt/admin/controller/module/tropatt.php') !== false, "OpenCart 4 zip contains admin controller");
    assert_true($zip->locateName('extension/tropatt/catalog/controller/module/tropatt.php') !== false, "OpenCart 4 zip contains catalog controller");
    $zip->close();
} else {
    assert_true(false, "Failed to open OpenCart 4 zip archive");
}

if ($zip->open($wcPkg) === true) {
    assert_true($zip->locateName('tropatt-ecommerce/tropatt-ecommerce.php') !== false, "WooCommerce zip contains root plugin entry");
    assert_true($zip->locateName('tropatt-ecommerce/includes/class-tropatt-client.php') !== false, "WooCommerce zip contains client class");
    assert_true($zip->locateName('tropatt-ecommerce/includes/class-tropatt-webhook-handler.php') !== false, "WooCommerce zip contains webhook handler");
    $zip->close();
} else {
    assert_true(false, "Failed to open WooCommerce zip archive");
}

echo "\n=======================================================\n";
echo "Total Tests Run: " . ($passed + $failed) . "\n";
echo "Tests Passed: {$passed}/" . ($passed + $failed) . "\n";
if ($failed === 0) {
    echo "ALL CONNECTOR CONTRACT & COMPATIBILITY TESTS PASSED 100%!\n";
} else {
    echo "SOME TESTS FAILED!\n";
    exit(1);
}
echo "=======================================================\n";
