<?php
declare(strict_types=1);

namespace Module\Crm\Bitrix24Migration\Repository;

use PDO;

final class Bitrix24MigrationRepository
{
    public function __construct(private readonly PDO $pdo) {}
    private function id(string $prefix): string { return $prefix . '_' . bin2hex(random_bytes(10)); }
    private function now(): string { return gmdate('Y-m-d H:i:s'); }
    private function json(mixed $value): string { return (string)json_encode($value, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES); }

    public function actor(int $id): array
    {
        $stmt=$this->pdo->prepare('SELECT id,public_id,login,full_name,is_root,is_active FROM users WHERE id=:id LIMIT 1');$stmt->execute(['id'=>$id]);
        return ($row=$stmt->fetch(PDO::FETCH_ASSOC))?:['id'=>$id,'is_root'=>0];
    }
    public function activeUserPublicId(string $id): ?string { $s=$this->pdo->prepare('SELECT public_id FROM users WHERE public_id=:id AND is_active=1 LIMIT 1');$s->execute(['id'=>$id]);$v=$s->fetchColumn();return$v===false?null:(string)$v; }

    public function listConnections(int $actorId,bool $manager): array { $sql='SELECT id,public_id,name,auth_type,portal_url,status,last_checked_at,last_error,created_by_user_id,created_at,updated_at FROM module_bitrix24_connections';$p=[];if(!$manager){$sql.=' WHERE created_by_user_id=:o';$p['o']=$actorId;}$sql.=' ORDER BY created_at DESC';$s=$this->pdo->prepare($sql);$s->execute($p);return$s->fetchAll(PDO::FETCH_ASSOC)?:[]; }
    public function getConnection(string $id): ?array { $s=$this->pdo->prepare('SELECT * FROM module_bitrix24_connections WHERE public_id=:id LIMIT 1');$s->execute(['id'=>$id]);$r=$s->fetch(PDO::FETCH_ASSOC);return is_array($r)?$r:null; }
    public function getConnectionById(int $id): ?array { $s=$this->pdo->prepare('SELECT * FROM module_bitrix24_connections WHERE id=:id LIMIT 1');$s->execute(['id'=>$id]);$r=$s->fetch(PDO::FETCH_ASSOC);return is_array($r)?$r:null; }
    public function createConnection(array $d): array { $id=$this->id('b24c');$now=$this->now();$s=$this->pdo->prepare("INSERT INTO module_bitrix24_connections (public_id,name,auth_type,portal_url,webhook_url_encrypted,access_token_encrypted,refresh_token_encrypted,client_id_encrypted,client_secret_encrypted,status,created_by_user_id,created_at,updated_at) VALUES (:p,:n,:a,:u,:w,:at,:rt,:ci,:cs,'draft',:o,:cr,:up)");$s->execute(['p'=>$id,'n'=>$d['name'],'a'=>$d['auth_type'],'u'=>$d['portal_url'],'w'=>$d['webhook_url_encrypted']??null,'at'=>$d['access_token_encrypted']??null,'rt'=>$d['refresh_token_encrypted']??null,'ci'=>$d['client_id_encrypted']??null,'cs'=>$d['client_secret_encrypted']??null,'o'=>$d['created_by_user_id'],'cr'=>$now,'up'=>$now]);return$this->getConnection($id)??['public_id'=>$id]; }
    public function updateConnection(string $id,array $d): void { $allowed=['name','portal_url','webhook_url_encrypted','access_token_encrypted','refresh_token_encrypted','client_id_encrypted','client_secret_encrypted'];$set=[];$p=['id'=>$id,'u'=>$this->now()];foreach($allowed as $f)if(array_key_exists($f,$d)){$set[]=$f.'=:'.$f;$p[$f]=$d[$f];}if($set===[])return;$set[]='updated_at=:u';$this->pdo->prepare('UPDATE module_bitrix24_connections SET '.implode(',',$set).' WHERE public_id=:id')->execute($p); }
    public function updateConnectionCheck(string $id,bool $ok,string $error=''): void { $s=$this->pdo->prepare('UPDATE module_bitrix24_connections SET status=:s,last_checked_at=UTC_TIMESTAMP(),last_error=:e,updated_at=UTC_TIMESTAMP() WHERE public_id=:id');$s->execute(['s'=>$ok?'active':'failed','e'=>$error!==''?mb_substr($error,0,1000):null,'id'=>$id]); }
    public function updateOAuthTokens(int $id,string $access,string $refresh): void { $this->pdo->prepare('UPDATE module_bitrix24_connections SET access_token_encrypted=:a,refresh_token_encrypted=:r,updated_at=UTC_TIMESTAMP() WHERE id=:id')->execute(['a'=>$access,'r'=>$refresh,'id'=>$id]); }

    public function hasRunningJobs(int $connection): bool { $s=$this->pdo->prepare("SELECT id FROM module_bitrix24_jobs WHERE connection_id=:c AND status IN ('queued','running','pausing','cancelling','rolling_back') LIMIT 1");$s->execute(['c'=>$connection]);return$s->fetchColumn()!==false; }
    public function deleteConnection(int $connection): void { $this->pdo->beginTransaction();try{foreach(['module_bitrix24_unresolved_entities'=>'job_id IN (SELECT id FROM module_bitrix24_jobs WHERE connection_id=:c)','module_bitrix24_job_logs'=>'job_id IN (SELECT id FROM module_bitrix24_jobs WHERE connection_id=:c)','module_bitrix24_job_items'=>'job_id IN (SELECT id FROM module_bitrix24_jobs WHERE connection_id=:c)','module_bitrix24_jobs'=>'connection_id=:c','module_bitrix24_source_mappings'=>'connection_id=:c','module_bitrix24_user_mappings'=>'connection_id=:c','module_bitrix24_rate_limits'=>'connection_id=:c'] as $t=>$w)$this->pdo->prepare('DELETE FROM '.$t.' WHERE '.$w)->execute(['c'=>$connection]);$this->pdo->prepare('DELETE FROM module_bitrix24_connections WHERE id=:c')->execute(['c'=>$connection]);$this->pdo->commit();}catch(\Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw$e;} }

    private function decodeJob(array $r): array { foreach(['source_scope_json'=>'source_scope','target_options_json'=>'target_options','progress_json'=>'progress','summary_json'=>'summary'] as $a=>$b)if(array_key_exists($a,$r))$r[$b]=json_decode((string)$r[$a],true)?:[];return$r; }
    public function createJob(array $d): array { $id=$this->id('b24j');$now=$this->now();$s=$this->pdo->prepare("INSERT INTO module_bitrix24_jobs (public_id,connection_id,mode,status,source_scope_json,target_options_json,created_by_user_id,created_at,updated_at) VALUES (:p,:c,:m,'draft',:s,:o,:u,:cr,:up)");$s->execute(['p'=>$id,'c'=>$d['connection_id'],'m'=>$d['mode']??'import','s'=>$this->json($d['source_scope']??[]),'o'=>$this->json($d['target_options']??[]),'u'=>$d['created_by_user_id'],'cr'=>$now,'up'=>$now]);return$this->getJob($id)??['public_id'=>$id]; }
    public function getJob(string $id): ?array { $s=$this->pdo->prepare('SELECT j.*,c.name AS connection_name FROM module_bitrix24_jobs j JOIN module_bitrix24_connections c ON c.id=j.connection_id WHERE j.public_id=:id LIMIT 1');$s->execute(['id'=>$id]);$r=$s->fetch(PDO::FETCH_ASSOC);return is_array($r)?$this->decodeJob($r):null; }
    public function listJobs(int $actorId,bool $manager): array { $sql='SELECT j.*,c.name AS connection_name FROM module_bitrix24_jobs j JOIN module_bitrix24_connections c ON c.id=j.connection_id';$p=[];if(!$manager){$sql.=' WHERE j.created_by_user_id=:o';$p['o']=$actorId;}$sql.=' ORDER BY j.created_at DESC';$s=$this->pdo->prepare($sql);$s->execute($p);return array_map([$this,'decodeJob'],$s->fetchAll(PDO::FETCH_ASSOC)?:[]); }

    public function requestStatus(string $id,string $status): bool { $allowed="'draft','queued','running','paused','pausing','cancelling','failed','cancelled','completed_with_warnings'";$set='status=:s,updated_at=UTC_TIMESTAMP()';if($status==='cancelled')$set.=',finished_at=UTC_TIMESTAMP(),lease_token=NULL,lease_until=NULL';$s=$this->pdo->prepare("UPDATE module_bitrix24_jobs SET {$set} WHERE public_id=:id AND status IN ({$allowed})");$s->execute(['s'=>$status,'id'=>$id]);return$s->rowCount()===1; }
    public function updateJobStatus(string $id,string $status,?string $lease=null): void { $set=['status=:s','updated_at=UTC_TIMESTAMP()'];$p=['id'=>$id,'s'=>$status];if(in_array($status,['queued','running'],true))$set[]='started_at=COALESCE(started_at,UTC_TIMESTAMP())';if(in_array($status,['completed','completed_with_warnings','failed','cancelled','rolled_back','rolled_back_with_warnings','rollback_failed'],true))$set[]='finished_at=UTC_TIMESTAMP()';$where=' WHERE public_id=:id';if($lease!==null){$where.=" AND lease_token=:l AND lease_until>=UTC_TIMESTAMP() AND status IN ('running','pausing','cancelling','rolling_back')";$p['l']=$lease;}$s=$this->pdo->prepare('UPDATE module_bitrix24_jobs SET '.implode(',',$set).$where);$s->execute($p);if($lease!==null&&!$this->ownsLease($id,$lease))throw new \RuntimeException('BITRIX24_JOB_LEASE_LOST'); }
    public function claimNextJob(int $seconds=240): ?array { $this->pdo->beginTransaction();try{$s=$this->pdo->query("SELECT id FROM module_bitrix24_jobs WHERE status='queued' OR (status IN ('running','pausing','cancelling') AND lease_until<UTC_TIMESTAMP()) ORDER BY created_at ASC LIMIT 1 FOR UPDATE");$id=$s->fetchColumn();if($id===false){$this->pdo->commit();return null;}$l=bin2hex(random_bytes(16));$u=gmdate('Y-m-d H:i:s',time()+max(60,$seconds));$this->pdo->prepare("UPDATE module_bitrix24_jobs SET status=CASE WHEN status='queued' THEN 'running' ELSE status END,lease_token=:l,lease_until=:u,started_at=COALESCE(started_at,UTC_TIMESTAMP()),updated_at=UTC_TIMESTAMP() WHERE id=:id")->execute(['l'=>$l,'u'=>$u,'id'=>$id]);$this->pdo->commit();$s=$this->pdo->prepare('SELECT j.*,c.name AS connection_name FROM module_bitrix24_jobs j JOIN module_bitrix24_connections c ON c.id=j.connection_id WHERE j.id=:id');$s->execute(['id'=>$id]);$r=$s->fetch(PDO::FETCH_ASSOC);return is_array($r)?$this->decodeJob($r):null;}catch(\Throwable$e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw$e;} }
    public function heartbeat(string $id,string $lease,int $seconds=240): bool { $s=$this->pdo->prepare("UPDATE module_bitrix24_jobs SET lease_until=:u,updated_at=UTC_TIMESTAMP() WHERE public_id=:id AND lease_token=:l AND status IN ('running','pausing','cancelling')");$s->execute(['u'=>gmdate('Y-m-d H:i:s',time()+max(60,$seconds)),'id'=>$id,'l'=>$lease]);return$this->ownsLease($id,$lease); }
    public function ownsLease(string $id,string $lease): bool { $s=$this->pdo->prepare("SELECT id FROM module_bitrix24_jobs WHERE public_id=:id AND lease_token=:l AND lease_until>=UTC_TIMESTAMP() AND status IN ('running','pausing','cancelling','rolling_back') LIMIT 1");$s->execute(['id'=>$id,'l'=>$lease]);return$s->fetchColumn()!==false; }
    public function releaseLease(string $id,string $lease): void {$this->pdo->prepare('UPDATE module_bitrix24_jobs SET lease_token=NULL,lease_until=NULL,updated_at=UTC_TIMESTAMP() WHERE public_id=:id AND lease_token=:l')->execute(['id'=>$id,'l'=>$lease]);}
    public function updateProgress(string $id,string $step,float $percent,array $progress,?string $lease=null): void {$p=['id'=>$id,'s'=>$step,'pc'=>max(0,min(100,$percent)),'pr'=>$this->json($progress)];$where=' WHERE public_id=:id';if($lease!==null){$where.=" AND lease_token=:l AND lease_until>=UTC_TIMESTAMP() AND status IN ('running','pausing','cancelling')";$p['l']=$lease;}$this->pdo->prepare('UPDATE module_bitrix24_jobs SET current_step=:s,progress_percent=:pc,progress_json=:pr,updated_at=UTC_TIMESTAMP()'.$where)->execute($p);if($lease!==null&&!$this->ownsLease($id,$lease))throw new \RuntimeException('BITRIX24_JOB_LEASE_LOST');}
    public function updateSummary(string $id,array $summary,?string $lease=null): void {$p=['id'=>$id,'s'=>$this->json($summary)];$where=' WHERE public_id=:id';if($lease!==null){$where.=" AND lease_token=:l AND lease_until>=UTC_TIMESTAMP() AND status IN ('running','pausing','cancelling')";$p['l']=$lease;}$this->pdo->prepare('UPDATE module_bitrix24_jobs SET summary_json=:s,updated_at=UTC_TIMESTAMP()'.$where)->execute($p);if($lease!==null&&!$this->ownsLease($id,$lease))throw new \RuntimeException('BITRIX24_JOB_LEASE_LOST');}
    public function updateCursor(string $id,array $cursor,?string $lease=null): void {$p=['id'=>$id,'c'=>$this->json($cursor)];$where=' WHERE public_id=:id';if($lease!==null){$where.=" AND lease_token=:l AND lease_until>=UTC_TIMESTAMP() AND status IN ('running','pausing','cancelling')";$p['l']=$lease;}$this->pdo->prepare('UPDATE module_bitrix24_jobs SET last_source_cursor=:c,updated_at=UTC_TIMESTAMP()'.$where)->execute($p);if($lease!==null&&!$this->ownsLease($id,$lease))throw new \RuntimeException('BITRIX24_JOB_LEASE_LOST');}

    public function findItem(int $job,string $type,string $source): ?array {$s=$this->pdo->prepare('SELECT * FROM module_bitrix24_job_items WHERE job_id=:j AND source_type=:t AND source_id=:s LIMIT 1');$s->execute(['j'=>$job,'t'=>$type,'s'=>$source]);$r=$s->fetch(PDO::FETCH_ASSOC);return is_array($r)?$r:null;}
    public function upsertItem(int $job,string $type,string $source,array $d): void {$old=$this->findItem($job,$type,$source);$fields=['source_parent_id','target_type','target_public_id','created_by_job','status','checksum','source_updated_at','payload_json','attempts','error_code','error_message'];if($old){if(($d['status']??null)==='pending'&&(string)($old['checksum']??'')===(string)($d['checksum']??'')&&in_array((string)$old['status'],['imported','updated','skipped'],true))unset($d['status']);$set=['updated_at=UTC_TIMESTAMP()'];$p=['id'=>$old['id']];foreach($fields as $f)if(array_key_exists($f,$d)){$set[]=$f.'=:'.$f;$p[$f]=$f==='payload_json'&&is_array($d[$f])?$this->json($d[$f]):$d[$f];}$this->pdo->prepare('UPDATE module_bitrix24_job_items SET '.implode(',',$set).' WHERE id=:id')->execute($p);return;}$s=$this->pdo->prepare('INSERT INTO module_bitrix24_job_items (job_id,source_type,source_id,source_parent_id,target_type,target_public_id,created_by_job,status,checksum,source_updated_at,attempts,error_code,error_message,payload_json,created_at,updated_at) VALUES (:j,:t,:s,:p,:tt,:tp,:cb,:st,:c,:su,:a,:ec,:em,:pl,UTC_TIMESTAMP(),UTC_TIMESTAMP())');$s->execute(['j'=>$job,'t'=>$type,'s'=>$source,'p'=>$d['source_parent_id']??null,'tt'=>$d['target_type']??null,'tp'=>$d['target_public_id']??null,'cb'=>!empty($d['created_by_job'])?1:0,'st'=>$d['status']??'pending','c'=>$d['checksum']??null,'su'=>$d['source_updated_at']??null,'a'=>$d['attempts']??0,'ec'=>$d['error_code']??null,'em'=>$d['error_message']??null,'pl'=>isset($d['payload_json'])?(is_array($d['payload_json'])?$this->json($d['payload_json']):$d['payload_json']):null]);}
    public function items(int $job,?string $status=null,int $limit=1000): array {$sql='SELECT * FROM module_bitrix24_job_items WHERE job_id=:j';$p=['j'=>$job];if($status!==null&&$status!==''){$sql.=' AND status=:s';$p['s']=$status;}$sql.=' ORDER BY id ASC LIMIT '.max(1,min(10000,$limit));$s=$this->pdo->prepare($sql);$s->execute($p);return$s->fetchAll(PDO::FETCH_ASSOC)?:[];}
    public function itemCounts(int $job): array {$s=$this->pdo->prepare('SELECT status,COUNT(*) AS count FROM module_bitrix24_job_items WHERE job_id=:j GROUP BY status');$s->execute(['j'=>$job]);$r=[];foreach($s->fetchAll(PDO::FETCH_ASSOC)?:[] as $row)$r[(string)$row['status']]=(int)$row['count'];return$r;}
    public function importItemsBatch(int $job,int $priority=0,int $lastId=0,int $limit=100): array {$sql="SELECT * FROM (SELECT i.*,CASE i.source_type WHEN 'department' THEN 10 WHEN 'user' THEN 15 WHEN 'company' THEN 20 WHEN 'contact' THEN 25 WHEN 'lead' THEN 30 WHEN 'project' THEN 35 WHEN 'task_project' THEN 35 WHEN 'deal' THEN 40 WHEN 'task' THEN 50 WHEN 'subtask' THEN 55 WHEN 'comment' THEN 60 WHEN 'timeline_comment' THEN 60 WHEN 'activity' THEN 65 WHEN 'event' THEN 65 WHEN 'file' THEN 70 WHEN 'product' THEN 80 WHEN 'invoice' THEN 85 WHEN 'quote' THEN 85 ELSE 90 END AS import_priority FROM module_bitrix24_job_items i WHERE i.job_id=:j AND i.status='pending') x WHERE x.import_priority>:p OR (x.import_priority=:p AND x.id>:i) ORDER BY x.import_priority ASC,x.id ASC LIMIT ".max(1,min(500,$limit))."";$s=$this->pdo->prepare($sql);$s->execute(['j'=>$job,'p'=>$priority,'i'=>$lastId]);return$s->fetchAll(PDO::FETCH_ASSOC)?:[];}
    public function findMapping(int $connection,string $type,string $source): ?array {$s=$this->pdo->prepare('SELECT * FROM module_bitrix24_source_mappings WHERE connection_id=:c AND source_type=:t AND source_id=:s LIMIT 1');$s->execute(['c'=>$connection,'t'=>$type,'s'=>$source]);$r=$s->fetch(PDO::FETCH_ASSOC);return is_array($r)?$r:null;}
    public function upsertMapping(int $connection,string $type,string $source,array $d): array {$old=$this->findMapping($connection,$type,$source);$now=$this->now();if($old){$s=$this->pdo->prepare('UPDATE module_bitrix24_source_mappings SET source_parent_id=:p,target_type=:tt,target_public_id=:tp,source_checksum=:sc,state=:st,created_by_job_id=COALESCE(created_by_job_id,:j),last_seen_at=:ls,updated_at=:u WHERE id=:i');$s->execute(['p'=>$d['source_parent_id']??$old['source_parent_id'],'tt'=>$d['target_type']??$old['target_type'],'tp'=>$d['target_public_id']??$old['target_public_id'],'sc'=>$d['source_checksum']??$old['source_checksum'],'st'=>$d['state']??'active','j'=>$d['created_by_job_id']??$old['created_by_job_id'],'ls'=>$now,'u'=>$now,'i'=>$old['id']]);return$this->findMapping($connection,$type,$source)??$old;}$id=$this->id('b24m');$s=$this->pdo->prepare('INSERT INTO module_bitrix24_source_mappings (public_id,connection_id,source_type,source_id,source_parent_id,target_type,target_public_id,source_checksum,state,created_by_job_id,last_seen_at,created_at,updated_at) VALUES (:i,:c,:t,:s,:p,:tt,:tp,:sc,:st,:j,:ls,:cr,:u)');$s->execute(['i'=>$id,'c'=>$connection,'t'=>$type,'s'=>$source,'p'=>$d['source_parent_id']??null,'tt'=>$d['target_type']??null,'tp'=>$d['target_public_id']??null,'sc'=>$d['source_checksum']??null,'st'=>$d['state']??'active','j'=>$d['created_by_job_id']??null,'ls'=>$now,'cr'=>$now,'u'=>$now]);return$this->findMapping($connection,$type,$source)??['public_id'=>$id];}
    public function markMappingRolledBack(int $connection,string $type,string $source): void {$this->pdo->prepare("UPDATE module_bitrix24_source_mappings SET target_type=NULL,target_public_id=NULL,state='rolled_back',updated_at=UTC_TIMESTAMP() WHERE connection_id=:c AND source_type=:t AND source_id=:s")->execute(['c'=>$connection,'t'=>$type,'s'=>$source]);}
    public function upsertUserMapping(int $connection,array $user): void {$id=trim((string)($user['ID']??$user['id']??''));if($id==='')return;$name=trim(implode(' ',array_filter([(string)($user['NAME']??''),(string)($user['LAST_NAME']??''),(string)($user['SECOND_NAME']??'')])))?:($user['FULL_NAME']??$user['name']??$id);$s=$this->pdo->prepare("INSERT INTO module_bitrix24_user_mappings (connection_id,bitrix_user_id,display_name,email,mapping_status,created_at,updated_at) VALUES (:c,:i,:n,:e,'unmapped',UTC_TIMESTAMP(),UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE display_name=VALUES(display_name),email=VALUES(email),updated_at=UTC_TIMESTAMP()");$s->execute(['c'=>$connection,'i'=>$id,'n'=>mb_substr($name,0,255),'e'=>$user['EMAIL']??$user['email']??null]);}
    public function mappedUserId(int $connection,string $source): ?int {$s=$this->pdo->prepare("SELECT u.id FROM module_bitrix24_user_mappings m JOIN users u ON u.public_id=m.crm_user_public_id WHERE m.connection_id=:c AND m.bitrix_user_id=:i AND m.mapping_status='mapped' AND u.is_active=1 LIMIT 1");$s->execute(['c'=>$connection,'i'=>$source]);$v=$s->fetchColumn();return$v===false?null:(int)$v;}
    public function listUserMappings(int $connection): array {$s=$this->pdo->prepare('SELECT * FROM module_bitrix24_user_mappings WHERE connection_id=:c ORDER BY display_name ASC');$s->execute(['c'=>$connection]);return$s->fetchAll(PDO::FETCH_ASSOC)?:[];}
    public function updateUserMapping(int $connection,int $id,?string $crm): bool {$s=$this->pdo->prepare("UPDATE module_bitrix24_user_mappings SET crm_user_public_id=:u,mapping_status=:s,updated_at=UTC_TIMESTAMP() WHERE id=:i AND connection_id=:c");$s->execute(['u'=>$crm?:null,'s'=>$crm?'mapped':'unmapped','i'=>$id,'c'=>$connection]);if($s->rowCount()>0)return true;$s=$this->pdo->prepare('SELECT id FROM module_bitrix24_user_mappings WHERE id=:i AND connection_id=:c');$s->execute(['i'=>$id,'c'=>$connection]);return$s->fetchColumn()!==false;}
    public function addLog(int $job,string $level,string $step,string $message,array $context=[]): void {$s=$this->pdo->prepare('INSERT INTO module_bitrix24_job_logs (job_id,level,step,message,context_json,created_at) VALUES (:j,:l,:s,:m,:c,UTC_TIMESTAMP())');$s->execute(['j'=>$job,'l'=>$level,'s'=>$step,'m'=>mb_substr($message,0,2000),'c'=>$context===[]?null:$this->json($context)]);}
    public function logs(int $job,int $limit=100): array {$s=$this->pdo->prepare('SELECT * FROM module_bitrix24_job_logs WHERE job_id=:j ORDER BY id DESC LIMIT '.max(1,min(1000,$limit)));$s->execute(['j'=>$job]);return$s->fetchAll(PDO::FETCH_ASSOC)?:[];}
    public function unresolved(int $job,string $type,string $source,string $reason,string $text,array $payload=[]): void {$this->pdo->prepare('DELETE FROM module_bitrix24_unresolved_entities WHERE job_id=:j AND source_type=:t AND source_id=:s AND reason_code=:r')->execute(['j'=>$job,'t'=>$type,'s'=>$source,'r'=>$reason]);$this->pdo->prepare('INSERT INTO module_bitrix24_unresolved_entities (job_id,source_type,source_id,reason_code,reason_text,payload_json,created_at) VALUES (:j,:t,:s,:r,:x,:p,UTC_TIMESTAMP())')->execute(['j'=>$job,'t'=>$type,'s'=>$source,'r'=>$reason,'x'=>mb_substr($text,0,2000),'p'=>$payload===[]?null:$this->json($payload)]);}
    public function unresolvedItems(int $job): array {$s=$this->pdo->prepare('SELECT * FROM module_bitrix24_unresolved_entities WHERE job_id=:j ORDER BY id DESC LIMIT 1000');$s->execute(['j'=>$job]);return$s->fetchAll(PDO::FETCH_ASSOC)?:[];}
    public function report(string $id): array {$j=$this->getJob($id);if(!$j)return[];$j['items']=$this->itemCounts((int)$j['id']);$j['logs']=$this->logs((int)$j['id']);$j['unresolved']=$this->unresolvedItems((int)$j['id']);return$j;}
    public function resetFailed(string $id): ?int {$s=$this->pdo->prepare("SELECT id,status FROM module_bitrix24_jobs WHERE public_id=:p AND status IN ('failed','completed_with_warnings','cancelled') LIMIT 1");$s->execute(['p'=>$id]);$j=$s->fetch(PDO::FETCH_ASSOC);if(!is_array($j))return null;$u=$this->pdo->prepare("UPDATE module_bitrix24_job_items SET status='pending',error_code=NULL,error_message=NULL WHERE job_id=:j AND status='failed'");$u->execute(['j'=>$j['id']]);$n=$u->rowCount();$this->pdo->prepare("UPDATE module_bitrix24_jobs SET status='queued',last_source_cursor=:c,current_step='import_retry',finished_at=NULL,updated_at=UTC_TIMESTAMP() WHERE id=:j")->execute(['c'=>$this->json(['phase'=>'import','priority'=>0,'id'=>0]),'j'=>$j['id']]);return$n;}
    public function rateState(int $id): ?array {$s=$this->pdo->prepare('SELECT * FROM module_bitrix24_rate_limits WHERE connection_id=:c LIMIT 1');$s->execute(['c'=>$id]);$r=$s->fetch(PDO::FETCH_ASSOC);return is_array($r)?$r:null;}
    public function attempts(int $id): int { $r=$this->rateState($id);return(int)($r['requests_made']??0); }
    public function recordRequest(int $id,int $status,array $headers): void {$r=$this->rateState($id)?:[];$this->upsertRate($id,['requests_made'=>(int)($r['requests_made']??0)+1,'window_started_at'=>$r['window_started_at']??$this->now(),'retry_after_until'=>$r['retry_after_until']??null,'last_http_status'=>$status]);}
    public function recordRetryAfter(int $id,int $seconds): void {$r=$this->rateState($id)?:[];$this->upsertRate($id,array_merge($r,['retry_after_until'=>gmdate('Y-m-d H:i:s',time()+max(1,$seconds))]));}
    private function upsertRate(int $id,array $d): void {$s=$this->pdo->prepare('INSERT INTO module_bitrix24_rate_limits (connection_id,requests_made,window_started_at,retry_after_until,last_http_status,updated_at) VALUES (:c,:n,:w,:r,:s,UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE requests_made=VALUES(requests_made),window_started_at=VALUES(window_started_at),retry_after_until=VALUES(retry_after_until),last_http_status=VALUES(last_http_status),updated_at=UTC_TIMESTAMP()');$s->execute(['c'=>$id,'n'=>(int)($d['requests_made']??0),'w'=>$d['window_started_at']??$this->now(),'r'=>$d['retry_after_until']??null,'s'=>$d['last_http_status']??null]);}
}
