<?php declare(strict_types=1); ?>
<?php $title = $t('admin_roles.title', 'TropaTT — Роли пользователей'); ?>
<body data-page="admin" data-protected="1"><div class="crm-app"><aside class="crm-sidebar"><div class="crm-brand"><span class="crm-brand-mark"></span> <?= htmlspecialchars($t('app.name', 'TropaTT'), ENT_QUOTES, 'UTF-8') ?></div><nav class="nav flex-column crm-nav"></nav></aside>
<div class="crm-main-wrap"><header class="crm-topbar py-2"><div class="container-fluid"></div></header>
<main class="crm-content crm-admin-page"><div class="crm-page-head"><div><ol class="breadcrumb mb-1"><li class="breadcrumb-item"><a href="index.php?route=admin" data-i18n="nav.admin"><?= htmlspecialchars($t('nav.admin', 'Администрирование'), ENT_QUOTES, 'UTF-8') ?></a></li><li class="breadcrumb-item active" data-i18n="admin_roles.page_title"><?= htmlspecialchars($t('admin_roles.page_title', 'Роли'), ENT_QUOTES, 'UTF-8') ?></li></ol><h1 class="crm-page-title" data-i18n="admin_roles.page_title"><?= htmlspecialchars($t('admin_roles.page_title', 'Роли'), ENT_QUOTES, 'UTF-8') ?></h1><p class="crm-subtitle" data-i18n="admin_roles.subtitle"><?= htmlspecialchars($t('admin_roles.subtitle', 'Роли пользователей и наборы прав доступа.'), ENT_QUOTES, 'UTF-8') ?></p></div><div class="d-flex gap-2"><button class="btn crm-btn-primary" id="roleCreateOpenBtn" type="button" data-i18n="admin_roles.create_btn"><?= htmlspecialchars($t('admin_roles.create_btn', 'Создать роль'), ENT_QUOTES, 'UTF-8') ?></button></div></div>

<div class="row g-3 mb-3 crm-kpi-row"><div class="col-md-4"><div class="crm-card crm-kpi-card"><small class="text-muted" data-i18n="admin_roles.kpi_total"><?= htmlspecialchars($t('admin_roles.kpi_total', 'Всего ролей'), ENT_QUOTES, 'UTF-8') ?></small><h2 class="h4 mb-0" id="rolesMetricTotal">0</h2></div></div><div class="col-md-4"><div class="crm-card crm-kpi-card"><small class="text-muted" data-i18n="admin_roles.kpi_custom"><?= htmlspecialchars($t('admin_roles.kpi_custom', 'Кастомных ролей'), ENT_QUOTES, 'UTF-8') ?></small><h2 class="h4 mb-0" id="rolesMetricCustom">0</h2></div></div><div class="col-md-4"><div class="crm-card crm-kpi-card"><small class="text-muted" data-i18n="admin_roles.kpi_system"><?= htmlspecialchars($t('admin_roles.kpi_system', 'Системных ролей'), ENT_QUOTES, 'UTF-8') ?></small><h2 class="h4 mb-0" id="rolesMetricSystem">0</h2></div></div></div>

<div class="crm-card crm-section-card p-0 table-responsive"><table class="table crm-table mb-0"><thead><tr><th data-i18n="admin_roles.th_role"><?= htmlspecialchars($t('admin_roles.th_role', 'Роль'), ENT_QUOTES, 'UTF-8') ?></th><th data-i18n="admin_roles.th_permissions"><?= htmlspecialchars($t('admin_roles.th_permissions', 'Доступы'), ENT_QUOTES, 'UTF-8') ?></th><th data-i18n="admin_roles.th_type"><?= htmlspecialchars($t('admin_roles.th_type', 'Тип'), ENT_QUOTES, 'UTF-8') ?></th><th data-i18n="admin_roles.th_updated"><?= htmlspecialchars($t('admin_roles.th_updated', 'Изменено'), ENT_QUOTES, 'UTF-8') ?></th><th style="width:170px" data-i18n="admin_roles.th_actions"><?= htmlspecialchars($t('admin_roles.th_actions', 'Действия'), ENT_QUOTES, 'UTF-8') ?></th></tr></thead><tbody id="adminRolesTableBody"><tr><td colspan="5" class="text-muted" data-i18n="admin_roles.loading"><?= htmlspecialchars($t('admin_roles.loading', 'Загрузка ролей...'), ENT_QUOTES, 'UTF-8') ?></td></tr></tbody></table></div>

<div class="modal fade" id="roleCreateModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" data-i18n="admin_roles.modal_create_title"><?= htmlspecialchars($t('admin_roles.modal_create_title', 'Создать роль'), ENT_QUOTES, 'UTF-8') ?></h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="<?= htmlspecialchars($t('page.close', 'Закрыть'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-aria-label="page.close"></button></div><form id="roleCreateForm"><div class="modal-body"><div class="row g-2 mb-3"><div class="col-md-6"><label class="form-label" data-i18n="admin_roles.field_code"><?= htmlspecialchars($t('admin_roles.field_code', 'Код роли'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="code" maxlength="64" placeholder="<?= htmlspecialchars($t('admin_roles.placeholder_code', 'qa_lead'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-placeholder="admin_roles.placeholder_code"></div><div class="col-md-6"><label class="form-label" data-i18n="admin_roles.field_title"><?= htmlspecialchars($t('admin_roles.field_title', 'Название роли'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="title" maxlength="255" placeholder="<?= htmlspecialchars($t('admin_roles.placeholder_title', 'Руководитель QA'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-placeholder="admin_roles.placeholder_title"></div></div><label class="form-label" data-i18n="admin_roles.field_permissions"><?= htmlspecialchars($t('admin_roles.field_permissions', 'Доступы'), ENT_QUOTES, 'UTF-8') ?></label><div class="border rounded p-2 crm-max-h-320 crm-overflow-auto" id="roleCreatePermissionsList"><div class="text-muted" data-i18n="admin_roles.loading_permissions"><?= htmlspecialchars($t('admin_roles.loading_permissions', 'Загрузка доступов...'), ENT_QUOTES, 'UTF-8') ?></div></div></div><div class="modal-footer"><button class="btn crm-btn-secondary" type="button" data-bs-dismiss="modal" data-i18n="page.cancel"><?= htmlspecialchars($t('page.cancel', 'Отмена'), ENT_QUOTES, 'UTF-8') ?></button><button class="btn crm-btn-primary" type="submit" data-i18n="page.create"><?= htmlspecialchars($t('page.create', 'Создать'), ENT_QUOTES, 'UTF-8') ?></button></div></form></div></div></div>

<div class="modal fade" id="roleEditModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" data-i18n="admin_roles.modal_edit_title"><?= htmlspecialchars($t('admin_roles.modal_edit_title', 'Редактировать роль'), ENT_QUOTES, 'UTF-8') ?></h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="<?= htmlspecialchars($t('page.close', 'Закрыть'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-aria-label="page.close"></button></div><form id="roleEditForm"><div class="modal-body"><input type="hidden" name="public_id"><div class="row g-2 mb-3"><div class="col-md-6"><label class="form-label" data-i18n="admin_roles.field_code"><?= htmlspecialchars($t('admin_roles.field_code', 'Код роли'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="code" maxlength="64"></div><div class="col-md-6"><label class="form-label" data-i18n="admin_roles.field_title"><?= htmlspecialchars($t('admin_roles.field_title', 'Название роли'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="title" maxlength="255"></div></div><label class="form-label" data-i18n="admin_roles.field_permissions"><?= htmlspecialchars($t('admin_roles.field_permissions', 'Доступы'), ENT_QUOTES, 'UTF-8') ?></label><div class="border rounded p-2 crm-max-h-320 crm-overflow-auto" id="roleEditPermissionsList"><div class="text-muted" data-i18n="admin_roles.loading_permissions"><?= htmlspecialchars($t('admin_roles.loading_permissions', 'Загрузка доступов...'), ENT_QUOTES, 'UTF-8') ?></div></div></div><div class="modal-footer"><button class="btn crm-btn-secondary" type="button" data-bs-dismiss="modal" data-i18n="page.cancel"><?= htmlspecialchars($t('page.cancel', 'Отмена'), ENT_QUOTES, 'UTF-8') ?></button><button class="btn crm-btn-primary" type="submit" data-i18n="page.save"><?= htmlspecialchars($t('page.save', 'Сохранить'), ENT_QUOTES, 'UTF-8') ?></button></div></form></div></div></div>

<div class="modal fade" id="roleDeleteModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" data-i18n="admin_roles.modal_delete_title"><?= htmlspecialchars($t('admin_roles.modal_delete_title', 'Удалить роль?'), ENT_QUOTES, 'UTF-8') ?></h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="<?= htmlspecialchars($t('page.close', 'Закрыть'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-aria-label="page.close"></button></div><div class="modal-body"><input type="hidden" id="roleDeletePublicId"><p class="mb-0" id="roleDeleteText" data-i18n="admin_roles.modal_delete_text"><?= htmlspecialchars($t('admin_roles.modal_delete_text', 'Роль будет удалена без возможности восстановления.'), ENT_QUOTES, 'UTF-8') ?></p></div><div class="modal-footer"><button class="btn crm-btn-secondary" type="button" data-bs-dismiss="modal" data-i18n="page.cancel"><?= htmlspecialchars($t('page.cancel', 'Отмена'), ENT_QUOTES, 'UTF-8') ?></button><button class="btn crm-btn-danger-soft" type="button" id="roleDeleteConfirmBtn" data-i18n="page.delete"><?= htmlspecialchars($t('page.delete', 'Удалить'), ENT_QUOTES, 'UTF-8') ?></button></div></div></div></div>

</main></div></div>
