<?php
declare(strict_types=1);

namespace Module\Crm\KaitenMigration\Controller;

use Api\System\Library\Container;
use Api\System\Library\Http\JsonResponse;
use Module\Crm\KaitenMigration\Repository\KaitenMigrationRepository;
use Module\Crm\KaitenMigration\Service\EncryptionService;
use Module\Crm\KaitenMigration\Service\KaitenClient;
use Module\Crm\KaitenMigration\Service\KaitenCrawler;
use Module\Crm\KaitenMigration\Service\KaitenImportService;
use Module\Crm\KaitenMigration\Service\KaitenTargetWriter;

final class KaitenMigrationController
{
    private KaitenMigrationRepository $repo;
    public function __construct(private readonly Container $container) { $this->repo=new KaitenMigrationRepository($container->get('db.pdo')); }
    private function body(): array { $raw=(string)($this->container->get('request')->rawBody??'');$value=$raw!==''?json_decode($raw,true):[];return is_array($value)?$value:[]; }
    private function actor(): array { $auth=$this->container->has('auth_user')?$this->container->get('auth_user'):[];return is_array($auth)&&is_array($auth['user']??null)?$auth['user']:[]; }
    private function actorId(): int { return (int)($this->actor()['id']??0); }
    private function can(string $permission): bool { $a=$this->actor();return !empty($a['is_root'])||in_array('*',(array)($a['permission_codes']??[]),true)||in_array($permission,(array)($a['permission_codes']??[]),true); }
    private function connection(string $id): array|JsonResponse { $row=$this->repo->getConnection($id);if(!$row)return JsonResponse::error('NOT_FOUND','Kaiten connection not found',404);if(!$this->can('module.kaiten-migration.manage')&&(int)$row['created_by_user_id']!==$this->actorId())return JsonResponse::error('FORBIDDEN','Connection access denied',403);return$row; }
    private function job(string $id): array|JsonResponse { $row=$this->repo->getJob($id);if(!$row)return JsonResponse::error('NOT_FOUND','Kaiten migration job not found',404);if(!$this->can('module.kaiten-migration.manage')&&(int)$row['created_by_user_id']!==$this->actorId())return JsonResponse::error('FORBIDDEN','Migration job access denied',403);return$row; }

    public function listConnections(): JsonResponse { return JsonResponse::success('KAITEN_CONNECTIONS_LIST','OK',['connections'=>array_map([$this,'publicConnection'],$this->repo->listConnections($this->actorId(),$this->can('module.kaiten-migration.manage')))]); }
    public function createConnection(): JsonResponse { return $this->withIdempotency(fn():JsonResponse=>$this->createConnectionInternal()); }
    private function createConnectionInternal(): JsonResponse
    {
        $input=$this->body();$name=trim((string)($input['name']??''));$baseUrl=trim((string)($input['base_url']??$input['tenant_url']??''));$token=trim((string)($input['access_token']??$input['token']??''));if($name===''||$baseUrl===''||$token==='')return JsonResponse::error('VALIDATION_ERROR','name, base_url and access_token are required',422);
        try{$client=new KaitenClient($this->repo,$baseUrl);$connection=$this->repo->createConnection(['name'=>mb_substr($name,0,255),'base_url'=>$baseUrl,'access_token_encrypted'=>EncryptionService::encrypt($token),'created_by_user_id'=>$this->actorId()]);$client->setConnectionId((int)$connection['id']);$me=$client->test($token);$this->repo->updateConnectionCheck((string)$connection['public_id'],true);return JsonResponse::success('KAITEN_CONNECTION_CREATED','Connection created and verified',['connection'=>$this->publicConnection($this->repo->getConnection((string)$connection['public_id'])??$connection),'user'=>$me],201);}catch(\Throwable $e){if(isset($connection['public_id']))$this->repo->updateConnectionCheck((string)$connection['public_id'],false,'Kaiten connection test failed');return JsonResponse::error($e->getMessage()==='KAITEN_AUTH_FAILED'?'KAITEN_AUTH_FAILED':'KAITEN_CONNECTION_TEST_FAILED','Kaiten credentials could not be verified',422);}
    }
    public function getConnection(array $params): JsonResponse { $r=$this->connection((string)($params['public_id']??''));return$r instanceof JsonResponse?$r:JsonResponse::success('KAITEN_CONNECTION','OK',['connection'=>$this->publicConnection($r)]); }
    public function updateConnection(array $params): JsonResponse
    {
        $r=$this->connection((string)($params['public_id']??''));if($r instanceof JsonResponse)return$r;$in=$this->body();$name=array_key_exists('name',$in)?mb_substr(trim((string)$in['name']),0,255):(string)$r['name'];$base=array_key_exists('base_url',$in)?trim((string)$in['base_url']):(string)$r['base_url'];$newToken=trim((string)($in['access_token']??$in['token']??''));$token=$newToken!==''?$newToken:EncryptionService::decrypt((string)$r['access_token_encrypted']);if($token===null)return JsonResponse::error('KAITEN_CREDENTIAL_DECRYPT_FAILED','Could not decrypt credentials',500);
        try{$check=new KaitenClient($this->repo,$base);$check->setConnectionId((int)$r['id']);$check->test($token);}catch(\Throwable){$this->repo->updateConnectionCheck((string)$r['public_id'],false,'Kaiten connection test failed');return JsonResponse::error('KAITEN_CONNECTION_TEST_FAILED','Updated Kaiten credentials could not be verified',422);}
        $u=['name'=>$name,'base_url'=>$base];if($newToken!=='')$u['access_token_encrypted']=EncryptionService::encrypt($newToken);$this->repo->updateConnection((string)$params['public_id'],$u);$this->repo->updateConnectionCheck((string)$r['public_id'],true);return JsonResponse::success('KAITEN_CONNECTION_UPDATED','Connection updated and verified',['connection'=>$this->publicConnection($this->repo->getConnection((string)$params['public_id'])??[])]);
    }
    public function deleteConnection(array $params): JsonResponse { $r=$this->connection((string)($params['public_id']??''));if($r instanceof JsonResponse)return$r;if($this->repo->hasRunningJobs((int)$r['id']))return JsonResponse::error('CONNECTION_HAS_RUNNING_JOBS','Cancel running jobs before deleting the connection',409);$this->repo->deleteConnection((int)$r['id']);return JsonResponse::success('KAITEN_CONNECTION_DELETED','Connection deleted'); }
    public function testConnection(array $params): JsonResponse { $r=$this->connection((string)($params['public_id']??''));if($r instanceof JsonResponse)return$r;$token=EncryptionService::decrypt((string)$r['access_token_encrypted']);if($token===null)return JsonResponse::error('KAITEN_CREDENTIAL_DECRYPT_FAILED','Could not decrypt credentials',500);try{$me=$this->client($r)->test($token);$this->repo->updateConnectionCheck((string)$r['public_id'],true);return JsonResponse::success('KAITEN_CONNECTION_TEST_OK','Connection successful',['user'=>$me]);}catch(\Throwable){$this->repo->updateConnectionCheck((string)$r['public_id'],false,'Kaiten connection test failed');return JsonResponse::error('KAITEN_CONNECTION_TEST_FAILED','Kaiten connection test failed',400);} }

    public function listSpaces(array $params): JsonResponse { $r=$this->connection((string)($params['public_id']??''));if($r instanceof JsonResponse)return$r;$token=EncryptionService::decrypt((string)$r['access_token_encrypted']);if($token===null)return JsonResponse::error('KAITEN_CREDENTIAL_DECRYPT_FAILED','Could not decrypt credentials',500);try{return JsonResponse::success('KAITEN_SPACES_LIST','OK',['spaces'=>$this->client($r)->spaces($token)]);}catch(\Throwable){return JsonResponse::error('KAITEN_SPACES_FAILED','Could not load Kaiten spaces',400);} }
    public function listWorkspaces(array $params): JsonResponse { return $this->listSpaces($params); }
    public function discover(array $params): JsonResponse
    {
        $r=$this->connection((string)($params['public_id']??''));if($r instanceof JsonResponse)return$r;$in=$this->body();$spaceId=trim((string)($in['space_id']??$in['workspace_gid']??''));$token=EncryptionService::decrypt((string)$r['access_token_encrypted']);if($token===null)return JsonResponse::error('KAITEN_CREDENTIAL_DECRYPT_FAILED','Could not decrypt credentials',500);if($spaceId==='')return JsonResponse::error('KAITEN_SPACE_REQUIRED','space_id is required',422);try{$c=$this->client($r);$spaces=$c->spaces($token);$found=array_values(array_filter($spaces,static fn(array $s):bool=>(string)($s['id']??$s['uid']??'')===$spaceId));if($found===[])return JsonResponse::error('KAITEN_SPACE_NOT_ACCESSIBLE','Selected space is not accessible',422);$boards=$c->boards($token,$spaceId,!empty($in['include_archived']));foreach($c->users($token) as $user)$this->repo->upsertUserMapping((int)$r['id'],$user);return JsonResponse::success('KAITEN_DISCOVERY_COMPLETE','Kaiten source discovered',['spaces'=>$spaces,'space_id'=>$spaceId,'boards'=>$boards,'user_mappings'=>$this->repo->listUserMappings((int)$r['id'])]);}catch(\Throwable){return JsonResponse::error('KAITEN_DISCOVERY_FAILED','Kaiten discovery failed',400);} }
    public function listUserMappings(array $params): JsonResponse { $r=$this->connection((string)($params['public_id']??''));return$r instanceof JsonResponse?$r:JsonResponse::success('KAITEN_USER_MAPPINGS','OK',['items'=>$this->repo->listUserMappings((int)$r['id'])]); }
    public function updateUserMapping(array $params): JsonResponse { $r=$this->connection((string)($params['public_id']??''));if($r instanceof JsonResponse)return$r;$id=($v=$this->body()['crm_user_public_id']??null)!==null&&$v!==''?(string)$v:null;if($id!==null&&$this->repo->activeUserPublicId($id)===null)return JsonResponse::error('USER_NOT_FOUND','Active CRM user not found',404);if(!$this->repo->updateUserMapping((int)$r['id'],(int)($params['mapping_id']??0),$id))return JsonResponse::error('MAPPING_NOT_FOUND','Kaiten user mapping not found',404);return JsonResponse::success('KAITEN_USER_MAPPING_UPDATED','Mapping updated'); }

    public function listJobs(): JsonResponse { return JsonResponse::success('KAITEN_JOBS_LIST','OK',['items'=>$this->repo->listJobs($this->actorId(),$this->can('module.kaiten-migration.manage'))]); }
    public function createJob(): JsonResponse { return $this->withIdempotency(fn():JsonResponse=>$this->createJobInternal()); }
    private function createJobInternal(): JsonResponse
    {
        $in=$this->body();$r=$this->connection((string)($in['connection_public_id']??''));if($r instanceof JsonResponse)return$r;$space=trim((string)($in['space_id']??$in['workspace_gid']??$r['workspace_gid']??''));if($space==='')return JsonResponse::error('KAITEN_SPACE_REQUIRED','space_id is required',422);$mode=(string)($in['mode']??'import');if(!in_array($mode,['import','sync','dry_run'],true))return JsonResponse::error('VALIDATION_ERROR','mode must be import, sync or dry_run',422);$token=EncryptionService::decrypt((string)$r['access_token_encrypted']);if($token===null)return JsonResponse::error('KAITEN_CREDENTIAL_DECRYPT_FAILED','Could not decrypt credentials',500);try{$accessible=false;foreach($this->client($r)->spaces($token) as $source){if((string)($source['id']??$source['uid']??'')===$space){$accessible=true;break;}}if(!$accessible)return JsonResponse::error('KAITEN_SPACE_NOT_ACCESSIBLE','Selected space is not accessible',422);}catch(\Throwable){return JsonResponse::error('KAITEN_SPACE_VALIDATION_FAILED','Could not validate selected space',422);}$scope=(array)($in['source_scope']??[]);$scope['space_ids']=[$space];$scope['board_ids']=array_values(array_filter(array_map('strval',(array)($in['board_ids']??$scope['board_ids']??[]))));$scope['max_cards']=max(0,(int)($in['max_cards']??$scope['max_cards']??0));$job=$this->repo->createJob(['connection_id'=>(int)$r['id'],'workspace_gid'=>$space,'mode'=>$mode,'source_scope'=>$scope,'target_options'=>(array)($in['target_options']??$in['options']??[]),'created_by_user_id'=>$this->actorId()]);return JsonResponse::success('KAITEN_JOB_CREATED','Job created',['job'=>$job],201);
    }
    public function getJob(array $params): JsonResponse { $r=$this->job((string)($params['public_id']??''));return$r instanceof JsonResponse?$r:JsonResponse::success('KAITEN_JOB','OK',['job'=>$r]); }
    public function startJob(array $p): JsonResponse{return$this->changeJob((string)$p['public_id'],'queued','KAITEN_JOB_QUEUED');}public function pauseJob(array $p):JsonResponse{return$this->changeJob((string)$p['public_id'],'pausing','KAITEN_JOB_PAUSING');}public function resumeJob(array $p):JsonResponse{return$this->changeJob((string)$p['public_id'],'queued','KAITEN_JOB_RESUMED');}public function cancelJob(array $p):JsonResponse{return$this->changeJob((string)$p['public_id'],'cancelling','KAITEN_JOB_CANCELLING');}
    public function retryFailed(array $p): JsonResponse { $r=$this->job((string)$p['public_id']);if($r instanceof JsonResponse)return$r;$count=$this->repo->retryJob((string)$p['public_id']);if($count===null)return JsonResponse::error('INVALID_JOB_STATUS','Only a finished job can be retried',409);return JsonResponse::success('KAITEN_JOB_RETRY_QUEUED','Failed items queued for retry',['reset_items'=>$count]); }
    public function rollbackJob(array $p): JsonResponse { $r=$this->job((string)$p['public_id']);if($r instanceof JsonResponse)return$r;try{$this->buildImportService((string)$p['public_id'])->rollback((string)$p['public_id'],$this->actor());return JsonResponse::success('KAITEN_JOB_ROLLED_BACK','Job targets rolled back');}catch(\Throwable){return JsonResponse::error('KAITEN_ROLLBACK_FAILED','Rollback failed; inspect the migration log',409);} }
    public function listJobItems(array $p):JsonResponse{$r=$this->job((string)$p['public_id']);if($r instanceof JsonResponse)return$r;$in=$this->container->get('request')->allInput();return JsonResponse::success('KAITEN_JOB_ITEMS','OK',['items'=>$this->repo->items((int)$r['id'],!empty($in['status'])?(string)$in['status']:null,max(1,min(1000,(int)($in['limit']??200))))]);}
    public function listJobLogs(array $p):JsonResponse{$r=$this->job((string)$p['public_id']);return$r instanceof JsonResponse?$r:JsonResponse::success('KAITEN_JOB_LOGS','OK',['items'=>$this->repo->logs((int)$r['id'])]);}
    public function getReport(array $p):JsonResponse{$r=$this->job((string)$p['public_id']);return$r instanceof JsonResponse?$r:JsonResponse::success('KAITEN_JOB_REPORT','OK',['report'=>$this->repo->report((string)$p['public_id'])]);}
    private function changeJob(string $id,string $status,string $code):JsonResponse{$r=$this->job($id);if($r instanceof JsonResponse)return$r;$current=(string)($r['status']??'');$ok=match($status){'queued'=>in_array($current,['draft','paused','failed','cancelled'],true),'pausing'=>in_array($current,['queued','running'],true),'cancelling'=>in_array($current,['draft','queued','running','paused','pausing'],true),default=>false};if(!$ok)return JsonResponse::error('INVALID_JOB_STATUS','Job cannot be changed from status: '.$current,409);if(!$this->repo->requestStatus($id,$status))return JsonResponse::error('INVALID_JOB_STATUS','Job changed concurrently; retry the action',409);return JsonResponse::success($code,'Job state updated');}
    private function client(array $connection): KaitenClient{$c=new KaitenClient($this->repo,(string)($connection['base_url']??''));$c->setConnectionId((int)$connection['id']);return$c;}
    private function buildImportService(string $jobPublicId):KaitenImportService{$job=$this->repo->getJob($jobPublicId);$connection=is_array($job)?$this->repo->getConnectionById((int)$job['connection_id']):null;$c=$this->client($connection??[]);$crawler=new KaitenCrawler($c,$this->repo);$writer=new KaitenTargetWriter($this->container,$this->repo,$c);return new KaitenImportService($this->repo,$c,$crawler,$writer);}
    private function withIdempotency(callable $producer):JsonResponse{if(!$this->container->has('service.idempotency'))return$producer();$s=$this->container->get('service.idempotency');$request=$this->container->get('request');$auth=$this->container->has('auth_user')?$this->container->get('auth_user'):null;$actor=is_array($auth)&&is_array($auth['user']??null)?$auth['user']:null;$replayed=$s->replay($request,$actor);if($replayed instanceof JsonResponse)return$replayed;$response=$producer();$s->remember($request,$actor,$response);return$response;}
    private function publicConnection(array $row):array{unset($row['access_token_encrypted'],$row['refresh_token_encrypted'],$row['client_id_encrypted'],$row['client_secret_encrypted']);return$row;}
}
