SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `module_clickup_unresolved_entities`;
DROP TABLE IF EXISTS `module_clickup_job_logs`;
DROP TABLE IF EXISTS `module_clickup_rate_limits`;
DROP TABLE IF EXISTS `module_clickup_user_mappings`;
DROP TABLE IF EXISTS `module_clickup_source_mappings`;
DROP TABLE IF EXISTS `module_clickup_job_items`;
DROP TABLE IF EXISTS `module_clickup_jobs`;
DROP TABLE IF EXISTS `module_clickup_connections`;
SET FOREIGN_KEY_CHECKS = 1;
