SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `module_activecollab_unresolved_entities`;
DROP TABLE IF EXISTS `module_activecollab_job_logs`;
DROP TABLE IF EXISTS `module_activecollab_rate_limits`;
DROP TABLE IF EXISTS `module_activecollab_user_mappings`;
DROP TABLE IF EXISTS `module_activecollab_source_mappings`;
DROP TABLE IF EXISTS `module_activecollab_job_items`;
DROP TABLE IF EXISTS `module_activecollab_jobs`;
DROP TABLE IF EXISTS `module_activecollab_connections`;
SET FOREIGN_KEY_CHECKS = 1;
