#!/usr/bin/env python3
"""Package the next standalone language-pack wave.

The locale dictionaries are generated by the dedicated builders.  This command
only packages the already generated web/API catalogues, so no external locale
can accidentally become part of the core tree.
"""
from __future__ import annotations

import hashlib
import json
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGES = ROOT / "upload/storage/packages"
LOCALES = (
    "id-id", "vi-vn", "th-th", "ms-my", "fil-ph", "be-by",
    "nl-nl", "pl-pl", "ro-ro", "cs-cz", "hu-hu", "sr-rs", "hr-hr",
)


def package(locale: str) -> tuple[Path, str]:
    web = ROOT / "upload/web/language" / f"{locale}.php"
    api = ROOT / "upload/api/language" / locale
    manifest_path = api / "manifest.json"
    if not web.is_file() or not manifest_path.is_file():
        raise FileNotFoundError(f"generated catalogue is missing for {locale}")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    expected = f"language-pack-{locale}"
    if manifest.get("name") != expected or manifest.get("code") != locale:
        raise ValueError(f"manifest mismatch for {locale}: {manifest.get('name')}")
    archive = PACKAGES / f"crm.language-pack-{locale}-{manifest['version']}.zip"
    archive.parent.mkdir(parents=True, exist_ok=True)
    if archive.exists():
        archive.unlink()
    with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.write(manifest_path, "manifest.json")
        zf.write(web, f"web/{locale}.php")
        for path in sorted(api.rglob("*.php")):
            zf.write(path, f"api/{locale}/{path.relative_to(api)}")
    return archive, hashlib.sha256(archive.read_bytes()).hexdigest()


if __name__ == "__main__":
    for code in LOCALES:
        archive, digest = package(code)
        print(f"{code}\t{archive.name}\t{digest}")
