<?php
declare(strict_types=1);

return [
    'feature_flags' => [
        'approvals' => true,
        'sla' => true,
        'webhooks' => true,
        'import_export' => true,
        'custom_fields' => true,
        'automation' => true,
        'recurring' => true,
        'events_sse' => true,
        'ai.enabled' => true,
        'ai.task' => false,
        'ai.project' => false,
        'ai.calendar' => false,
        'ai.client' => false,
        'ai.analytics' => false,
        'ai.admin' => false,
        'ai.search' => true,
        'ai.knowledge' => true,
        'ai.workflow' => false,
        'ai.import' => false,
        'ai.cron.enabled' => false,
        'ai.cron.daily_work_plan' => false,
        'ai.cron.user_daily_digest' => false,
        'ai.cron.user_weekly_plan' => false,
        'ai.cron.manager_weekly_digest' => false,
        'ai.cron.task_risk_scan' => false,
        'ai.cron.task_quality_scan' => false,
        'ai.cron.task_decomposition_scan' => false,
        'ai.cron.meeting_agenda' => false,
        'ai.cron.project_daily_summary' => false,
        'ai.cron.client_weekly_report' => false,
        'ai.cron.team_workload_scan' => false,
        'ai.cron.sla_approval_scan' => false,
        'ai.cron.data_quality_scan' => false,
        'ai.cron.import_review' => false,
        'ai.cron.security_log_review' => false,
        'ai.cron.webhook_health_review' => false,
        'ai.cron.workflow_audit' => false,
        'ai.cron.semantic_index_refresh' => false,
        'ai.cron.suggestion_cleanup' => false,
    ],
];
