<?php
declare(strict_types=1);

return [
    '' => [Web\Controller\Page\DashboardController::class, 'index'],
    'dashboard' => [Web\Controller\Page\DashboardController::class, 'index'],
    'index' => [Web\Controller\Page\DashboardController::class, 'index'],

    'app' => [Web\Controller\Page\AppController::class, 'index'],
    'login' => [Web\Controller\Page\LoginController::class, 'index'],
    'password-reset-request' => [Web\Controller\Page\PasswordResetRequestController::class, 'index'],
    'password-reset-confirm' => [Web\Controller\Page\PasswordResetConfirmController::class, 'index'],
    'invitation-accept' => [Web\Controller\Page\InvitationAcceptController::class, 'index'],

    'projects' => [Web\Controller\Page\ProjectsController::class, 'index'],
    'project-detail' => [Web\Controller\Page\ProjectDetailController::class, 'index'],
    'tasks' => [Web\Controller\Page\TasksController::class, 'index'],
    'task-detail' => [Web\Controller\Page\TaskDetailController::class, 'index'],
    'kanban' => [Web\Controller\Page\KanbanController::class, 'index'],
    'gantt' => [Web\Controller\Page\GanttController::class, 'index'],

    'calendar' => [Web\Controller\Page\CalendarController::class, 'index'],
    'my-day' => [Web\Controller\Page\MyDayController::class, 'index'],
    'my-week' => [Web\Controller\Page\MyWeekController::class, 'index'],

    'notifications' => [Web\Controller\Page\NotificationsController::class, 'index'],
    'profile' => [Web\Controller\Page\ProfileController::class, 'index'],
    'cycles' => [Web\Controller\Page\CyclesController::class, 'index'],
    'teams' => [Web\Controller\Page\TeamsController::class, 'index'],
    'departments' => [Web\Controller\Page\DepartmentsController::class, 'index'],
    'clients' => [Web\Controller\Page\ClientsController::class, 'index'],
    'companies' => [Web\Controller\Page\CompaniesController::class, 'index'],
    'contacts' => [Web\Controller\Page\ContactsController::class, 'index'],
    'counterparties' => [Web\Controller\Page\CounterpartiesController::class, 'index'],
    'counterparty-detail' => [Web\Controller\Page\CounterpartyDetailController::class, 'index'],
    'client-detail' => [Web\Controller\Page\ClientDetailController::class, 'index'],
    'client-cabinet' => [Web\Controller\Page\ClientCabinetController::class, 'index'],

    'analytics' => [Web\Controller\Page\AnalyticsController::class, 'index'],
    'time-analytics' => [Web\Controller\Page\TimeAnalyticsController::class, 'index'],
    'global-search' => [Web\Controller\Page\GlobalSearchController::class, 'index'],
    'docs' => [Web\Controller\Page\DocsController::class, 'index'],
    'knowledge' => [Web\Controller\Page\KnowledgeController::class, 'index'],
    'knowledge-page' => [Web\Controller\Page\KnowledgePageController::class, 'index'],

    'admin' => [Web\Controller\Page\AdminController::class, 'index'],
    'admin-users' => [Web\Controller\Page\AdminUsersController::class, 'index'],
    'admin-roles' => [Web\Controller\Page\AdminRolesController::class, 'index'],
    'admin-statuses' => [Web\Controller\Page\AdminStatusesController::class, 'index'],
    'admin-logs' => [Web\Controller\Page\AdminLogsController::class, 'index'],
    'admin-api-clients' => [Web\Controller\Page\AdminApiClientsController::class, 'index'],
    'admin-settings' => [Web\Controller\Page\AdminSettingsController::class, 'index'],
    'admin-jobs' => [Web\Controller\Page\AdminJobsController::class, 'index'],
    'admin-ai' => [Web\Controller\Page\AdminAiController::class, 'index'],
    'admin-workflow' => [Web\Controller\Page\AdminWorkflowController::class, 'index'],
    'admin-sla' => [Web\Controller\Page\AdminSlaController::class, 'index'],
    'approvals' => [Web\Controller\Page\ApprovalsController::class, 'index'],
    'recycle-bin' => [Web\Controller\Page\RecycleBinController::class, 'index'],
    'admin-custom-fields' => [Web\Controller\Page\AdminCustomFieldsController::class, 'index'],
    'recurring' => [Web\Controller\Page\RecurringController::class, 'index'],
    'organizations' => [Web\Controller\Page\OrganizationsController::class, 'index'],
    'admin-priorities' => [Web\Controller\Page\AdminPrioritiesController::class, 'index'],
    'admin-calendar' => [Web\Controller\Page\AdminCalendarController::class, 'index'],
    'admin-knowledge' => [Web\Controller\Page\AdminKnowledgeController::class, 'index'],
    'mentions' => [Web\Controller\Page\MentionsController::class, 'index'],
    'admin-templates' => [Web\Controller\Page\AdminTemplatesController::class, 'index'],
    'admin-tags' => [Web\Controller\Page\AdminTagsController::class, 'index'],
    'admin-webhooks' => [Web\Controller\Page\AdminWebhooksController::class, 'index'],
    'admin-modules' => [Web\Controller\Page\AdminModulesController::class, 'index'],
    'admin-modules-install' => [Web\Controller\Page\AdminModulesInstallController::class, 'index'],
    'admin-module-detail' => [Web\Controller\Page\AdminModuleDetailController::class, 'index'],
    'ideas' => [Web\Controller\Page\IdeasController::class, 'index'],
    'idea-detail' => [Web\Controller\Page\IdeaDetailController::class, 'index'],
    'chat' => [Web\Controller\Page\ChatController::class, 'index'],
];
