<?php declare(strict_types=1); ?>
<?php $title = $t('admin_users.title', 'TropaTT — Users'); ?>
<body data-page="admin" data-protected="1"><div class="crm-app"><aside class="crm-sidebar"><div class="crm-brand"><span class="crm-brand-mark"></span> <?= htmlspecialchars($t('app.name', 'TropaTT'), ENT_QUOTES, 'UTF-8') ?></div><nav class="nav flex-column crm-nav"></nav></aside>
<div class="crm-main-wrap"><header class="crm-topbar py-2"><div class="container-fluid"></div></header>
<main class="crm-content crm-admin-page"><div class="crm-page-head"><div><ol class="breadcrumb mb-1"><li class="breadcrumb-item"><a href="index.php?route=admin"><?= htmlspecialchars($t('nav.admin', 'Admin'), ENT_QUOTES, 'UTF-8') ?></a></li><li class="breadcrumb-item active"><?= htmlspecialchars($t('admin_users.page_title', 'User Management'), ENT_QUOTES, 'UTF-8') ?></li></ol><h1 class="crm-page-title"><?= htmlspecialchars($t('admin_users.page_title', 'User Management'), ENT_QUOTES, 'UTF-8') ?></h1><p class="crm-subtitle"><?= htmlspecialchars($t('admin_users.subtitle', ''), ENT_QUOTES, 'UTF-8') ?></p></div><div class="d-flex gap-2"><button class="btn crm-btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#userCreateModal"><?= htmlspecialchars($t('admin_users.add_btn', '+ Add user'), ENT_QUOTES, 'UTF-8') ?></button><button class="btn crm-btn-secondary" type="button" data-bs-toggle="modal" data-bs-target="#invitationCreateModal"><?= htmlspecialchars($t('admin_users.invite_btn', 'Пригласить пользователя'), ENT_QUOTES, 'UTF-8') ?></button></div></div>

<div class="crm-toolbar crm-toolbar-surface d-flex flex-wrap gap-2 align-items-center">
  <input id="adminUsersSearchInput" class="form-control crm-field-w-280" placeholder="<?= htmlspecialchars($t('admin_users.search_placeholder', 'Search'), ENT_QUOTES, 'UTF-8') ?>">
  <select id="adminUsersActiveFilter" class="form-select crm-field-w-200">
    <option value=""><?= htmlspecialchars($t('admin_users.filter_all', 'All users'), ENT_QUOTES, 'UTF-8') ?></option>
    <option value="1"><?= htmlspecialchars($t('admin_users.filter_active', 'Active only'), ENT_QUOTES, 'UTF-8') ?></option>
    <option value="0"><?= htmlspecialchars($t('admin_users.filter_inactive', 'Inactive only'), ENT_QUOTES, 'UTF-8') ?></option>
  </select>
  <select id="adminUsersSavedViewSelect" class="form-select crm-field-w-220">
    <option value=""><?= htmlspecialchars($t('admin_users.saved_views', 'Saved views'), ENT_QUOTES, 'UTF-8') ?></option>
  </select>
  <button id="adminUsersSaveViewBtn" class="btn crm-btn-secondary" type="button"><?= htmlspecialchars($t('admin_users.save_view', 'Save view'), ENT_QUOTES, 'UTF-8') ?></button>
  <button id="adminUsersDeleteViewBtn" class="btn crm-btn-muted" type="button"><?= htmlspecialchars($t('admin_users.delete_view', 'Delete view'), ENT_QUOTES, 'UTF-8') ?></button>
  <button id="adminUsersFiltersResetBtn" class="btn crm-btn-secondary" type="button"><?= htmlspecialchars($t('admin_users.filter_reset', 'Reset'), ENT_QUOTES, 'UTF-8') ?></button>
</div>

<div id="adminUsersBulkActionsBar" class="alert alert-primary d-none d-flex justify-content-between align-items-center" role="region" aria-label="Bulk actions admin users">
  <div><?= htmlspecialchars($t('admin_users.bulk_selected', 'Users selected:'), ENT_QUOTES, 'UTF-8') ?> <strong data-admin-users-selected-count>0</strong> <span class="small ms-2" id="adminUsersBulkResult" aria-live="polite"></span></div>
  <div class="d-flex gap-2">
    <select id="adminUsersBulkActiveSelect" class="form-select form-select-sm crm-field-w-170" aria-label="<?= htmlspecialchars($t('admin_users.bulk_status_aria', 'Change user status'), ENT_QUOTES, 'UTF-8') ?>">
      <option value=""><?= htmlspecialchars($t('admin_users.bulk_status_placeholder', 'Status...'), ENT_QUOTES, 'UTF-8') ?></option>
      <option value="1"><?= htmlspecialchars($t('admin_users.bulk_active', 'Active'), ENT_QUOTES, 'UTF-8') ?></option>
      <option value="0"><?= htmlspecialchars($t('admin_users.bulk_inactive', 'Inactive'), ENT_QUOTES, 'UTF-8') ?></option>
    </select>
    <button class="btn btn-sm crm-btn-danger-soft" type="button" id="adminUsersBulkDeleteBtn"><?= htmlspecialchars($t('admin_users.bulk_delete', 'Delete'), ENT_QUOTES, 'UTF-8') ?></button>
  </div>
</div>

<div class="crm-card crm-section-card p-0 table-responsive"><table class="table crm-table mb-0"><thead><tr><th style="width:40px"><input class="form-check-input" type="checkbox" id="adminUsersBulkSelectAll"></th><th><?= htmlspecialchars($t('admin_users.th_user', 'User'), ENT_QUOTES, 'UTF-8') ?></th><th><?= htmlspecialchars($t('admin_users.th_email', 'Email'), ENT_QUOTES, 'UTF-8') ?></th><th><?= htmlspecialchars($t('admin_users.th_role', 'Role'), ENT_QUOTES, 'UTF-8') ?></th><th><?= htmlspecialchars($t('admin_users.th_team', 'Team'), ENT_QUOTES, 'UTF-8') ?></th><th><?= htmlspecialchars($t('admin_users.th_last_login', 'Last login'), ENT_QUOTES, 'UTF-8') ?></th><th><?= htmlspecialchars($t('admin_users.th_status', 'Status'), ENT_QUOTES, 'UTF-8') ?></th><th style="width:150px"><?= htmlspecialchars($t('admin_users.th_actions', 'Actions'), ENT_QUOTES, 'UTF-8') ?></th></tr></thead><tbody>
<tr><td colspan="8" class="text-muted"><?= htmlspecialchars($t('admin_users.loading', 'Loading users...'), ENT_QUOTES, 'UTF-8') ?></td></tr>
</tbody></table></div>

<div class="modal fade" id="userCreateModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title"><?= htmlspecialchars($t('admin_users.create_title', 'Add user'), ENT_QUOTES, 'UTF-8') ?></h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><form id="adminUserCreateForm"><div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label"><?= htmlspecialchars($t('admin_users.field_login', 'Login'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="login" maxlength="120" required></div><div class="col-md-6"><label class="form-label"><?= htmlspecialchars($t('admin_users.field_password', 'Password'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" type="password" name="password" minlength="8" required></div><div class="col-md-6"><label class="form-label"><?= htmlspecialchars($t('admin_users.field_name', 'Name'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="full_name" maxlength="255"></div><div class="col-md-6"><label class="form-label"><?= htmlspecialchars($t('admin_users.th_email', 'Email'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="email" maxlength="190"></div><div class="col-md-6"><label class="form-label"><?= htmlspecialchars($t('admin_users.field_locale', 'Locale'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="locale" value="ru-ru" maxlength="20"></div><div class="col-md-6"><label class="form-label"><?= htmlspecialchars($t('admin_users.field_role', 'Role'), ENT_QUOTES, 'UTF-8') ?></label><select class="form-select" name="role_public_ids"><option value=""><?= htmlspecialchars($t('admin_users.no_role', 'No role'), ENT_QUOTES, 'UTF-8') ?></option></select></div><div class="col-md-6"><label class="form-label"><?= htmlspecialchars($t('admin_users.field_team', 'Team'), ENT_QUOTES, 'UTF-8') ?></label><select class="form-select" name="team_public_id"><option value=""><?= htmlspecialchars($t('admin_users.no_team', 'No team'), ENT_QUOTES, 'UTF-8') ?></option></select></div></div></div><div class="modal-footer"><button class="btn crm-btn-secondary" type="button" data-bs-dismiss="modal"><?= htmlspecialchars($t('admin_users.cancel', 'Cancel'), ENT_QUOTES, 'UTF-8') ?></button><button class="btn crm-btn-primary" type="submit"><?= htmlspecialchars($t('admin_users.add', 'Add'), ENT_QUOTES, 'UTF-8') ?></button></div></form></div></div></div>
<div class="modal fade" id="userEditModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title"><?= htmlspecialchars($t('admin_users.edit_title', 'Edit user'), ENT_QUOTES, 'UTF-8') ?></h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><form id="adminUserEditForm"><div class="modal-body"><input type="hidden" name="public_id"><div class="row g-3"><div class="col-md-6"><label class="form-label"><?= htmlspecialchars($t('admin_users.field_name', 'Name'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="full_name" maxlength="255"></div><div class="col-md-6"><label class="form-label"><?= htmlspecialchars($t('admin_users.th_email', 'Email'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="email" maxlength="190"></div><div class="col-md-6"><label class="form-label"><?= htmlspecialchars($t('admin_users.field_locale', 'Locale'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="locale" maxlength="20"></div><div class="col-md-6"><label class="form-label"><?= htmlspecialchars($t('admin_users.field_user_status', 'Status'), ENT_QUOTES, 'UTF-8') ?></label><select class="form-select" name="is_active"><option value="1"><?= htmlspecialchars($t('admin_users.status_active', 'Active'), ENT_QUOTES, 'UTF-8') ?></option><option value="0"><?= htmlspecialchars($t('admin_users.status_inactive', 'Inactive'), ENT_QUOTES, 'UTF-8') ?></option></select></div><div class="col-md-6"><label class="form-label"><?= htmlspecialchars($t('admin_users.field_new_password', 'New password (optional)'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" type="password" name="password" minlength="8"></div><div class="col-md-6"><label class="form-label"><?= htmlspecialchars($t('admin_users.field_role', 'Role'), ENT_QUOTES, 'UTF-8') ?></label><select class="form-select" name="role_public_ids"><option value=""><?= htmlspecialchars($t('admin_users.no_role', 'No role'), ENT_QUOTES, 'UTF-8') ?></option></select></div><div class="col-md-6"><label class="form-label"><?= htmlspecialchars($t('admin_users.field_team', 'Team'), ENT_QUOTES, 'UTF-8') ?></label><select class="form-select" name="team_public_id"><option value=""><?= htmlspecialchars($t('admin_users.no_team', 'No team'), ENT_QUOTES, 'UTF-8') ?></option></select></div></div></div><div class="modal-footer"><button class="btn crm-btn-secondary" type="button" data-bs-dismiss="modal"><?= htmlspecialchars($t('admin_users.cancel', 'Cancel'), ENT_QUOTES, 'UTF-8') ?></button><button class="btn crm-btn-primary" type="submit"><?= htmlspecialchars($t('admin_users.save', 'Save'), ENT_QUOTES, 'UTF-8') ?></button></div></form></div></div></div>
<div class="modal fade" id="invitationCreateModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title"><?= htmlspecialchars($t('admin_users.invite_title', 'Пригласить пользователя'), ENT_QUOTES, 'UTF-8') ?></h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div>
<div id="invitationCreateFormPanel">
<form id="invitationCreateForm"><div class="modal-body">
<p class="text-muted small"><?= htmlspecialchars($t('admin_users.invite_hint', 'Приглашаемый сам укажет логин, имя и пароль при принятии приглашения.'), ENT_QUOTES, 'UTF-8') ?></p>
<div class="mb-3"><label class="form-label"><?= htmlspecialchars($t('admin_users.th_email', 'Email'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" type="email" name="email" maxlength="190" required placeholder="ivan@example.com"></div>
<div class="mb-3"><label class="form-label"><?= htmlspecialchars($t('admin_users.invite_field_expires', 'Срок действия'), ENT_QUOTES, 'UTF-8') ?></label><select class="form-select" name="expires_in_days"><option value="1"><?= htmlspecialchars($t('admin_users.invite_expires_1', '1 день'), ENT_QUOTES, 'UTF-8') ?></option><option value="7" selected><?= htmlspecialchars($t('admin_users.invite_expires_7', '7 дней'), ENT_QUOTES, 'UTF-8') ?></option><option value="14"><?= htmlspecialchars($t('admin_users.invite_expires_14', '14 дней'), ENT_QUOTES, 'UTF-8') ?></option><option value="30"><?= htmlspecialchars($t('admin_users.invite_expires_30', '30 дней'), ENT_QUOTES, 'UTF-8') ?></option></select></div>
<div id="invitationCreateError" class="alert alert-danger d-none py-2"></div>
</div><div class="modal-footer"><button class="btn crm-btn-secondary" type="button" data-bs-dismiss="modal"><?= htmlspecialchars($t('admin_users.cancel', 'Отмена'), ENT_QUOTES, 'UTF-8') ?></button><button class="btn crm-btn-primary" type="submit"><?= htmlspecialchars($t('admin_users.invite_btn_create', 'Создать приглашение'), ENT_QUOTES, 'UTF-8') ?></button></div></form>
</div>
<div id="invitationCreateResult" class="d-none"><div class="modal-body">
<div class="alert alert-success py-2"><?= htmlspecialchars($t('admin_users.invite_created', 'Приглашение создано. Передайте ссылку или токен приглашаемому — токен показывается только один раз.'), ENT_QUOTES, 'UTF-8') ?></div>
<div class="mb-3"><label class="form-label"><?= htmlspecialchars($t('admin_users.invite_link_label', 'Ссылка для приглашения'), ENT_QUOTES, 'UTF-8') ?></label><div class="input-group"><input class="form-control" id="invitationLinkInput" type="text" readonly onclick="this.select()"><button class="btn crm-btn-secondary" type="button" data-copy-target="invitationLinkInput"><?= htmlspecialchars($t('admin_users.invite_copy', 'Копировать'), ENT_QUOTES, 'UTF-8') ?></button></div></div>
<div class="mb-3"><label class="form-label"><?= htmlspecialchars($t('admin_users.invite_token_label', 'Токен'), ENT_QUOTES, 'UTF-8') ?></label><div class="input-group"><input class="form-control" id="invitationTokenInput" type="text" readonly onclick="this.select()"><button class="btn crm-btn-secondary" type="button" data-copy-target="invitationTokenInput"><?= htmlspecialchars($t('admin_users.invite_copy', 'Копировать'), ENT_QUOTES, 'UTF-8') ?></button></div></div>
<p class="text-muted small mb-0"><?= htmlspecialchars($t('admin_users.invite_once_hint', 'Внимание: токен больше не будет показан. Если приглашение потеряно, создайте новое.'), ENT_QUOTES, 'UTF-8') ?></p>
</div><div class="modal-footer"><button class="btn crm-btn-primary" type="button" data-bs-dismiss="modal"><?= htmlspecialchars($t('admin_users.invite_done', 'Готово'), ENT_QUOTES, 'UTF-8') ?></button></div></div>
</div></div></div>

</main></div></div>
