<?php declare(strict_types=1); ?>
<?php $title = $t('analytics.title', 'TropaTT — Аналитика'); ?>
<body data-page="analytics" data-protected="1"><div class="crm-app"><aside class="crm-sidebar"><div class="crm-brand"><span class="crm-brand-mark"></span> <?= htmlspecialchars($t('app.name', 'TropaTT'), ENT_QUOTES, 'UTF-8') ?></div><nav class="nav flex-column crm-nav"></nav></aside>
<div class="crm-main-wrap"><header class="crm-topbar py-2"><div class="container-fluid"></div></header>
<main class="crm-content crm-analytics-page"><div class="crm-page-head"><div><h1 class="crm-page-title" data-i18n="analytics.page_title"><?= htmlspecialchars($t('analytics.page_title', 'Аналитика'), ENT_QUOTES, 'UTF-8') ?></h1><p class="crm-subtitle" data-analytics-subtitle data-i18n="analytics.subtitle"><?= htmlspecialchars($t('analytics.subtitle', 'SLA, выполнение задач, загрузка команд и проектные риски.'), ENT_QUOTES, 'UTF-8') ?></p></div><div class="crm-page-actions"><a class="btn crm-btn-secondary" href="index.php?route=time-analytics" data-i18n="analytics.btn_time_tracking"><i class="fa-regular fa-clock"></i> <?= htmlspecialchars($t('analytics.btn_time_tracking', 'Учет времени'), ENT_QUOTES, 'UTF-8') ?></a><button class="btn crm-btn-secondary" type="button" id="analyticsExportBtn" disabled data-i18n="analytics.btn_export_csv"><?= htmlspecialchars($t('analytics.btn_export_csv', 'Экспорт CSV'), ENT_QUOTES, 'UTF-8') ?></button></div></div>
<div class="crm-toolbar-surface crm-analytics-toolbar mb-3" aria-label="<?= htmlspecialchars($t('analytics.filters_aria', 'Фильтры аналитики'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-aria-label="analytics.filters_aria"><div><label class="crm-filter-label" for="analyticsProjectFilter" data-i18n="analytics.filter_project"><?= htmlspecialchars($t('analytics.filter_project', 'Проект'), ENT_QUOTES, 'UTF-8') ?></label><select class="form-select crm-field-w-220" id="analyticsProjectFilter" aria-label="<?= htmlspecialchars($t('analytics.filter_project_aria', 'Проект'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-aria-label="analytics.filter_project_aria"><option value="" data-i18n="analytics.opt_all_projects"><?= htmlspecialchars($t('analytics.opt_all_projects', 'Все проекты'), ENT_QUOTES, 'UTF-8') ?></option></select></div><div><label class="crm-filter-label" for="analyticsTeamFilter" data-i18n="analytics.filter_assignee"><?= htmlspecialchars($t('analytics.filter_assignee', 'Исполнитель'), ENT_QUOTES, 'UTF-8') ?></label><select class="form-select crm-field-w-220" id="analyticsTeamFilter" aria-label="<?= htmlspecialchars($t('analytics.filter_assignee_aria', 'Исполнитель'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-aria-label="analytics.filter_assignee_aria"><option value="" data-i18n="analytics.opt_all_assignees"><?= htmlspecialchars($t('analytics.opt_all_assignees', 'Все исполнители'), ENT_QUOTES, 'UTF-8') ?></option></select></div><button class="btn crm-btn-secondary" type="button" id="analyticsApplyBtn" data-i18n="page.apply"><?= htmlspecialchars($t('page.apply', 'Применить'), ENT_QUOTES, 'UTF-8') ?></button><span class="crm-toolbar-note" data-analytics-filter-note data-i18n="analytics.filter_note"><?= htmlspecialchars($t('analytics.filter_note', 'Показан общий срез по доступным данным.'), ENT_QUOTES, 'UTF-8') ?></span></div>
<div class="row g-3 mb-3 crm-kpi-row"><div class="col-md-3"><div class="crm-card crm-kpi-card"><small class="text-muted" data-i18n="analytics.kpi_total_tasks"><?= htmlspecialchars($t('analytics.kpi_total_tasks', 'Всего задач'), ENT_QUOTES, 'UTF-8') ?></small><h2 class="h4 mb-0"><?= htmlspecialchars($t('page.loading', 'Загрузка...'), ENT_QUOTES, 'UTF-8') ?></h2><span class="crm-badge archived" data-i18n="analytics.kpi_pending_data"><?= htmlspecialchars($t('analytics.kpi_pending_data', 'Ожидание данных'), ENT_QUOTES, 'UTF-8') ?></span></div></div><div class="col-md-3"><div class="crm-card crm-kpi-card"><small class="text-muted" data-i18n="analytics.kpi_completion_rate"><?= htmlspecialchars($t('analytics.kpi_completion_rate', 'Доля завершения'), ENT_QUOTES, 'UTF-8') ?></small><h2 class="h4 mb-0"><?= htmlspecialchars($t('page.loading', 'Загрузка...'), ENT_QUOTES, 'UTF-8') ?></h2><span class="crm-badge archived" data-i18n="analytics.kpi_pending_data"><?= htmlspecialchars($t('analytics.kpi_pending_data', 'Ожидание данных'), ENT_QUOTES, 'UTF-8') ?></span></div></div><div class="col-md-3"><div class="crm-card crm-kpi-card"><small class="text-muted" data-i18n="analytics.kpi_overdue"><?= htmlspecialchars($t('analytics.kpi_overdue', 'Просрочки'), ENT_QUOTES, 'UTF-8') ?></small><h2 class="h4 mb-0"><?= htmlspecialchars($t('page.loading', 'Загрузка...'), ENT_QUOTES, 'UTF-8') ?></h2><span class="crm-badge archived" data-i18n="analytics.kpi_pending_data"><?= htmlspecialchars($t('analytics.kpi_pending_data', 'Ожидание данных'), ENT_QUOTES, 'UTF-8') ?></span></div></div><div class="col-md-3"><div class="crm-card crm-kpi-card"><small class="text-muted" data-i18n="analytics.kpi_weekly_time"><?= htmlspecialchars($t('analytics.kpi_weekly_time', 'Лог времени за неделю'), ENT_QUOTES, 'UTF-8') ?></small><h2 class="h4 mb-0"><?= htmlspecialchars($t('page.loading', 'Загрузка...'), ENT_QUOTES, 'UTF-8') ?></h2><span class="crm-badge archived" data-i18n="analytics.kpi_pending_data"><?= htmlspecialchars($t('analytics.kpi_pending_data', 'Ожидание данных'), ENT_QUOTES, 'UTF-8') ?></span></div></div></div>
<div class="row g-3 mb-3">
  <div class="col-12">
    <div class="crm-card crm-section-card" id="analyticsAiCard" data-ai-state="idle">
      <div class="crm-section-head"><div><h2 class="h6 mb-0" data-i18n="analytics.section_ai_explanation"><?= htmlspecialchars($t('analytics.section_ai_explanation', 'AI-объяснение аналитики'), ENT_QUOTES, 'UTF-8') ?></h2><div class="crm-section-note" data-i18n="analytics.note_ai_explanation"><?= htmlspecialchars($t('analytics.note_ai_explanation', 'AI объясняет KPI и риски, но не заменяет числовые метрики.'), ENT_QUOTES, 'UTF-8') ?></div></div></div>
      <div class="crm-analytics-ai-pills mb-2">
        <button class="btn btn-sm crm-btn-primary" type="button" id="analyticsAiKpiBtn" title="<?= htmlspecialchars($t('analytics.btn_ai_kpi_title', 'Сформировать AI-объяснение текущих KPI'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-title="analytics.btn_ai_kpi_title" data-i18n="analytics.btn_ai_kpi"><?= htmlspecialchars($t('analytics.btn_ai_kpi', 'Пояснить KPI'), ENT_QUOTES, 'UTF-8') ?></button>
        <button class="btn btn-sm btn-light" type="button" id="analyticsAiRisksBtn" title="<?= htmlspecialchars($t('analytics.btn_ai_risks_title', 'Сформировать AI-пояснение ключевых рисков'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-title="analytics.btn_ai_risks_title" data-i18n="analytics.btn_ai_risks"><?= htmlspecialchars($t('analytics.btn_ai_risks', 'Пояснить риски'), ENT_QUOTES, 'UTF-8') ?></button>
        <button class="btn btn-sm btn-light" type="button" id="analyticsAiWorkloadBtn" title="<?= htmlspecialchars($t('analytics.btn_ai_workload_title', 'Сформировать AI-сводку по загрузке команд'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-title="analytics.btn_ai_workload_title" data-i18n="analytics.btn_ai_workload"><?= htmlspecialchars($t('analytics.btn_ai_workload', 'Сводка загрузки'), ENT_QUOTES, 'UTF-8') ?></button>
        <button class="btn btn-sm btn-light" type="button" id="analyticsAiPreviewBtn" disabled title="<?= htmlspecialchars($t('analytics.btn_ai_preview_title', 'Открыть предпросмотр AI-предложения'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-title="analytics.btn_ai_preview_title" data-i18n="analytics.btn_ai_preview"><?= htmlspecialchars($t('analytics.btn_ai_preview', 'Предпросмотр'), ENT_QUOTES, 'UTF-8') ?></button>
        <button class="btn btn-sm crm-btn-muted" type="button" id="analyticsAiDismissBtn" disabled title="<?= htmlspecialchars($t('analytics.btn_ai_dismiss_title', 'Отклонить текущее AI-предложение'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-title="analytics.btn_ai_dismiss_title" data-i18n="analytics.btn_ai_dismiss"><?= htmlspecialchars($t('analytics.btn_ai_dismiss', 'Отклонить'), ENT_QUOTES, 'UTF-8') ?></button>
      </div>
      <div class="small text-muted mb-2" id="analyticsAiState" data-i18n="analytics.ai_state_idle"><?= htmlspecialchars($t('analytics.ai_state_idle', 'AI-объяснение пока не сформировано.'), ENT_QUOTES, 'UTF-8') ?></div>
      <div class="crm-analytics-ai-result">
        <div class="crm-metric-tile mb-2"><small class="text-muted d-block" data-i18n="analytics.ai_summary_label"><?= htmlspecialchars($t('analytics.ai_summary_label', 'Резюме'), ENT_QUOTES, 'UTF-8') ?></small><div id="analyticsAiSummaryText" data-i18n="analytics.ai_summary_empty"><?= htmlspecialchars($t('analytics.ai_summary_empty', 'Нажмите «Пояснить KPI», чтобы получить объяснение по текущим метрикам.'), ENT_QUOTES, 'UTF-8') ?></div></div>
        <div class="crm-metric-tile mb-2"><small class="text-muted d-block" data-i18n="analytics.ai_facts_label"><?= htmlspecialchars($t('analytics.ai_facts_label', 'Факты / KPI'), ENT_QUOTES, 'UTF-8') ?></small><div id="analyticsAiFacts" data-i18n="analytics.ai_facts_empty">—</div></div>
        <div class="crm-metric-tile"><small class="text-muted d-block" data-i18n="analytics.ai_risks_label"><?= htmlspecialchars($t('analytics.ai_risks_label', 'Риски и вопросы'), ENT_QUOTES, 'UTF-8') ?></small><div id="analyticsAiInferences" data-i18n="analytics.ai_risks_empty">—</div></div>
      </div>
    </div>
  </div>
</div>
<div class="row g-3 mt-1"><div class="col-lg-6"><div class="crm-card crm-section-card"><div class="crm-section-head"><div><h2 class="h6 mb-0" data-i18n="analytics.section_projects_at_risk"><?= htmlspecialchars($t('analytics.section_projects_at_risk', 'Проекты под риском'), ENT_QUOTES, 'UTF-8') ?></h2><div class="crm-section-note" data-i18n="analytics.note_projects_at_risk"><?= htmlspecialchars($t('analytics.note_projects_at_risk', 'Приоритет по просрочкам, блокировкам и текущему статусу проекта.'), ENT_QUOTES, 'UTF-8') ?></div></div></div><div data-analytics-projects><div class="text-muted" data-i18n="analytics.loading_projects"><?= htmlspecialchars($t('analytics.loading_projects', 'Загрузка проектных метрик...'), ENT_QUOTES, 'UTF-8') ?></div></div></div></div><div class="col-lg-6"><div class="crm-card crm-section-card"><div class="crm-section-head"><div><h2 class="h6 mb-0" data-i18n="analytics.section_users"><?= htmlspecialchars($t('analytics.section_users', 'Исполнители'), ENT_QUOTES, 'UTF-8') ?></h2><div class="crm-section-note" data-i18n="analytics.note_users"><?= htmlspecialchars($t('analytics.note_users', 'Фактическая активность и доля завершения по пользователям.'), ENT_QUOTES, 'UTF-8') ?></div></div></div><div data-analytics-users><div class="text-muted" data-i18n="analytics.loading_users"><?= htmlspecialchars($t('analytics.loading_users', 'Загрузка пользовательских метрик...'), ENT_QUOTES, 'UTF-8') ?></div></div></div></div></div>
<div class="row g-3 mt-1"><div class="col-lg-12"><div class="crm-card crm-section-card"><div class="crm-section-head"><div><h2 class="h6 mb-0" data-i18n="analytics.section_teams"><?= htmlspecialchars($t('analytics.section_teams', 'Команды'), ENT_QUOTES, 'UTF-8') ?></h2><div class="crm-section-note" data-i18n="analytics.note_teams"><?= htmlspecialchars($t('analytics.note_teams', 'Команды считаются по привязке проектов и суммарной загрузке задач.'), ENT_QUOTES, 'UTF-8') ?></div></div></div><div data-analytics-teams><div class="crm-metric-tile mb-2 text-muted" data-i18n="analytics.loading_teams"><?= htmlspecialchars($t('analytics.loading_teams', 'Загрузка командных метрик...'), ENT_QUOTES, 'UTF-8') ?></div></div></div></div></div>
</main></div></div>
