<?php declare(strict_types=1); ?>
<?php $title = $t('clients.title', 'TropaTT — Клиенты'); ?>
<body data-page="clients" data-protected="1"><div class="crm-app">
<aside class="crm-sidebar"><div class="crm-brand"><span class="crm-brand-mark"></span> <?= htmlspecialchars($t('app.name', 'TropaTT'), ENT_QUOTES, 'UTF-8') ?></div><nav class="nav flex-column crm-nav"></nav></aside>
<div class="crm-main-wrap"><header class="crm-topbar py-2"><div class="container-fluid"></div></header>
<main class="crm-content crm-clients-page"><div class="crm-page-head"><div><ol class="breadcrumb mb-1"><li class="breadcrumb-item"><a href="index.php?route=dashboard" data-i18n="page.dashboard"><?= htmlspecialchars($t('page.dashboard', 'Главная'), ENT_QUOTES, 'UTF-8') ?></a></li><li class="breadcrumb-item active" data-i18n="clients.breadcrumb"><?= htmlspecialchars($t('clients.breadcrumb', 'Клиенты'), ENT_QUOTES, 'UTF-8') ?></li></ol><h1 class="crm-page-title" data-i18n="clients.page_title"><?= htmlspecialchars($t('clients.page_title', 'Клиенты'), ENT_QUOTES, 'UTF-8') ?></h1><p class="crm-subtitle" data-i18n="clients.page_subtitle"><?= htmlspecialchars($t('clients.page_subtitle', 'Список клиентов, контактов и реквизитов.'), ENT_QUOTES, 'UTF-8') ?></p></div><div class="crm-page-actions"><select id="clientsSavedViewSelect" class="form-select form-select-sm crm-field-w-220" aria-label="<?= htmlspecialchars($t('clients.saved_view_aria', 'Сохраненные виды клиентов'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-aria-label="clients.saved_view_aria"><option value="" data-i18n="clients.opt_default_view"><?= htmlspecialchars($t('clients.opt_default_view', 'Вид по умолчанию'), ENT_QUOTES, 'UTF-8') ?></option></select><button id="clientsSaveViewBtn" class="btn crm-btn-secondary" type="button" data-i18n="clients.btn_save_view"><?= htmlspecialchars($t('clients.btn_save_view', 'Сохранить вид'), ENT_QUOTES, 'UTF-8') ?></button><button id="clientsDeleteViewBtn" class="btn crm-btn-secondary" type="button" data-i18n="clients.btn_delete_view"><?= htmlspecialchars($t('clients.btn_delete_view', 'Удалить вид'), ENT_QUOTES, 'UTF-8') ?></button><a class="btn crm-btn-secondary" href="index.php?route=companies" data-i18n="clients.link_companies"><?= htmlspecialchars($t('clients.link_companies', 'Компании'), ENT_QUOTES, 'UTF-8') ?></a><a class="btn crm-btn-secondary" href="index.php?route=contacts" data-i18n="clients.link_contacts"><?= htmlspecialchars($t('clients.link_contacts', 'Контакты'), ENT_QUOTES, 'UTF-8') ?></a><button class="btn crm-btn-muted" type="button" id="clientsCompactToggle" data-i18n="clients.btn_compact"><?= htmlspecialchars($t('clients.btn_compact', 'Компактный вид'), ENT_QUOTES, 'UTF-8') ?></button><button class="btn crm-btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#clientCreateModal" data-i18n="clients.btn_create"><?= htmlspecialchars($t('clients.btn_create', 'Создать клиента'), ENT_QUOTES, 'UTF-8') ?></button></div></div>

<div class="crm-card crm-section-card crm-filters-card mb-3">
  <div class="row g-2 crm-clients-filters">
    <div class="col-md-5"><label class="form-label" for="clientsFilterSearch" data-i18n="clients.filter_search_label"><?= htmlspecialchars($t('clients.filter_search_label', 'Поиск'), ENT_QUOTES, 'UTF-8') ?></label><input id="clientsFilterSearch" class="form-control" placeholder="<?= htmlspecialchars($t('clients.filter_search_placeholder', 'Название, ИНН, email, телефон, сайт'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-placeholder="clients.filter_search_placeholder"></div>
    <div class="col-md-3"><label class="form-label" for="clientsFilterType" data-i18n="clients.filter_type_label"><?= htmlspecialchars($t('clients.filter_type_label', 'Тип клиента'), ENT_QUOTES, 'UTF-8') ?></label><select id="clientsFilterType" class="form-select"><option value="" data-i18n="page.all_types"><?= htmlspecialchars($t('page.all_types', 'Все типы'), ENT_QUOTES, 'UTF-8') ?></option><option value="individual" data-i18n="clients.type_individual"><?= htmlspecialchars($t('clients.type_individual', 'Физлицо'), ENT_QUOTES, 'UTF-8') ?></option><option value="sole_proprietor" data-i18n="clients.type_sole_proprietor"><?= htmlspecialchars($t('clients.type_sole_proprietor', 'ИП'), ENT_QUOTES, 'UTF-8') ?></option><option value="legal_entity" data-i18n="clients.type_legal_entity"><?= htmlspecialchars($t('clients.type_legal_entity', 'Юрлицо'), ENT_QUOTES, 'UTF-8') ?></option></select></div>
    <div class="col-md-2"><label class="form-label" for="clientsFilterStatus" data-i18n="clients.filter_status_label"><?= htmlspecialchars($t('clients.filter_status_label', 'Статус'), ENT_QUOTES, 'UTF-8') ?></label><select id="clientsFilterStatus" class="form-select"><option value="" data-i18n="page.all_statuses"><?= htmlspecialchars($t('page.all_statuses', 'Все статусы'), ENT_QUOTES, 'UTF-8') ?></option><option value="active" data-i18n="clients.status_active"><?= htmlspecialchars($t('clients.status_active', 'Активен'), ENT_QUOTES, 'UTF-8') ?></option><option value="inactive" data-i18n="clients.status_inactive"><?= htmlspecialchars($t('clients.status_inactive', 'Неактивен'), ENT_QUOTES, 'UTF-8') ?></option><option value="archived" data-i18n="clients.status_archived"><?= htmlspecialchars($t('clients.status_archived', 'Архив'), ENT_QUOTES, 'UTF-8') ?></option></select></div>
    <div class="col-md-2"><label class="form-label" for="clientsFilterHasWebsite" data-i18n="clients.filter_website_label"><?= htmlspecialchars($t('clients.filter_website_label', 'Сайт'), ENT_QUOTES, 'UTF-8') ?></label><select id="clientsFilterHasWebsite" class="form-select"><option value="" data-i18n="page.any"><?= htmlspecialchars($t('page.any', 'Любой'), ENT_QUOTES, 'UTF-8') ?></option><option value="1" data-i18n="clients.filter_website_with"><?= htmlspecialchars($t('clients.filter_website_with', 'Только с сайтом'), ENT_QUOTES, 'UTF-8') ?></option><option value="0" data-i18n="clients.filter_website_without"><?= htmlspecialchars($t('clients.filter_website_without', 'Без сайта'), ENT_QUOTES, 'UTF-8') ?></option></select></div>
    <div class="col-md-3"><label class="form-label" for="clientsFilterCreatedFrom" data-i18n="clients.filter_created_from_label"><?= htmlspecialchars($t('clients.filter_created_from_label', 'Создан с'), ENT_QUOTES, 'UTF-8') ?></label><input id="clientsFilterCreatedFrom" type="date" class="form-control"></div>
    <div class="col-md-3"><label class="form-label" for="clientsFilterCreatedTo" data-i18n="clients.filter_created_to_label"><?= htmlspecialchars($t('clients.filter_created_to_label', 'Создан по'), ENT_QUOTES, 'UTF-8') ?></label><input id="clientsFilterCreatedTo" type="date" class="form-control"></div>
    <div class="col-md-3"><label class="form-label" for="clientsSortBy" data-i18n="clients.sort_by_label"><?= htmlspecialchars($t('clients.sort_by_label', 'Сортировка'), ENT_QUOTES, 'UTF-8') ?></label><select id="clientsSortBy" class="form-select"><option value="created_at" data-i18n="clients.sort_created_at"><?= htmlspecialchars($t('clients.sort_created_at', 'Дата создания'), ENT_QUOTES, 'UTF-8') ?></option><option value="updated_at" data-i18n="clients.sort_updated_at"><?= htmlspecialchars($t('clients.sort_updated_at', 'Дата обновления'), ENT_QUOTES, 'UTF-8') ?></option><option value="title" data-i18n="clients.sort_title"><?= htmlspecialchars($t('clients.sort_title', 'Название'), ENT_QUOTES, 'UTF-8') ?></option></select></div>
    <div class="col-md-3"><label class="form-label" for="clientsSortDir" data-i18n="clients.sort_dir_label"><?= htmlspecialchars($t('clients.sort_dir_label', 'Направление'), ENT_QUOTES, 'UTF-8') ?></label><select id="clientsSortDir" class="form-select"><option value="DESC" data-i18n="clients.sort_desc"><?= htmlspecialchars($t('clients.sort_desc', 'По убыванию'), ENT_QUOTES, 'UTF-8') ?></option><option value="ASC" data-i18n="clients.sort_asc"><?= htmlspecialchars($t('clients.sort_asc', 'По возрастанию'), ENT_QUOTES, 'UTF-8') ?></option></select></div>
    <div class="col-12 d-flex justify-content-end"><button class="btn crm-btn-muted" type="button" id="clientsFilterReset" data-i18n="page.reset"><?= htmlspecialchars($t('page.reset', 'Сбросить'), ENT_QUOTES, 'UTF-8') ?></button></div>
  </div>
</div>

<div id="clientsBulkActionsBar" class="alert alert-primary d-none d-flex justify-content-between align-items-center" role="region" aria-label="<?= htmlspecialchars($t('clients.bulk_aria_label', 'Bulk actions clients'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-aria-label="clients.bulk_aria_label">
  <div><span data-i18n="clients.bulk_selected_prefix"><?= htmlspecialchars($t('clients.bulk_selected_prefix', 'Выбрано клиентов:'), ENT_QUOTES, 'UTF-8') ?></span> <strong data-clients-selected-count>0</strong> <span class="small ms-2" id="clientsBulkResult" aria-live="polite"></span></div>
  <div class="d-flex gap-2">
    <select id="clientsBulkStatusSelect" class="form-select form-select-sm crm-field-w-170" aria-label="<?= htmlspecialchars($t('clients.bulk_status_aria', 'Изменить статус клиентов'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-aria-label="clients.bulk_status_aria">
      <option value="" data-i18n="page.status_placeholder"><?= htmlspecialchars($t('page.status_placeholder', 'Статус...'), ENT_QUOTES, 'UTF-8') ?></option>
      <option value="active" data-i18n="clients.status_active"><?= htmlspecialchars($t('clients.status_active', 'Активен'), ENT_QUOTES, 'UTF-8') ?></option>
      <option value="inactive" data-i18n="clients.status_inactive"><?= htmlspecialchars($t('clients.status_inactive', 'Неактивен'), ENT_QUOTES, 'UTF-8') ?></option>
      <option value="archived" data-i18n="clients.status_archived"><?= htmlspecialchars($t('clients.status_archived', 'Архив'), ENT_QUOTES, 'UTF-8') ?></option>
    </select>
    <button class="btn btn-sm crm-btn-danger-soft" type="button" id="clientsBulkDeleteBtn" data-i18n="page.delete"><?= htmlspecialchars($t('page.delete', 'Удалить'), ENT_QUOTES, 'UTF-8') ?></button>
  </div>
</div>

<div class="crm-card crm-section-card p-0 table-responsive"><table id="clientsTable" class="table crm-table mb-0"><thead><tr><th style="width:40px"><input class="form-check-input" type="checkbox" id="clientsBulkSelectAll" aria-label="<?= htmlspecialchars($t('clients.bulk_select_all_aria', 'Выбрать всех клиентов'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-aria-label="clients.bulk_select_all_aria"></th><th data-i18n="clients.th_name"><?= htmlspecialchars($t('clients.th_name', 'Клиент'), ENT_QUOTES, 'UTF-8') ?></th><th data-i18n="clients.th_type"><?= htmlspecialchars($t('clients.th_type', 'Тип'), ENT_QUOTES, 'UTF-8') ?></th><th data-i18n="clients.th_inn"><?= htmlspecialchars($t('clients.th_inn', 'ИНН'), ENT_QUOTES, 'UTF-8') ?></th><th data-i18n="clients.th_email"><?= htmlspecialchars($t('clients.th_email', 'Email'), ENT_QUOTES, 'UTF-8') ?></th><th data-i18n="clients.th_phone"><?= htmlspecialchars($t('clients.th_phone', 'Телефон'), ENT_QUOTES, 'UTF-8') ?></th><th data-i18n="clients.th_status"><?= htmlspecialchars($t('clients.th_status', 'Статус'), ENT_QUOTES, 'UTF-8') ?></th><th data-i18n="clients.th_updated"><?= htmlspecialchars($t('clients.th_updated', 'Обновлен'), ENT_QUOTES, 'UTF-8') ?></th><th style="width:96px" data-i18n="clients.th_actions"><?= htmlspecialchars($t('clients.th_actions', 'Действия'), ENT_QUOTES, 'UTF-8') ?></th></tr></thead><tbody id="clientsTableBody"><tr><td colspan="9" class="text-muted" data-i18n="clients.loading"><?= htmlspecialchars($t('clients.loading', 'Загрузка клиентов...'), ENT_QUOTES, 'UTF-8') ?></td></tr></tbody></table></div>
</main></div></div>

<div class="modal fade" id="clientCreateModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-xl modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" data-i18n="clients.create_modal_title"><?= htmlspecialchars($t('clients.create_modal_title', 'Создать клиента'), ENT_QUOTES, 'UTF-8') ?></h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="<?= htmlspecialchars($t('page.close', 'Закрыть'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-aria-label="page.close"></button></div><form id="clientsCreateForm"><div class="modal-body"><div class="row g-3">
  <div class="col-12 d-none" data-form-error-summary></div>
  <div class="col-md-4"><label class="form-label" data-i18n="clients.field_type"><?= htmlspecialchars($t('clients.field_type', 'Тип клиента'), ENT_QUOTES, 'UTF-8') ?></label><select class="form-select" name="client_type" data-client-type-input><option value="individual" data-i18n="clients.type_individual"><?= htmlspecialchars($t('clients.type_individual', 'Физлицо'), ENT_QUOTES, 'UTF-8') ?></option><option value="sole_proprietor" data-i18n="clients.type_sole_proprietor"><?= htmlspecialchars($t('clients.type_sole_proprietor', 'ИП'), ENT_QUOTES, 'UTF-8') ?></option><option value="legal_entity" data-i18n="clients.type_legal_entity"><?= htmlspecialchars($t('clients.type_legal_entity', 'Юрлицо'), ENT_QUOTES, 'UTF-8') ?></option></select></div>
  <div class="col-md-8"><label class="form-label" data-i18n="clients.field_title"><?= htmlspecialchars($t('clients.field_title', 'Название'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="title" maxlength="255" required></div>
  <div class="col-md-6" data-client-type-group="sole_proprietor,legal_entity"><label class="form-label" data-i18n="clients.field_legal_name"><?= htmlspecialchars($t('clients.field_legal_name', 'Юридическое наименование / ФИО ИП'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="legal_name" maxlength="255"></div>
  <div class="col-md-4" data-client-type-group="sole_proprietor,legal_entity"><label class="form-label" data-i18n="clients.field_inn"><?= htmlspecialchars($t('clients.field_inn', 'ИНН'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="tax_inn" maxlength="12"></div>
  <div class="col-md-4" data-client-type-group="legal_entity"><label class="form-label" data-i18n="clients.field_kpp"><?= htmlspecialchars($t('clients.field_kpp', 'КПП'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="tax_kpp" maxlength="9"></div>
  <div class="col-md-4" data-client-type-group="legal_entity"><label class="form-label" data-i18n="clients.field_ogrn"><?= htmlspecialchars($t('clients.field_ogrn', 'ОГРН'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="tax_ogrn" maxlength="13"></div>
  <div class="col-md-4" data-client-type-group="sole_proprietor"><label class="form-label" data-i18n="clients.field_ogrnip"><?= htmlspecialchars($t('clients.field_ogrnip', 'ОГРНИП'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="tax_ogrnip" maxlength="15"></div>
  <div class="col-md-4"><label class="form-label" data-i18n="clients.field_email"><?= htmlspecialchars($t('clients.field_email', 'Email'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" type="email" name="email" maxlength="190"></div>
  <div class="col-md-4"><label class="form-label" data-i18n="clients.field_phone"><?= htmlspecialchars($t('clients.field_phone', 'Телефон'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="phone" maxlength="64"></div>
  <div class="col-md-4"><label class="form-label" data-i18n="clients.field_website"><?= htmlspecialchars($t('clients.field_website', 'Сайт'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="website" maxlength="2048" placeholder="<?= htmlspecialchars($t('clients.placeholder_website', 'https://example.com'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-placeholder="clients.placeholder_website"></div>
  <div class="col-md-4"><label class="form-label" data-i18n="clients.field_messenger"><?= htmlspecialchars($t('clients.field_messenger', 'Мессенджер'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="messenger" maxlength="190"></div>
  <div class="col-md-4" data-client-type-group="sole_proprietor,legal_entity"><label class="form-label" data-i18n="clients.field_bank_account"><?= htmlspecialchars($t('clients.field_bank_account', 'Расчетный счет'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="bank_account" maxlength="34"></div>
  <div class="col-md-4" data-client-type-group="sole_proprietor,legal_entity"><label class="form-label" data-i18n="clients.field_bik"><?= htmlspecialchars($t('clients.field_bik', 'БИК'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="bank_bik" maxlength="9"></div>
  <div class="col-md-4" data-client-type-group="sole_proprietor,legal_entity"><label class="form-label" data-i18n="clients.field_corr_account"><?= htmlspecialchars($t('clients.field_corr_account', 'Корр. счет'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="bank_corr_account" maxlength="34"></div>
  <div class="col-md-8" data-client-type-group="sole_proprietor,legal_entity"><label class="form-label" data-i18n="clients.field_bank_name"><?= htmlspecialchars($t('clients.field_bank_name', 'Банк'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="bank_name" maxlength="255"></div>
  <div class="col-md-4"><label class="form-label" data-i18n="clients.field_status"><?= htmlspecialchars($t('clients.field_status', 'Статус'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="status" maxlength="64" value="active"></div>
  <div class="col-md-6"><label class="form-label" data-i18n="clients.field_address_legal"><?= htmlspecialchars($t('clients.field_address_legal', 'Юридический адрес'), ENT_QUOTES, 'UTF-8') ?></label><textarea class="form-control" name="address_legal" rows="2"></textarea></div>
  <div class="col-md-6"><label class="form-label" data-i18n="clients.field_address_postal"><?= htmlspecialchars($t('clients.field_address_postal', 'Почтовый адрес'), ENT_QUOTES, 'UTF-8') ?></label><textarea class="form-control" name="address_postal" rows="2"></textarea></div>
  <div class="col-12"><label class="form-label" data-i18n="clients.field_notes"><?= htmlspecialchars($t('clients.field_notes', 'Комментарий'), ENT_QUOTES, 'UTF-8') ?></label><textarea class="form-control" name="notes" rows="2"></textarea></div>
  <div class="col-12"><label class="form-label" data-i18n="clients.field_extra_attributes"><?= htmlspecialchars($t('clients.field_extra_attributes', 'Дополнительные поля (JSON)'), ENT_QUOTES, 'UTF-8') ?></label><textarea class="form-control" name="extra_attributes_text" rows="3"></textarea></div>
</div></div><div class="modal-footer"><button class="btn crm-btn-secondary" type="button" data-bs-dismiss="modal" data-i18n="page.cancel"><?= htmlspecialchars($t('page.cancel', 'Отмена'), ENT_QUOTES, 'UTF-8') ?></button><button class="btn crm-btn-primary" type="submit" data-i18n="page.create"><?= htmlspecialchars($t('page.create', 'Создать'), ENT_QUOTES, 'UTF-8') ?></button></div></form></div></div></div>

<div class="modal fade" id="clientEditModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-xl modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" data-i18n="clients.edit_modal_title"><?= htmlspecialchars($t('clients.edit_modal_title', 'Редактировать клиента'), ENT_QUOTES, 'UTF-8') ?></h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="<?= htmlspecialchars($t('page.close', 'Закрыть'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-aria-label="page.close"></button></div><form id="clientsEditForm"><div class="modal-body"><input type="hidden" name="public_id"><div class="row g-3">
  <div class="col-12 d-none" data-form-error-summary></div>
  <div class="col-md-4"><label class="form-label" data-i18n="clients.field_type"><?= htmlspecialchars($t('clients.field_type', 'Тип клиента'), ENT_QUOTES, 'UTF-8') ?></label><select class="form-select" name="client_type" data-client-type-input><option value="individual" data-i18n="clients.type_individual"><?= htmlspecialchars($t('clients.type_individual', 'Физлицо'), ENT_QUOTES, 'UTF-8') ?></option><option value="sole_proprietor" data-i18n="clients.type_sole_proprietor"><?= htmlspecialchars($t('clients.type_sole_proprietor', 'ИП'), ENT_QUOTES, 'UTF-8') ?></option><option value="legal_entity" data-i18n="clients.type_legal_entity"><?= htmlspecialchars($t('clients.type_legal_entity', 'Юрлицо'), ENT_QUOTES, 'UTF-8') ?></option></select></div>
  <div class="col-md-8"><label class="form-label" data-i18n="clients.field_title"><?= htmlspecialchars($t('clients.field_title', 'Название'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="title" maxlength="255" required></div>
  <div class="col-md-6" data-client-type-group="sole_proprietor,legal_entity"><label class="form-label" data-i18n="clients.field_legal_name"><?= htmlspecialchars($t('clients.field_legal_name', 'Юридическое наименование / ФИО ИП'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="legal_name" maxlength="255"></div>
  <div class="col-md-4" data-client-type-group="sole_proprietor,legal_entity"><label class="form-label" data-i18n="clients.field_inn"><?= htmlspecialchars($t('clients.field_inn', 'ИНН'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="tax_inn" maxlength="12"></div>
  <div class="col-md-4" data-client-type-group="legal_entity"><label class="form-label" data-i18n="clients.field_kpp"><?= htmlspecialchars($t('clients.field_kpp', 'КПП'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="tax_kpp" maxlength="9"></div>
  <div class="col-md-4" data-client-type-group="legal_entity"><label class="form-label" data-i18n="clients.field_ogrn"><?= htmlspecialchars($t('clients.field_ogrn', 'ОГРН'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="tax_ogrn" maxlength="13"></div>
  <div class="col-md-4" data-client-type-group="sole_proprietor"><label class="form-label" data-i18n="clients.field_ogrnip"><?= htmlspecialchars($t('clients.field_ogrnip', 'ОГРНИП'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="tax_ogrnip" maxlength="15"></div>
  <div class="col-md-4"><label class="form-label" data-i18n="clients.field_email"><?= htmlspecialchars($t('clients.field_email', 'Email'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" type="email" name="email" maxlength="190"></div>
  <div class="col-md-4"><label class="form-label" data-i18n="clients.field_phone"><?= htmlspecialchars($t('clients.field_phone', 'Телефон'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="phone" maxlength="64"></div>
  <div class="col-md-4"><label class="form-label" data-i18n="clients.field_website"><?= htmlspecialchars($t('clients.field_website', 'Сайт'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="website" maxlength="2048"></div>
  <div class="col-md-4"><label class="form-label" data-i18n="clients.field_messenger"><?= htmlspecialchars($t('clients.field_messenger', 'Мессенджер'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="messenger" maxlength="190"></div>
  <div class="col-md-4" data-client-type-group="sole_proprietor,legal_entity"><label class="form-label" data-i18n="clients.field_bank_account"><?= htmlspecialchars($t('clients.field_bank_account', 'Расчетный счет'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="bank_account" maxlength="34"></div>
  <div class="col-md-4" data-client-type-group="sole_proprietor,legal_entity"><label class="form-label" data-i18n="clients.field_bik"><?= htmlspecialchars($t('clients.field_bik', 'БИК'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="bank_bik" maxlength="9"></div>
  <div class="col-md-4" data-client-type-group="sole_proprietor,legal_entity"><label class="form-label" data-i18n="clients.field_corr_account"><?= htmlspecialchars($t('clients.field_corr_account', 'Корр. счет'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="bank_corr_account" maxlength="34"></div>
  <div class="col-md-8" data-client-type-group="sole_proprietor,legal_entity"><label class="form-label" data-i18n="clients.field_bank_name"><?= htmlspecialchars($t('clients.field_bank_name', 'Банк'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="bank_name" maxlength="255"></div>
  <div class="col-md-4"><label class="form-label" data-i18n="clients.field_status"><?= htmlspecialchars($t('clients.field_status', 'Статус'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="status" maxlength="64"></div>
  <div class="col-md-6"><label class="form-label" data-i18n="clients.field_address_legal"><?= htmlspecialchars($t('clients.field_address_legal', 'Юридический адрес'), ENT_QUOTES, 'UTF-8') ?></label><textarea class="form-control" name="address_legal" rows="2"></textarea></div>
  <div class="col-md-6"><label class="form-label" data-i18n="clients.field_address_postal"><?= htmlspecialchars($t('clients.field_address_postal', 'Почтовый адрес'), ENT_QUOTES, 'UTF-8') ?></label><textarea class="form-control" name="address_postal" rows="2"></textarea></div>
  <div class="col-12"><label class="form-label" data-i18n="clients.field_notes"><?= htmlspecialchars($t('clients.field_notes', 'Комментарий'), ENT_QUOTES, 'UTF-8') ?></label><textarea class="form-control" name="notes" rows="2"></textarea></div>
  <div class="col-12"><label class="form-label" data-i18n="clients.field_extra_attributes"><?= htmlspecialchars($t('clients.field_extra_attributes', 'Дополнительные поля (JSON)'), ENT_QUOTES, 'UTF-8') ?></label><textarea class="form-control" name="extra_attributes_text" rows="3"></textarea></div>
</div></div><div class="modal-footer"><button class="btn crm-btn-secondary" type="button" data-bs-dismiss="modal" data-i18n="page.cancel"><?= htmlspecialchars($t('page.cancel', 'Отмена'), ENT_QUOTES, 'UTF-8') ?></button><button class="btn crm-btn-danger-soft me-auto" type="button" id="clientsDeleteInModalBtn" data-i18n="clients.btn_delete"><?= htmlspecialchars($t('clients.btn_delete', 'Удалить клиента'), ENT_QUOTES, 'UTF-8') ?></button><button class="btn crm-btn-primary" type="submit" data-i18n="page.save"><?= htmlspecialchars($t('page.save', 'Сохранить'), ENT_QUOTES, 'UTF-8') ?></button></div></form></div></div></div>
</body>
