<?php declare(strict_types=1); ?>
<?php $title = $t('contacts.title', 'TropaTT — Контакты'); ?>
<body data-page="contacts" data-protected="1"><div class="crm-app">
<aside class="crm-sidebar"><div class="crm-brand"><span class="crm-brand-mark"></span> <?= htmlspecialchars($t('app.name', 'TropaTT'), ENT_QUOTES, 'UTF-8') ?></div><nav class="nav flex-column crm-nav"></nav></aside>
<div class="crm-main-wrap"><header class="crm-topbar py-2"><div class="container-fluid"></div></header>
<main class="crm-content crm-contacts-page"><div class="crm-page-head"><div><ol class="breadcrumb mb-1"><li class="breadcrumb-item"><a href="index.php?route=dashboard" data-i18n="page.dashboard"><?= htmlspecialchars($t('page.dashboard', 'Главная'), ENT_QUOTES, 'UTF-8') ?></a></li><li class="breadcrumb-item active" data-i18n="contacts.breadcrumb"><?= htmlspecialchars($t('contacts.breadcrumb', 'Контакты'), ENT_QUOTES, 'UTF-8') ?></li></ol><h1 class="crm-page-title" data-i18n="contacts.page_title"><?= htmlspecialchars($t('contacts.page_title', 'Контакты'), ENT_QUOTES, 'UTF-8') ?></h1><p class="crm-subtitle" data-i18n="contacts.page_subtitle"><?= htmlspecialchars($t('contacts.page_subtitle', 'Контактные лица контрагентов.'), ENT_QUOTES, 'UTF-8') ?></p></div><div class="crm-page-actions"><button class="btn crm-btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#contactCreateModal" data-i18n="contacts.btn_create"><?= htmlspecialchars($t('contacts.btn_create', 'Создать контакт'), ENT_QUOTES, 'UTF-8') ?></button></div></div>

<div class="crm-card crm-section-card crm-filters-card mb-3">
  <div class="row g-2 crm-contacts-filters">
    <div class="col-md-5"><label class="form-label" for="contactsFilterSearch" data-i18n="contacts.filter_search_label"><?= htmlspecialchars($t('contacts.filter_search_label', 'Поиск'), ENT_QUOTES, 'UTF-8') ?></label><input id="contactsFilterSearch" class="form-control" placeholder="<?= htmlspecialchars($t('contacts.filter_search_placeholder', 'ФИО, email, телефон'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-placeholder="contacts.filter_search_placeholder"></div>
    <div class="col-md-3"><label class="form-label" data-i18n="contacts.filter_counterparty_label"><?= htmlspecialchars($t('contacts.filter_counterparty_label', 'Контрагент'), ENT_QUOTES, 'UTF-8') ?></label><select id="contactsFilterCounterparty" class="form-select"><option value="" data-i18n="page.all_counterparties"><?= htmlspecialchars($t('page.all_counterparties', 'Все контрагенты'), ENT_QUOTES, 'UTF-8') ?></option></select></div>
    <div class="col-md-2"><label class="form-label" data-i18n="contacts.filter_role_label"><?= htmlspecialchars($t('contacts.filter_role_label', 'Роль'), ENT_QUOTES, 'UTF-8') ?></label><select id="contactsFilterRole" class="form-select"><option value="" data-i18n="page.all_roles"><?= htmlspecialchars($t('page.all_roles', 'Все роли'), ENT_QUOTES, 'UTF-8') ?></option><option value="decision_maker" data-i18n="contacts.role_decision_maker"><?= htmlspecialchars($t('contacts.role_decision_maker', 'ЛПР'), ENT_QUOTES, 'UTF-8') ?></option><option value="influencer" data-i18n="contacts.role_influencer"><?= htmlspecialchars($t('contacts.role_influencer', 'Влияющий'), ENT_QUOTES, 'UTF-8') ?></option><option value="user" data-i18n="contacts.role_user"><?= htmlspecialchars($t('contacts.role_user', 'Пользователь'), ENT_QUOTES, 'UTF-8') ?></option><option value="technical" data-i18n="contacts.role_technical"><?= htmlspecialchars($t('contacts.role_technical', 'Технический'), ENT_QUOTES, 'UTF-8') ?></option></select></div>
    <div class="col-md-2"><label class="form-label" data-i18n="contacts.filter_primary_label"><?= htmlspecialchars($t('contacts.filter_primary_label', 'Основной'), ENT_QUOTES, 'UTF-8') ?></label><select id="contactsFilterPrimary" class="form-select"><option value="" data-i18n="page.all"><?= htmlspecialchars($t('page.all', 'Все'), ENT_QUOTES, 'UTF-8') ?></option><option value="1" data-i18n="contacts.filter_primary_only"><?= htmlspecialchars($t('contacts.filter_primary_only', 'Только основные'), ENT_QUOTES, 'UTF-8') ?></option></select></div>
    <div class="col-12 d-flex justify-content-end"><button class="btn crm-btn-muted" type="button" id="contactsFilterReset" data-i18n="page.reset"><?= htmlspecialchars($t('page.reset', 'Сбросить'), ENT_QUOTES, 'UTF-8') ?></button></div>
  </div>
</div>

<div class="crm-card crm-section-card p-0 table-responsive"><table id="contactsTable" class="table crm-table mb-0"><thead><tr><th data-i18n="contacts.th_contact"><?= htmlspecialchars($t('contacts.th_contact', 'Контакт'), ENT_QUOTES, 'UTF-8') ?></th><th data-i18n="contacts.th_counterparty"><?= htmlspecialchars($t('contacts.th_counterparty', 'Контрагент'), ENT_QUOTES, 'UTF-8') ?></th><th data-i18n="contacts.th_role"><?= htmlspecialchars($t('contacts.th_role', 'Роль'), ENT_QUOTES, 'UTF-8') ?></th><th data-i18n="contacts.th_email"><?= htmlspecialchars($t('contacts.th_email', 'Email'), ENT_QUOTES, 'UTF-8') ?></th><th data-i18n="contacts.th_phone"><?= htmlspecialchars($t('contacts.th_phone', 'Телефон'), ENT_QUOTES, 'UTF-8') ?></th><th data-i18n="contacts.th_primary"><?= htmlspecialchars($t('contacts.th_primary', 'Основной'), ENT_QUOTES, 'UTF-8') ?></th><th style="width:96px" data-i18n="contacts.th_actions"><?= htmlspecialchars($t('contacts.th_actions', 'Действия'), ENT_QUOTES, 'UTF-8') ?></th></tr></thead><tbody id="contactsTableBody"><tr><td colspan="7" class="text-muted" data-i18n="contacts.loading"><?= htmlspecialchars($t('contacts.loading', 'Загрузка контактов...'), ENT_QUOTES, 'UTF-8') ?></td></tr></tbody></table></div>
</main></div></div>
<div class="modal fade" id="contactCreateModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" data-i18n="contacts.create_modal_title"><?= htmlspecialchars($t('contacts.create_modal_title', 'Создать контакт'), ENT_QUOTES, 'UTF-8') ?></h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="<?= htmlspecialchars($t('page.close', 'Закрыть'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-aria-label="page.close"></button></div><form id="contactsCreateForm"><div class="modal-body"><div class="row g-3">
  <div class="col-12 d-none" data-form-error-summary></div>
  <div class="col-md-6"><label class="form-label" data-i18n="contacts.field_full_name"><?= htmlspecialchars($t('contacts.field_full_name', 'ФИО *'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="full_name" maxlength="255" required></div>
  <div class="col-md-6"><label class="form-label" data-i18n="contacts.field_counterparty"><?= htmlspecialchars($t('contacts.field_counterparty', 'Контрагент'), ENT_QUOTES, 'UTF-8') ?></label><select class="form-select" name="counterparty_public_id" id="contactCreateCounterpartySelect"><option value="" data-i18n="contacts.opt_select_counterparty"><?= htmlspecialchars($t('contacts.opt_select_counterparty', 'Выберите контрагента'), ENT_QUOTES, 'UTF-8') ?></option></select></div>
  <div class="col-md-3"><label class="form-label" data-i18n="contacts.field_email"><?= htmlspecialchars($t('contacts.field_email', 'Email'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" type="email" name="email" maxlength="190"></div>
  <div class="col-md-3"><label class="form-label" data-i18n="contacts.field_phone"><?= htmlspecialchars($t('contacts.field_phone', 'Телефон'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="phone" maxlength="64"></div>
  <div class="col-md-4"><label class="form-label" data-i18n="contacts.field_role"><?= htmlspecialchars($t('contacts.field_role', 'Роль'), ENT_QUOTES, 'UTF-8') ?></label><select class="form-select" name="role" data-role-select><option value="" data-i18n="contacts.opt_no_role"><?= htmlspecialchars($t('contacts.opt_no_role', 'Без роли'), ENT_QUOTES, 'UTF-8') ?></option><option value="decision_maker" data-i18n="contacts.role_decision_maker"><?= htmlspecialchars($t('contacts.role_decision_maker', 'ЛПР'), ENT_QUOTES, 'UTF-8') ?></option><option value="influencer" data-i18n="contacts.role_influencer"><?= htmlspecialchars($t('contacts.role_influencer', 'Влияющий'), ENT_QUOTES, 'UTF-8') ?></option><option value="user" data-i18n="contacts.role_user"><?= htmlspecialchars($t('contacts.role_user', 'Пользователь'), ENT_QUOTES, 'UTF-8') ?></option><option value="technical" data-i18n="contacts.role_technical"><?= htmlspecialchars($t('contacts.role_technical', 'Технический'), ENT_QUOTES, 'UTF-8') ?></option><option value="__custom__" data-i18n="contacts.opt_custom_role"><?= htmlspecialchars($t('contacts.opt_custom_role', 'Другая роль (своя)...'), ENT_QUOTES, 'UTF-8') ?></option></select><input class="form-control mt-2 d-none" type="text" name="role_custom" maxlength="64" placeholder="<?= htmlspecialchars($t('contacts.role_custom_placeholder', 'Введите свою роль'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-placeholder="contacts.role_custom_placeholder" data-role-custom-input></div>
  <div class="col-md-2 d-flex align-items-end"><div class="form-check"><input class="form-check-input" type="checkbox" name="is_primary" id="contactCreateIsPrimary"><label class="form-check-label" for="contactCreateIsPrimary" data-i18n="contacts.label_primary"><?= htmlspecialchars($t('contacts.label_primary', 'Основной'), ENT_QUOTES, 'UTF-8') ?></label></div></div>
</div></div><div class="modal-footer"><button class="btn crm-btn-secondary" type="button" data-bs-dismiss="modal" data-i18n="page.cancel"><?= htmlspecialchars($t('page.cancel', 'Отмена'), ENT_QUOTES, 'UTF-8') ?></button><button class="btn crm-btn-primary" type="submit" data-i18n="page.create"><?= htmlspecialchars($t('page.create', 'Создать'), ENT_QUOTES, 'UTF-8') ?></button></div></form></div></div></div>

<div class="modal fade" id="contactEditModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" data-i18n="contacts.edit_modal_title"><?= htmlspecialchars($t('contacts.edit_modal_title', 'Редактировать контакт'), ENT_QUOTES, 'UTF-8') ?></h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="<?= htmlspecialchars($t('page.close', 'Закрыть'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-aria-label="page.close"></button></div><form id="contactsEditForm"><div class="modal-body"><input type="hidden" name="public_id"><div class="row g-3">
  <div class="col-12 d-none" data-form-error-summary></div>
  <div class="col-md-6"><label class="form-label" data-i18n="contacts.field_full_name"><?= htmlspecialchars($t('contacts.field_full_name', 'ФИО *'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="full_name" maxlength="255" required></div>
  <div class="col-md-6"><label class="form-label" data-i18n="contacts.field_counterparty"><?= htmlspecialchars($t('contacts.field_counterparty', 'Контрагент'), ENT_QUOTES, 'UTF-8') ?></label><select class="form-select" name="counterparty_public_id" id="contactEditCounterpartySelect"><option value="" data-i18n="contacts.opt_select_counterparty"><?= htmlspecialchars($t('contacts.opt_select_counterparty', 'Выберите контрагента'), ENT_QUOTES, 'UTF-8') ?></option></select></div>
  <div class="col-md-3"><label class="form-label" data-i18n="contacts.field_email"><?= htmlspecialchars($t('contacts.field_email', 'Email'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" type="email" name="email" maxlength="190"></div>
  <div class="col-md-3"><label class="form-label" data-i18n="contacts.field_phone"><?= htmlspecialchars($t('contacts.field_phone', 'Телефон'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" name="phone" maxlength="64"></div>
  <div class="col-md-4"><label class="form-label" data-i18n="contacts.field_role"><?= htmlspecialchars($t('contacts.field_role', 'Роль'), ENT_QUOTES, 'UTF-8') ?></label><select class="form-select" name="role" data-role-select><option value="" data-i18n="contacts.opt_no_role"><?= htmlspecialchars($t('contacts.opt_no_role', 'Без роли'), ENT_QUOTES, 'UTF-8') ?></option><option value="decision_maker" data-i18n="contacts.role_decision_maker"><?= htmlspecialchars($t('contacts.role_decision_maker', 'ЛПР'), ENT_QUOTES, 'UTF-8') ?></option><option value="influencer" data-i18n="contacts.role_influencer"><?= htmlspecialchars($t('contacts.role_influencer', 'Влияющий'), ENT_QUOTES, 'UTF-8') ?></option><option value="user" data-i18n="contacts.role_user"><?= htmlspecialchars($t('contacts.role_user', 'Пользователь'), ENT_QUOTES, 'UTF-8') ?></option><option value="technical" data-i18n="contacts.role_technical"><?= htmlspecialchars($t('contacts.role_technical', 'Технический'), ENT_QUOTES, 'UTF-8') ?></option><option value="__custom__" data-i18n="contacts.opt_custom_role"><?= htmlspecialchars($t('contacts.opt_custom_role', 'Другая роль (своя)...'), ENT_QUOTES, 'UTF-8') ?></option></select><input class="form-control mt-2 d-none" type="text" name="role_custom" maxlength="64" placeholder="<?= htmlspecialchars($t('contacts.role_custom_placeholder', 'Введите свою роль'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-placeholder="contacts.role_custom_placeholder" data-role-custom-input></div>
  <div class="col-md-2 d-flex align-items-end"><div class="form-check"><input class="form-check-input" type="checkbox" name="is_primary" id="contactEditIsPrimary"><label class="form-check-label" for="contactEditIsPrimary" data-i18n="contacts.label_primary"><?= htmlspecialchars($t('contacts.label_primary', 'Основной'), ENT_QUOTES, 'UTF-8') ?></label></div></div>
</div>
<div class="mt-3 pt-3 border-top" id="contactKnowledgeSection">
  <h6 class="mb-2"><?= htmlspecialchars($t('contacts.section_notes', 'Связанные заметки'), ENT_QUOTES, 'UTF-8') ?></h6>
  <div id="contactKnowledgeList"><div class="text-muted small">—</div></div>
  <div class="mt-2"><a class="btn btn-sm crm-btn-primary" href="index.php?route=knowledge" id="contactKnowledgeLink" data-i18n="contacts.btn_knowledge"><?= htmlspecialchars($t('contacts.btn_knowledge', 'Перейти в базу знаний'), ENT_QUOTES, 'UTF-8') ?></a></div>
</div>
</div><div class="modal-footer"><button class="btn crm-btn-secondary" type="button" data-bs-dismiss="modal" data-i18n="page.cancel"><?= htmlspecialchars($t('page.cancel', 'Отмена'), ENT_QUOTES, 'UTF-8') ?></button><button class="btn crm-btn-danger-soft me-auto" type="button" id="contactsDeleteInModalBtn" data-i18n="contacts.btn_delete"><?= htmlspecialchars($t('contacts.btn_delete', 'Удалить контакт'), ENT_QUOTES, 'UTF-8') ?></button><button class="btn crm-btn-primary" type="submit" data-i18n="page.save"><?= htmlspecialchars($t('page.save', 'Сохранить'), ENT_QUOTES, 'UTF-8') ?></button></div></form></div></div></div>
<script>
(function () {
  var editModal = document.getElementById('contactEditModal');
  if (!editModal) return;
  var knowledgeSection = document.getElementById('contactKnowledgeSection');
  var knowledgeList = document.getElementById('contactKnowledgeList');
  if (!knowledgeSection || !knowledgeList) return;
  editModal.addEventListener('show.bs.modal', function () {
    var contactIdInput = document.querySelector('#contactsEditForm input[name="public_id"]');
    var contactId = contactIdInput ? contactIdInput.value : '';
    if (!contactId) { knowledgeList.innerHTML = '<div class="text-muted small">—</div>'; return; }
    var link = document.getElementById('contactKnowledgeLink');
    if (link) link.href = 'index.php?route=knowledge&entity_type=contact&entity_public_id=' + encodeURIComponent(contactId);
    knowledgeList.innerHTML = '<div class="text-muted small"><?= htmlspecialchars($t('page.loading', 'Загрузка...'), ENT_QUOTES, 'UTF-8') ?></div>';
    (async function () {
      try {
        var api = window.CRM && window.CRM.api && typeof window.CRM.api.request === 'function' ? window.CRM.api : null;
        if (!api) return;
        var envelope = await api.request('api/v1/knowledge/entities/contact/' + encodeURIComponent(contactId) + '/pages', { method: 'GET' });
        var items = envelope.data && envelope.data.items || [];
        if (!items.length) {
          knowledgeList.innerHTML = '<div class="text-muted small"><?= htmlspecialchars($t('contacts.knowledge_empty', 'Нет связанных заметок'), ENT_QUOTES, 'UTF-8') ?></div>';
        } else {
          knowledgeList.innerHTML = '<ul class="list-unstyled mb-0 small">' + items.map(function (p) {
            return '<li class="mb-1"><a href="index.php?route=knowledge-page&amp;id=' + encodeURIComponent(p.public_id) + '">' + (function esc(v) { return String(v == null ? '' : v).replace(/[&<>"']/g, function(ch) { return ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'})[ch]; }); })(p.title || '') + '</a></li>';
          }).join('') + '</ul>';
        }
      } catch (e) {
        knowledgeList.innerHTML = '<div class="text-muted small">—</div>';
      }
    })();
  });
})();
</script>
</body>
