<?php declare(strict_types=1); ?>
<?php $title = $t('counterparties.title', 'TropaTT — Контрагенты'); ?>
<body data-page="counterparties" data-protected="1"><div class="crm-app">
<aside class="crm-sidebar"><div class="crm-brand"><span class="crm-brand-mark"></span> <?= htmlspecialchars($t('app.name', 'TropaTT'), ENT_QUOTES, 'UTF-8') ?></div><nav class="nav flex-column crm-nav"></nav></aside>
<div class="crm-main-wrap"><header class="crm-topbar py-2"><div class="container-fluid"></div></header>
<main class="crm-content crm-counterparties-page"><div class="crm-page-head"><div><ol class="breadcrumb mb-1"><li class="breadcrumb-item"><a href="index.php?route=dashboard" data-i18n="page.dashboard"><?= htmlspecialchars($t('page.dashboard', 'Главная'), ENT_QUOTES, 'UTF-8') ?></a></li></ol><h1 class="crm-page-title" data-i18n="counterparties.page_title"><?= htmlspecialchars($t('counterparties.page_title', 'Контрагенты'), ENT_QUOTES, 'UTF-8') ?></h1><p class="crm-subtitle" data-i18n="counterparties.page_subtitle"><?= htmlspecialchars($t('counterparties.page_subtitle', 'Единый справочник контрагентов: организации, физлица, ИП.'), ENT_QUOTES, 'UTF-8') ?></p></div><div class="crm-page-actions crm-counterparties-actions"><div class="crm-counterparties-action-group"><select id="counterpartiesSavedViewSelect" class="form-select form-select-sm crm-field-w-220" aria-label="<?= htmlspecialchars($t('counterparties.saved_view_aria', 'Сохраненные виды'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-aria-label="counterparties.saved_view_aria"><option value="" data-i18n="counterparties.opt_default_view"><?= htmlspecialchars($t('counterparties.opt_default_view', 'Вид по умолчанию'), ENT_QUOTES, 'UTF-8') ?></option></select><button id="counterpartiesSaveViewBtn" class="btn crm-btn-secondary" type="button" data-i18n="counterparties.btn_save_view"><?= htmlspecialchars($t('counterparties.btn_save_view', 'Сохранить вид'), ENT_QUOTES, 'UTF-8') ?></button><button id="counterpartiesDeleteViewBtn" class="btn crm-btn-secondary" type="button" disabled data-i18n="counterparties.btn_delete_view"><?= htmlspecialchars($t('counterparties.btn_delete_view', 'Удалить вид'), ENT_QUOTES, 'UTF-8') ?></button></div><div class="crm-counterparties-action-group crm-counterparties-action-group-links"><a class="btn crm-btn-secondary" href="index.php?route=clients" data-i18n="counterparties.link_clients"><?= htmlspecialchars($t('counterparties.link_clients', 'Клиенты'), ENT_QUOTES, 'UTF-8') ?></a><a class="btn crm-btn-secondary" href="index.php?route=companies" data-i18n="counterparties.link_companies"><?= htmlspecialchars($t('counterparties.link_companies', 'Компании'), ENT_QUOTES, 'UTF-8') ?></a><a class="btn crm-btn-secondary" href="index.php?route=contacts" data-i18n="counterparties.link_contacts"><?= htmlspecialchars($t('counterparties.link_contacts', 'Контакты'), ENT_QUOTES, 'UTF-8') ?></a></div><div class="crm-counterparties-action-group crm-counterparties-action-group-main"><button class="btn crm-btn-muted" type="button" id="counterpartiesCompactToggle" data-i18n="counterparties.btn_compact"><?= htmlspecialchars($t('counterparties.btn_compact', 'Компактный вид'), ENT_QUOTES, 'UTF-8') ?></button><button class="btn crm-btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#counterpartyCreateModal" data-i18n="counterparties.btn_create"><?= htmlspecialchars($t('counterparties.btn_create', 'Создать контрагента'), ENT_QUOTES, 'UTF-8') ?></button></div></div></div>

<div class="crm-card crm-section-card crm-filters-card mb-3">
  <div class="row g-2 crm-counterparties-filters">
    <div class="col-md-5"><label class="form-label" for="counterpartiesFilterSearch" data-i18n="counterparties.filter_search_label"><?= htmlspecialchars($t('counterparties.filter_search_label', 'Поиск'), ENT_QUOTES, 'UTF-8') ?></label><input id="counterpartiesFilterSearch" class="form-control" aria-label="<?= htmlspecialchars($t('counterparties.filter_search_aria', 'Поиск по контрагентам'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-aria-label="counterparties.filter_search_aria" placeholder="<?= htmlspecialchars($t('counterparties.filter_search_placeholder', 'Название, ИНН, email, телефон, сайт'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-placeholder="counterparties.filter_search_placeholder"></div>
    <div class="col-md-3"><label class="form-label" for="counterpartiesFilterType" data-i18n="counterparties.filter_type_label"><?= htmlspecialchars($t('counterparties.filter_type_label', 'Тип'), ENT_QUOTES, 'UTF-8') ?></label><select id="counterpartiesFilterType" class="form-select" aria-label="<?= htmlspecialchars($t('counterparties.filter_type_aria', 'Тип контрагента'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-aria-label="counterparties.filter_type_aria"><option value="" data-i18n="page.all_types"><?= htmlspecialchars($t('page.all_types', 'Все типы'), ENT_QUOTES, 'UTF-8') ?></option><option value="organization" data-i18n="counterparties.type_organization"><?= htmlspecialchars($t('counterparties.type_organization', 'Организация'), ENT_QUOTES, 'UTF-8') ?></option><option value="individual" data-i18n="counterparties.type_individual"><?= htmlspecialchars($t('counterparties.type_individual', 'Физлицо'), ENT_QUOTES, 'UTF-8') ?></option><option value="sole_proprietor" data-i18n="counterparties.type_sole_proprietor"><?= htmlspecialchars($t('counterparties.type_sole_proprietor', 'ИП'), ENT_QUOTES, 'UTF-8') ?></option><option value="legal_entity" data-i18n="counterparties.type_legal_entity"><?= htmlspecialchars($t('counterparties.type_legal_entity', 'Юрлицо'), ENT_QUOTES, 'UTF-8') ?></option></select></div>
    <div class="col-md-2"><label class="form-label" for="counterpartiesFilterStatus" data-i18n="counterparties.filter_status_label"><?= htmlspecialchars($t('counterparties.filter_status_label', 'Статус'), ENT_QUOTES, 'UTF-8') ?></label><input id="counterpartiesFilterStatus" class="form-control" aria-label="<?= htmlspecialchars($t('counterparties.filter_status_aria', 'Статус контрагента'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-aria-label="counterparties.filter_status_aria" placeholder="<?= htmlspecialchars($t('counterparties.filter_status_placeholder', 'Активен'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-placeholder="counterparties.filter_status_placeholder"></div>
    <div class="col-md-2"><label class="form-label" for="counterpartiesFilterHasWebsite" data-i18n="counterparties.filter_website_label"><?= htmlspecialchars($t('counterparties.filter_website_label', 'Сайт'), ENT_QUOTES, 'UTF-8') ?></label><select id="counterpartiesFilterHasWebsite" class="form-select" aria-label="<?= htmlspecialchars($t('counterparties.filter_website_aria', 'Наличие сайта'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-aria-label="counterparties.filter_website_aria"><option value="" data-i18n="page.any"><?= htmlspecialchars($t('page.any', 'Любой'), ENT_QUOTES, 'UTF-8') ?></option><option value="1" data-i18n="counterparties.filter_website_with"><?= htmlspecialchars($t('counterparties.filter_website_with', 'Только с сайтом'), ENT_QUOTES, 'UTF-8') ?></option><option value="0" data-i18n="counterparties.filter_website_without"><?= htmlspecialchars($t('counterparties.filter_website_without', 'Без сайта'), ENT_QUOTES, 'UTF-8') ?></option></select></div>
    <div class="col-md-3"><label class="form-label" for="counterpartiesFilterCreatedFrom" data-i18n="counterparties.filter_created_from_label"><?= htmlspecialchars($t('counterparties.filter_created_from_label', 'Создан с'), ENT_QUOTES, 'UTF-8') ?></label><input id="counterpartiesFilterCreatedFrom" type="date" class="form-control" aria-label="<?= htmlspecialchars($t('counterparties.filter_created_from_aria', 'Дата создания с'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-aria-label="counterparties.filter_created_from_aria"></div>
    <div class="col-md-3"><label class="form-label" for="counterpartiesFilterCreatedTo" data-i18n="counterparties.filter_created_to_label"><?= htmlspecialchars($t('counterparties.filter_created_to_label', 'Создан по'), ENT_QUOTES, 'UTF-8') ?></label><input id="counterpartiesFilterCreatedTo" type="date" class="form-control" aria-label="<?= htmlspecialchars($t('counterparties.filter_created_to_aria', 'Дата создания по'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-aria-label="counterparties.filter_created_to_aria"></div>
    <div class="col-md-3"><label class="form-label" for="counterpartiesSortBy" data-i18n="counterparties.sort_by_label"><?= htmlspecialchars($t('counterparties.sort_by_label', 'Сортировка'), ENT_QUOTES, 'UTF-8') ?></label><select id="counterpartiesSortBy" class="form-select" aria-label="<?= htmlspecialchars($t('counterparties.sort_by_aria', 'Поле сортировки'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-aria-label="counterparties.sort_by_aria"><option value="created_at" data-i18n="counterparties.sort_created_at"><?= htmlspecialchars($t('counterparties.sort_created_at', 'Дата создания'), ENT_QUOTES, 'UTF-8') ?></option><option value="updated_at" data-i18n="counterparties.sort_updated_at"><?= htmlspecialchars($t('counterparties.sort_updated_at', 'Дата обновления'), ENT_QUOTES, 'UTF-8') ?></option><option value="title" data-i18n="counterparties.sort_title"><?= htmlspecialchars($t('counterparties.sort_title', 'Название'), ENT_QUOTES, 'UTF-8') ?></option></select></div>
    <div class="col-md-3"><label class="form-label" for="counterpartiesSortDir" data-i18n="counterparties.sort_dir_label"><?= htmlspecialchars($t('counterparties.sort_dir_label', 'Направление'), ENT_QUOTES, 'UTF-8') ?></label><select id="counterpartiesSortDir" class="form-select" aria-label="<?= htmlspecialchars($t('counterparties.sort_dir_aria', 'Направление сортировки'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-aria-label="counterparties.sort_dir_aria"><option value="DESC" data-i18n="counterparties.sort_desc"><?= htmlspecialchars($t('counterparties.sort_desc', 'По убыванию'), ENT_QUOTES, 'UTF-8') ?></option><option value="ASC" data-i18n="counterparties.sort_asc"><?= htmlspecialchars($t('counterparties.sort_asc', 'По возрастанию'), ENT_QUOTES, 'UTF-8') ?></option></select></div>
    <div class="col-12 d-flex justify-content-end"><button class="btn crm-btn-muted" type="button" id="counterpartiesFilterReset" data-i18n="page.reset"><?= htmlspecialchars($t('page.reset', 'Сбросить'), ENT_QUOTES, 'UTF-8') ?></button></div>
  </div>
</div>

<div id="counterpartiesBulkActionsBar" class="alert alert-primary d-none d-flex justify-content-between align-items-center" role="region" aria-label="<?= htmlspecialchars($t('counterparties.bulk_aria_label', 'Bulk actions counterparties'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-aria-label="counterparties.bulk_aria_label">
  <div><span data-i18n="counterparties.bulk_selected_prefix"><?= htmlspecialchars($t('counterparties.bulk_selected_prefix', 'Выбрано контрагентов:'), ENT_QUOTES, 'UTF-8') ?></span> <strong data-counterparties-selected-count>0</strong> <span class="small ms-2" id="counterpartiesBulkResult" aria-live="polite"></span></div>
  <div class="d-flex gap-2">
    <select id="counterpartiesBulkStatusSelect" class="form-select form-select-sm crm-field-w-170" aria-label="<?= htmlspecialchars($t('counterparties.bulk_status_aria', 'Изменить статус'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-aria-label="counterparties.bulk_status_aria">
      <option value="" data-i18n="page.status_placeholder"><?= htmlspecialchars($t('page.status_placeholder', 'Статус...'), ENT_QUOTES, 'UTF-8') ?></option>
      <option value="active" data-i18n="counterparties.status_active"><?= htmlspecialchars($t('counterparties.status_active', 'Активен'), ENT_QUOTES, 'UTF-8') ?></option>
      <option value="inactive" data-i18n="counterparties.status_inactive"><?= htmlspecialchars($t('counterparties.status_inactive', 'Неактивен'), ENT_QUOTES, 'UTF-8') ?></option>
      <option value="archived" data-i18n="counterparties.status_archived"><?= htmlspecialchars($t('counterparties.status_archived', 'Архив'), ENT_QUOTES, 'UTF-8') ?></option>
    </select>
    <button class="btn btn-sm crm-btn-danger-soft" type="button" id="counterpartiesBulkDeleteBtn" data-confirm-delete disabled data-i18n="page.delete"><?= htmlspecialchars($t('page.delete', 'Удалить'), ENT_QUOTES, 'UTF-8') ?></button>
  </div>
</div>

<div class="crm-card crm-section-card p-0 table-responsive crm-counterparties-table-wrap"><table id="counterpartiesTable" class="table crm-table mb-0"><thead><tr><th style="width:40px"><input class="form-check-input" type="checkbox" id="counterpartiesBulkSelectAll" aria-label="<?= htmlspecialchars($t('counterparties.bulk_select_all_aria', 'Выбрать всех контрагентов'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-aria-label="counterparties.bulk_select_all_aria"></th><th data-i18n="counterparties.th_name"><?= htmlspecialchars($t('counterparties.th_name', 'Контрагент'), ENT_QUOTES, 'UTF-8') ?></th><th><?= htmlspecialchars($t('counterparties.th_type', 'Тип') . ' / ' . $t('counterparties.th_status', 'Статус'), ENT_QUOTES, 'UTF-8') ?></th><th><?= htmlspecialchars($t('counterparties.th_email', 'Email') . ' / ' . $t('counterparties.th_phone', 'Телефон'), ENT_QUOTES, 'UTF-8') ?></th><th data-i18n="counterparties.th_extra"><?= htmlspecialchars($t('counterparties.th_extra', 'Доп. поля'), ENT_QUOTES, 'UTF-8') ?></th><th data-i18n="counterparties.th_updated"><?= htmlspecialchars($t('counterparties.th_updated', 'Обновлен'), ENT_QUOTES, 'UTF-8') ?></th><th style="width:96px" data-i18n="counterparties.th_actions"><?= htmlspecialchars($t('counterparties.th_actions', 'Действия'), ENT_QUOTES, 'UTF-8') ?></th></tr></thead><tbody id="counterpartiesTableBody"><tr><td colspan="7" class="text-muted" data-i18n="counterparties.loading"><?= htmlspecialchars($t('counterparties.loading', 'Загрузка контрагентов...'), ENT_QUOTES, 'UTF-8') ?></td></tr></tbody></table></div>
<div id="counterpartiesMobileList" class="crm-counterparties-mobile-list d-none" aria-live="polite"></div>
<?= module_position('counterparties.content.after', ['route' => $route ?? 'counterparties']) ?>
</main></div></div>

<div class="modal fade" id="counterpartyCreateModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-xl modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" data-i18n="counterparties.create_modal_title"><?= htmlspecialchars($t('counterparties.create_modal_title', 'Создать контрагента'), ENT_QUOTES, 'UTF-8') ?></h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="<?= htmlspecialchars($t('page.close', 'Закрыть'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-aria-label="page.close"></button></div><form id="counterpartiesCreateForm" novalidate><div class="modal-body"><div class="row g-3">
  <div class="col-12 d-none" data-form-error-summary></div>
  <div class="col-md-4"><label class="form-label" for="counterpartyCreateType" data-i18n="counterparties.field_type"><?= htmlspecialchars($t('counterparties.field_type', 'Тип контрагента'), ENT_QUOTES, 'UTF-8') ?></label><select class="form-select" id="counterpartyCreateType" name="counterparty_type" data-counterparty-type-input><option value="organization" data-i18n="counterparties.type_organization"><?= htmlspecialchars($t('counterparties.type_organization', 'Организация'), ENT_QUOTES, 'UTF-8') ?></option><option value="individual" data-i18n="counterparties.type_individual"><?= htmlspecialchars($t('counterparties.type_individual', 'Физлицо'), ENT_QUOTES, 'UTF-8') ?></option><option value="sole_proprietor" data-i18n="counterparties.type_sole_proprietor"><?= htmlspecialchars($t('counterparties.type_sole_proprietor', 'ИП'), ENT_QUOTES, 'UTF-8') ?></option><option value="legal_entity" data-i18n="counterparties.type_legal_entity"><?= htmlspecialchars($t('counterparties.type_legal_entity', 'Юрлицо'), ENT_QUOTES, 'UTF-8') ?></option></select></div>
  <div class="col-md-8"><label class="form-label" for="counterpartyCreateTitle" data-i18n="counterparties.field_title"><?= htmlspecialchars($t('counterparties.field_title', 'Название'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" id="counterpartyCreateTitle" name="title" maxlength="255" required></div>
  <div class="col-md-6" data-counterparty-type-group="sole_proprietor,legal_entity"><label class="form-label" for="counterpartyCreateLegalName" data-i18n="counterparties.field_legal_name"><?= htmlspecialchars($t('counterparties.field_legal_name', 'Юридическое наименование / ФИО ИП'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" id="counterpartyCreateLegalName" name="legal_name" maxlength="255"></div>
  <div class="col-md-4" data-counterparty-type-group="sole_proprietor,legal_entity"><label class="form-label" for="counterpartyCreateInn" data-i18n="counterparties.field_inn"><?= htmlspecialchars($t('counterparties.field_inn', 'ИНН'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" id="counterpartyCreateInn" name="tax_inn" maxlength="12"></div>
  <div class="col-md-4" data-counterparty-type-group="legal_entity"><label class="form-label" for="counterpartyCreateKpp" data-i18n="counterparties.field_kpp"><?= htmlspecialchars($t('counterparties.field_kpp', 'КПП'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" id="counterpartyCreateKpp" name="tax_kpp" maxlength="9"></div>
  <div class="col-md-4" data-counterparty-type-group="legal_entity"><label class="form-label" for="counterpartyCreateOgrn" data-i18n="counterparties.field_ogrn"><?= htmlspecialchars($t('counterparties.field_ogrn', 'ОГРН'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" id="counterpartyCreateOgrn" name="tax_ogrn" maxlength="13"></div>
  <div class="col-md-4" data-counterparty-type-group="sole_proprietor"><label class="form-label" for="counterpartyCreateOgrnip" data-i18n="counterparties.field_ogrnip"><?= htmlspecialchars($t('counterparties.field_ogrnip', 'ОГРНИП'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" id="counterpartyCreateOgrnip" name="tax_ogrnip" maxlength="15"></div>
  <div class="col-md-4"><label class="form-label" for="counterpartyCreateEmail" data-i18n="counterparties.field_email"><?= htmlspecialchars($t('counterparties.field_email', 'Email'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" id="counterpartyCreateEmail" type="email" name="email" maxlength="190"></div>
  <div class="col-md-4"><label class="form-label" for="counterpartyCreatePhone" data-i18n="counterparties.field_phone"><?= htmlspecialchars($t('counterparties.field_phone', 'Телефон'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" id="counterpartyCreatePhone" name="phone" maxlength="64"></div>
  <div class="col-md-4"><label class="form-label" for="counterpartyCreateWebsite" data-i18n="counterparties.field_website"><?= htmlspecialchars($t('counterparties.field_website', 'Сайт'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" id="counterpartyCreateWebsite" name="website" maxlength="2048" placeholder="<?= htmlspecialchars($t('counterparties.placeholder_website', 'https://example.com'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-placeholder="counterparties.placeholder_website"></div>
  <div class="col-md-4"><label class="form-label" for="counterpartyCreateMessenger" data-i18n="counterparties.field_messenger"><?= htmlspecialchars($t('counterparties.field_messenger', 'Мессенджер'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" id="counterpartyCreateMessenger" name="messenger" maxlength="190"></div>
  <div class="col-md-4" data-counterparty-type-group="sole_proprietor,legal_entity"><label class="form-label" for="counterpartyCreateBankAccount" data-i18n="counterparties.field_bank_account"><?= htmlspecialchars($t('counterparties.field_bank_account', 'Расчетный счет'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" id="counterpartyCreateBankAccount" name="bank_account" maxlength="34"></div>
  <div class="col-md-4" data-counterparty-type-group="sole_proprietor,legal_entity"><label class="form-label" for="counterpartyCreateBik" data-i18n="counterparties.field_bik"><?= htmlspecialchars($t('counterparties.field_bik', 'БИК'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" id="counterpartyCreateBik" name="bank_bik" maxlength="9"></div>
  <div class="col-md-4" data-counterparty-type-group="sole_proprietor,legal_entity"><label class="form-label" for="counterpartyCreateCorrAccount" data-i18n="counterparties.field_corr_account"><?= htmlspecialchars($t('counterparties.field_corr_account', 'Корр. счет'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" id="counterpartyCreateCorrAccount" name="bank_corr_account" maxlength="34"></div>
  <div class="col-md-8" data-counterparty-type-group="sole_proprietor,legal_entity"><label class="form-label" for="counterpartyCreateBankName" data-i18n="counterparties.field_bank_name"><?= htmlspecialchars($t('counterparties.field_bank_name', 'Банк'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" id="counterpartyCreateBankName" name="bank_name" maxlength="255"></div>
  <div class="col-md-4"><label class="form-label" for="counterpartyCreateStatus" data-i18n="counterparties.field_status"><?= htmlspecialchars($t('counterparties.field_status', 'Статус'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" id="counterpartyCreateStatus" name="status" maxlength="64" value="active"></div>
  <div class="col-md-6"><label class="form-label" data-i18n="counterparties.field_address_legal"><?= htmlspecialchars($t('counterparties.field_address_legal', 'Юридический адрес'), ENT_QUOTES, 'UTF-8') ?></label><textarea class="form-control" name="address_legal" rows="2"></textarea></div>
  <div class="col-md-6"><label class="form-label" data-i18n="counterparties.field_address_postal"><?= htmlspecialchars($t('counterparties.field_address_postal', 'Почтовый адрес'), ENT_QUOTES, 'UTF-8') ?></label><textarea class="form-control" name="address_postal" rows="2"></textarea></div>
  <div class="col-12"><label class="form-label" data-i18n="counterparties.field_extra_attributes"><?= htmlspecialchars($t('counterparties.field_extra_attributes', 'Дополнительные поля (JSON)'), ENT_QUOTES, 'UTF-8') ?></label><textarea class="form-control font-monospace" name="extra_attributes_text" rows="3" placeholder="{&quot;key&quot;: &quot;value&quot;}"></textarea><div class="form-text" data-i18n="counterparties.extra_attributes_hint"><?= htmlspecialchars($t('counterparties.extra_attributes_hint', 'Укажите дополнительные поля в формате JSON.'), ENT_QUOTES, 'UTF-8') ?></div></div>
  <div class="col-12"><label class="form-label" data-i18n="counterparties.field_notes"><?= htmlspecialchars($t('counterparties.field_notes', 'Комментарий'), ENT_QUOTES, 'UTF-8') ?></label><textarea class="form-control" name="notes" rows="2"></textarea></div>
</div></div><div class="modal-footer"><button class="btn crm-btn-secondary" type="button" data-bs-dismiss="modal" data-i18n="page.cancel"><?= htmlspecialchars($t('page.cancel', 'Отмена'), ENT_QUOTES, 'UTF-8') ?></button><button class="btn crm-btn-primary" type="submit" data-i18n="page.create"><?= htmlspecialchars($t('page.create', 'Создать'), ENT_QUOTES, 'UTF-8') ?></button></div></form></div></div></div>

<div class="modal fade" id="counterpartyEditModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-xl modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" data-i18n="counterparties.edit_modal_title"><?= htmlspecialchars($t('counterparties.edit_modal_title', 'Редактировать контрагента'), ENT_QUOTES, 'UTF-8') ?></h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="<?= htmlspecialchars($t('page.close', 'Закрыть'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-aria-label="page.close"></button></div><form id="counterpartiesEditForm" novalidate><div class="modal-body"><input type="hidden" name="public_id"><div class="row g-3">
  <div class="col-12 d-none" data-form-error-summary></div>
  <div class="col-md-4"><label class="form-label" for="counterpartyEditType" data-i18n="counterparties.field_type"><?= htmlspecialchars($t('counterparties.field_type', 'Тип контрагента'), ENT_QUOTES, 'UTF-8') ?></label><select class="form-select" id="counterpartyEditType" name="counterparty_type" data-counterparty-type-input><option value="organization" data-i18n="counterparties.type_organization"><?= htmlspecialchars($t('counterparties.type_organization', 'Организация'), ENT_QUOTES, 'UTF-8') ?></option><option value="individual" data-i18n="counterparties.type_individual"><?= htmlspecialchars($t('counterparties.type_individual', 'Физлицо'), ENT_QUOTES, 'UTF-8') ?></option><option value="sole_proprietor" data-i18n="counterparties.type_sole_proprietor"><?= htmlspecialchars($t('counterparties.type_sole_proprietor', 'ИП'), ENT_QUOTES, 'UTF-8') ?></option><option value="legal_entity" data-i18n="counterparties.type_legal_entity"><?= htmlspecialchars($t('counterparties.type_legal_entity', 'Юрлицо'), ENT_QUOTES, 'UTF-8') ?></option></select></div>
  <div class="col-md-8"><label class="form-label" for="counterpartyEditTitle" data-i18n="counterparties.field_title"><?= htmlspecialchars($t('counterparties.field_title', 'Название'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" id="counterpartyEditTitle" name="title" maxlength="255" required></div>
  <div class="col-md-6" data-counterparty-type-group="sole_proprietor,legal_entity"><label class="form-label" for="counterpartyEditLegalName" data-i18n="counterparties.field_legal_name"><?= htmlspecialchars($t('counterparties.field_legal_name', 'Юридическое наименование / ФИО ИП'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" id="counterpartyEditLegalName" name="legal_name" maxlength="255"></div>
  <div class="col-md-4" data-counterparty-type-group="sole_proprietor,legal_entity"><label class="form-label" for="counterpartyEditInn" data-i18n="counterparties.field_inn"><?= htmlspecialchars($t('counterparties.field_inn', 'ИНН'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" id="counterpartyEditInn" name="tax_inn" maxlength="12"></div>
  <div class="col-md-4" data-counterparty-type-group="legal_entity"><label class="form-label" for="counterpartyEditKpp" data-i18n="counterparties.field_kpp"><?= htmlspecialchars($t('counterparties.field_kpp', 'КПП'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" id="counterpartyEditKpp" name="tax_kpp" maxlength="9"></div>
  <div class="col-md-4" data-counterparty-type-group="legal_entity"><label class="form-label" for="counterpartyEditOgrn" data-i18n="counterparties.field_ogrn"><?= htmlspecialchars($t('counterparties.field_ogrn', 'ОГРН'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" id="counterpartyEditOgrn" name="tax_ogrn" maxlength="13"></div>
  <div class="col-md-4" data-counterparty-type-group="sole_proprietor"><label class="form-label" for="counterpartyEditOgrnip" data-i18n="counterparties.field_ogrnip"><?= htmlspecialchars($t('counterparties.field_ogrnip', 'ОГРНИП'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" id="counterpartyEditOgrnip" name="tax_ogrnip" maxlength="15"></div>
  <div class="col-md-4"><label class="form-label" for="counterpartyEditEmail" data-i18n="counterparties.field_email"><?= htmlspecialchars($t('counterparties.field_email', 'Email'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" id="counterpartyEditEmail" type="email" name="email" maxlength="190"></div>
  <div class="col-md-4"><label class="form-label" for="counterpartyEditPhone" data-i18n="counterparties.field_phone"><?= htmlspecialchars($t('counterparties.field_phone', 'Телефон'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" id="counterpartyEditPhone" name="phone" maxlength="64"></div>
  <div class="col-md-4"><label class="form-label" for="counterpartyEditWebsite" data-i18n="counterparties.field_website"><?= htmlspecialchars($t('counterparties.field_website', 'Сайт'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" id="counterpartyEditWebsite" name="website" maxlength="2048"></div>
  <div class="col-md-4"><label class="form-label" for="counterpartyEditMessenger" data-i18n="counterparties.field_messenger"><?= htmlspecialchars($t('counterparties.field_messenger', 'Мессенджер'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" id="counterpartyEditMessenger" name="messenger" maxlength="190"></div>
  <div class="col-md-4" data-counterparty-type-group="sole_proprietor,legal_entity"><label class="form-label" for="counterpartyEditBankAccount" data-i18n="counterparties.field_bank_account"><?= htmlspecialchars($t('counterparties.field_bank_account', 'Расчетный счет'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" id="counterpartyEditBankAccount" name="bank_account" maxlength="34"></div>
  <div class="col-md-4" data-counterparty-type-group="sole_proprietor,legal_entity"><label class="form-label" for="counterpartyEditBik" data-i18n="counterparties.field_bik"><?= htmlspecialchars($t('counterparties.field_bik', 'БИК'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" id="counterpartyEditBik" name="bank_bik" maxlength="9"></div>
  <div class="col-md-4" data-counterparty-type-group="sole_proprietor,legal_entity"><label class="form-label" for="counterpartyEditCorrAccount" data-i18n="counterparties.field_corr_account"><?= htmlspecialchars($t('counterparties.field_corr_account', 'Корр. счет'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" id="counterpartyEditCorrAccount" name="bank_corr_account" maxlength="34"></div>
  <div class="col-md-8" data-counterparty-type-group="sole_proprietor,legal_entity"><label class="form-label" for="counterpartyEditBankName" data-i18n="counterparties.field_bank_name"><?= htmlspecialchars($t('counterparties.field_bank_name', 'Банк'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" id="counterpartyEditBankName" name="bank_name" maxlength="255"></div>
  <div class="col-md-4"><label class="form-label" for="counterpartyEditStatus" data-i18n="counterparties.field_status"><?= htmlspecialchars($t('counterparties.field_status', 'Статус'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" id="counterpartyEditStatus" name="status" maxlength="64"></div>
  <div class="col-md-6"><label class="form-label" data-i18n="counterparties.field_address_legal"><?= htmlspecialchars($t('counterparties.field_address_legal', 'Юридический адрес'), ENT_QUOTES, 'UTF-8') ?></label><textarea class="form-control" name="address_legal" rows="2"></textarea></div>
  <div class="col-md-6"><label class="form-label" data-i18n="counterparties.field_address_postal"><?= htmlspecialchars($t('counterparties.field_address_postal', 'Почтовый адрес'), ENT_QUOTES, 'UTF-8') ?></label><textarea class="form-control" name="address_postal" rows="2"></textarea></div>
  <div class="col-12"><label class="form-label" data-i18n="counterparties.field_extra_attributes"><?= htmlspecialchars($t('counterparties.field_extra_attributes', 'Дополнительные поля (JSON)'), ENT_QUOTES, 'UTF-8') ?></label><textarea class="form-control font-monospace" name="extra_attributes_text" rows="3" placeholder="{&quot;key&quot;: &quot;value&quot;}"></textarea><div class="form-text" data-i18n="counterparties.extra_attributes_hint"><?= htmlspecialchars($t('counterparties.extra_attributes_hint', 'Укажите дополнительные поля в формате JSON.'), ENT_QUOTES, 'UTF-8') ?></div></div>
  <div class="col-12"><label class="form-label" data-i18n="counterparties.field_notes"><?= htmlspecialchars($t('counterparties.field_notes', 'Комментарий'), ENT_QUOTES, 'UTF-8') ?></label><textarea class="form-control" name="notes" rows="2"></textarea></div>
</div></div><div class="modal-footer"><button class="btn crm-btn-secondary" type="button" data-bs-dismiss="modal" data-i18n="page.cancel"><?= htmlspecialchars($t('page.cancel', 'Отмена'), ENT_QUOTES, 'UTF-8') ?></button><button class="btn crm-btn-danger-soft me-auto" type="button" id="counterpartiesDeleteInModalBtn" data-i18n="counterparties.btn_delete"><?= htmlspecialchars($t('counterparties.btn_delete', 'Удалить контрагента'), ENT_QUOTES, 'UTF-8') ?></button><button class="btn crm-btn-primary" type="submit" data-i18n="page.save"><?= htmlspecialchars($t('page.save', 'Сохранить'), ENT_QUOTES, 'UTF-8') ?></button></div></form></div></div></div>

<div class="modal fade" id="counterpartiesSaveViewModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" data-i18n="counterparties.save_view_modal_title"><?= htmlspecialchars($t('counterparties.save_view_modal_title', 'Сохранить вид контрагентов'), ENT_QUOTES, 'UTF-8') ?></h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="<?= htmlspecialchars($t('page.close', 'Закрыть'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-aria-label="page.close"></button></div><form id="counterpartiesSaveViewForm" novalidate><div class="modal-body"><div class="mb-3"><label class="form-label" for="counterpartiesSaveViewTitle" data-i18n="counterparties.save_view_field_title"><?= htmlspecialchars($t('counterparties.save_view_field_title', 'Название вида'), ENT_QUOTES, 'UTF-8') ?></label><input class="form-control" id="counterpartiesSaveViewTitle" name="title" maxlength="120" required placeholder="<?= htmlspecialchars($t('counterparties.save_view_placeholder', 'Например: Активные организации'), ENT_QUOTES, 'UTF-8') ?>" data-i18n-placeholder="counterparties.save_view_placeholder"></div><div class="small text-muted" id="counterpartiesSaveViewHint" data-i18n="counterparties.save_view_hint"><?= htmlspecialchars($t('counterparties.save_view_hint', 'Будут сохранены текущие фильтры и сортировка.'), ENT_QUOTES, 'UTF-8') ?></div></div><div class="modal-footer"><button class="btn crm-btn-secondary" type="button" data-bs-dismiss="modal" data-i18n="page.cancel"><?= htmlspecialchars($t('page.cancel', 'Отмена'), ENT_QUOTES, 'UTF-8') ?></button><button class="btn crm-btn-primary" type="submit" data-i18n="page.save"><?= htmlspecialchars($t('page.save', 'Сохранить'), ENT_QUOTES, 'UTF-8') ?></button></div></form></div></div></div>
</body>
